### ISSUE TITLE
VERIFIER_nondet functions do not work properly for unsigned types

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#102]
Here is an example:

```
#include "smack.h"

int main(void) {
  unsigned x = __VERIFIER_nondet_unsigned();
  assert (x > 0);
}
```

This should I believe pass, and yet it does not.
If you look at `smack-svcomp.h`, unsigned nondet functions there assume that the returned value is >= 0. I am not sure if that is the best solution.

**Comment by MontyCarter** [comment]
Does it work if you correct the assertion?  `assert (x >= 0)`...  ;)

Also, is this within the context of the svcomp pull request (#100), or the develop branch as is?

**Comment by michael-emmi** [comment]
Note that this is not a problem in bit-precise mode — assuming you meant `assert (x>=0)`.
