### ISSUE TITLE
Small regtest.py bug

### ISSUE THREAD

**Issue by MontyCarter** [smackers/smack#103]
In [`regtest.py` line 86](https://github.com/smackers/smack/blob/ea903c86c0dccedb5627161a0b3debd3c565725e/test/regtest.py#L86), the old signature is used for a function call to `red()`.

This is causing `regtest.py` to crash if `// @expect` is not found in one of the regression tests.

**Comment by jon-whit** [comment]
I will fix this. I missed that in the code. Thanks!

**Comment by jon-whit** [comment]
Thanks for pointing this out. I overlooked it when I was adding the multi-threading support. I have submitted a pull request to fix the issue.
