### ISSUE TITLE
Cast int to double causes errors in bpl.

### ISSUE THREAD

**Issue by alexandrugyori** [smackers/smack#107]
Feeding the following program to smack produces a bpl with errors since si2fp.i32.float is undeclared in the resulting bpl.

int x = 0;
double y = 0.;

int main(int argc, char** argv)
{
  x = 6;
  y = (double)x;
}

**Comment by michael-emmi** [comment]
This issue has been fixed in commit 9ea39a600ba95626a86b478e8555188a1675c054 on the develop branch.
