### ISSUE TITLE
Z3 Installation Fails on Develop Branch

### ISSUE THREAD

**Issue by jon-whit** [smackers/smack#112]
I am opening this issue as a reminder to fix this. If someone beats me to it, kudos to you!

```
==> ubuntu: *** SMACK BUILD: Installed required packages ***
==> ubuntu: *** SMACK BUILD: Installing Z3 ***
==> ubuntu: https://github.com/Z3Prover/bin/blob/f139669240f613e86cac199e518dbc3541cf16bd/z3-4.4.0.1abeb825a35a-x64-ubuntu-14.04.zip?raw=true:
==> ubuntu: 2015-07-18 06:02:53 ERROR 404: Not Found.
```

**Comment by jon-whit** [comment]
Appears as though the directory at `https://github.com/Z3Prover/bin/blob` no longer exists. I believe what we are looking for is the file at `https://github.com/Z3Prover/bin/blob/master/releases/z3-4.4.0-x64-win.zip`. I will update the build script with this different path.

**Comment by zvonimir** [comment]
Your fix is not good. You are now pulling Z3 release for Windows (hence `win` in your link), which does not work on Linux. I will push a proper fix in 5 minutes, I know what changed here.

**Comment by jon-whit** [comment]
That's weird.. It worked fine in the VM that I was testing it with. Either way, good catch!
