### ISSUE TITLE
wget cannot download Z3 from codeplex

### ISSUE THREAD

**Issue by mwillsey** [smackers/smack#122]
Hi,

I've been trying to install `smack` through `vagrant up`, and it's running into an issue where it thinks the `z3-download.zip` file is corrupted. I ran the `wget` command from `build.sh` manually on my machine, and it looks like `wget` is just failing to follow the redirects and waiting that codeplex requires. Instead, I think it's just grabbing the html of the landing page and calling it `z3-download.zip`, which explains the corruption that the unzip on line 315 of `build.sh` sees.

I tried to get either `wget` or `curl` to download the correct file from [the link](http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=z3&DownloadId=923684&FileTime=130586905368570000&Build=20983) specified in `build.sh`, but I had no success. Maybe the binary should just be mirrored somewhere else?

Thanks!

**Comment by jon-whit** [comment]
Are you building from the `master` branch or `develop`?

**Comment by mwillsey** [comment]
Ok. I was building from `master`. Thanks for the update.

**Comment by jon-whit** [comment]
You are welcome!
