### ISSUE TITLE
Some SVCOMP examples breaking DSA

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#127]
As we are running SMACK on SVCOMP benchmarks, it is clear that some of them are breaking DSA. In particular, it appears that some of them cause recursion in `DSGraph::computeNodeMapping` to not terminate. I attached a relatively simple file that triggers this behavior:
[usb_urb-drivers-media-dvb-ttusb-dec-ttusb_dec.ko_false-unreach-call.cil.out.i.pp3.c](https://github.com/smackers/smack/files/3172/usb_urb-drivers-media-dvb-ttusb-dec-ttusb_dec.ko_false-unreach-call.cil.out.i.pp3.c)

**Comment by michael-emmi** [comment]
Can you elaborate on what “breaks”?

Can you give a simple example?

**Comment by zvonimir** [comment]
I updated my description above. I hope that helps.
