### ISSUE TITLE
building error - missing check for libedit

### ISSUE THREAD

**Issue by mchalupa** [smackers/smack#131]
Hi,
the cmake config files are missing a check for libedit library,  I'm getting this error:

/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
CMakeFiles/smack.dir/build.make:97: recipe for target 'smack' failed
make[2]: **\* [smack] Error 1
CMakeFiles/Makefile2:143: recipe for target 'CMakeFiles/smack.dir/all' failed
make[1]: **\* [CMakeFiles/smack.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

after installing libedit it works

**Comment by zvonimir** [comment]
Thanks for reporting this!
Which OS (exact version) are you experiencing this issues on?

**Comment by mchalupa** [comment]
It was Fedora 22 - more details I can't tell, because I updated to 23 few days ago and I don't remember the exact setup.

**Comment by zvonimir** [comment]
@liammachado : maybe you could try to explore this one. Basically, you should try to run `bin/build.sh` in a Fedora virtual machine, and see what happens. If it fails, and it likely will, it would be good to update `build.sh` to work with Fedora.

**Comment by zvonimir** [comment]
We cannot easily reproduce this problem and it is not clear whether it is still happening, and so I am closing it.
