### ISSUE TITLE
Allow smack to be used conveniently as a library

### ISSUE THREAD

**Issue by dbueno** [smackers/smack#143]
Currently smack is intended to be used from the command line. In my use case, I would like programmatic access to the Boogie AST, so I need to be able to invoke SMACK as a library. Currently I have a hacked together solution, but it would be great if this could be officially supported by SMACK.

**Comment by pdeligia** [comment]
You can get access to the Boogie AST (and then traverse and manipulate it) from your tool using directly the Boogie APIs (https://github.com/boogie-org/boogie). This does not work for you?

**Comment by zvonimir** [comment]
If you like Ruby, then there is this options as well: https://github.com/michael-emmi/bam-bam-boogieman
In general, it would be great if you could better describe your use case, and then we can see if we could accommodate it on our end.

**Comment by dbueno** [comment]
The boogie ast doesn't expose enough members to be usable this way. I had
to put public declarations in a lot of places. Have you tried using the ast
as a client?

On Fri, Dec 4, 2015, 9:35 AM Zvonimir <notifications@github.com> wrote:

> If you like Ruby, then there is this options as well:
> https://github.com/michael-emmi/bam-bam-boogieman
> In general, it would be great if you could better describe your use case,
> and then we can see if we could accommodate it on our end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smackers/smack/issues/143#issuecomment-162013836>.
>
-- 

Denis

**Comment by pdeligia** [comment]
You still have not given us enough information about your case study to understand what exactly you need, and why the current infrastructure is not enough. About what you say: I have written a tool that traverses the Boogie AST, and performs various complex transformations on it. It worked fine, without making any changes in the actual Boogie source code.

**Comment by dbueno** [comment]
Here's some of what I mean. All of these are changes on top of the v1.5.1 tag.
- There's no method to run smack on a file or a Module. I made one that looks like the main smack method but doesn't print the ast and takes a "continuation" llvm pass that can perform further processing.
- There was no public way to get the "expr" member of an AssertStmt. This kind of thing crops up frequently, where the members of ast types are not accessible publicly in any way (either directly or through a method). Pretty much every ast needed changing for this.

Does that help?

**Comment by zvonimir** [comment]
Yes, now I understand what you mean and it makes sense. Basically, you would like to do some post-processing on the ast to augment the translation. I find this usage scenario to be very interesting, and we are certainly totally open to accepting patches in that direction. So please help us out if you wish!

**Comment by shaobo-he** [comment]
@dbueno Please reopen this issue if you're still interested in it.
