### ISSUE TITLE
CFGSimplification pass broke error traces

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#150]
Hi guys,

It seems SMACK generates buggy error traces with a pass simplifying CFG[[1]](https://github.com/smackers/smack/blob/develop/tools/llvm2bpl/llvm2bpl.cpp#L104). To be more specific, let's take a look at a SVCOMP benchmark[[2]](https://github.com/sosy-lab/sv-benchmarks/blob/master/c/recursive/Ackermann02_false-unreach-call_false-termination.c) that has this issue,

``` c
int ackermann(int m, int n) {
    if (m==0) {
        return n+1;
    }
    if (n==0) {
        return ackermann(m-1,1);
    }
    return ackermann(m-1,ackermann(m,n-1));
}
```

One segment of its error trace is,

> Ackermann02_false-unreach-call_false-termination.c(28,18): Trace: Thread=1  (CALL ackermann)
> Ackermann02_false-unreach-call_false-termination.c(15,9): Trace: Thread=1
> Ackermann02_false-unreach-call_false-termination.c(18,9): Trace: Thread=1
> Ackermann02_false-unreach-call_false-termination.c(19,26): Trace: Thread=1
> Ackermann02_false-unreach-call_false-termination.c(18,9): Trace: Thread=1
> Ackermann02_false-unreach-call_false-termination.c(19,16): Trace: Thread=1

The function starts from line `14`. First if statement is in line `15` and second in `18`. Error trace assumes `m=2` and `n=0`. So the error trace segment is invalid since it is impossible for the program to go from line `19` back to line `18`. The reason why it occurs is that the optimization pass extracts expression `m-1` and move it before the first recursive call because this expression is passed to both recursive calls (`ackermann(m-1,1)` and `ackermann(m-1,ackermann(m,n-1))`) no matter if the condition `n==0` satisfies or not.

If we want to keep this pass if its effect is significantly beneficial, a fix would be to enforce statement line numbers in a basic block to be strictly increasing.

Thanks,
Shaobo

**Comment by zvonimir** [comment]
This has been fixed in e239d6daf743. Removing this pass did not significantly affect performance.
