### ISSUE TITLE
Installing SMACK

### ISSUE THREAD

**Issue by shazqadeer** [smackers/smack#156]
This is more of a question than an issue.  I am trying to install SMACK on my Windows machine via the Vagrant VM route.  When I executed "vagrant up", the command terminated with:

==> ubuntu: Mounting shared folders...
    ubuntu: /home/vagrant/smack => C:/Users/qadeer/Work/smack
==> ubuntu: Running provisioner: shell...
    ubuntu: Running: inline script
==> ubuntu: stdin: is not a tty
==> ubuntu: /tmp/vagrant-shell: ./smack/bin/build.sh: /bin/bash^M: bad interpreter: No such file or directory

What happened?

Also, what should I expect if "vagrant up" had finished successfully?  Does it mean that I will have a VM with SMACK, Boogie, Z3 precompiled on it ready for execution?  Or do I have to do further installation on the VM?

There is a typo on this page:  https://github.com/smackers/smack/wiki/System-Requirements-&-Installation.  Search for "suspect".

**Comment by Guoanshisb** [comment]
Hi Shaz,

It seems this is an issue with line endings. Can you check the line ending of `bin/build.sh` file (`CRLF` or `LF`)? If it is `CRLF` which is common on Windows machines, then you may want to convert it to unix format. Please refer to this webpage: http://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory.

Shaobo

**Comment by zvonimir** [comment]
Shaobo, have you seen my email on this I sent you half an hour ago?
See here: http://foo-o-rama.com/vagrant--stdin-is-not-a-tty--fix.html
This might be a different problem.

**Comment by shazqadeer** [comment]
I am thoroughly confused now.  Now, when I run "vagrant up", I get a different error message:

C:\Users\qadeer\Work\smack>vagrant up
Bringing machine 'ubuntu' up with 'virtualbox' provider...
==> ubuntu: Importing base box 'ubuntu/trusty64'...
==> ubuntu: Matching MAC address for NAT networking...
==> ubuntu: Checking if box 'ubuntu/trusty64' is up to date...
==> ubuntu: Setting the name of the VM: smack_ubuntu_1458685156894_75719
==> ubuntu: Clearing any previously set forwarded ports...
==> ubuntu: Clearing any previously set network interfaces...
==> ubuntu: Preparing network interfaces based on configuration...
    ubuntu: Adapter 1: nat
==> ubuntu: Forwarding ports...
    ubuntu: 22 (guest) => 2222 (host) (adapter 1)
==> ubuntu: Running 'pre-boot' VM customizations...
==> ubuntu: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "716ed598-36e1-4509-b967-336d57414c3f", "--type", "headless
"]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole


The only thing that has changed is that I have installed Hyper-V on machine and rebooted it.  I haven't attempted to apply any of the fixes mentioned by you.

**Comment by Guoanshisb** [comment]
@shazqadeer @zvonimir 

Monty and I fixed the first two issues in develop branch. But `-b` flag is needed for `git clone`. So you may want to have a new clone using `git clone -b develop https://github.com/smackers/smack.git` and type in `vagrant up` under SMACK root directory. We will try to figure out a better solution.

Unfortunately there may be a conflict between Hyper-V and other virtualization software over hardware virtualization. So vagrant should work if you disable Hyper-V. The following webpage has some instructions on how to disable Hyper-V, http://druss.co/2015/06/fix-vt-x-is-not-available-verr_vmx_no_vmx-in-virtualbox/.

Let us know if it helps.

**Comment by zvonimir** [comment]
Thanks guys!
So I tested the implemented fixes, and on my end everything works both on Windows and Linux. On Windows, I also updated both VirtualBox and vagrant to their most recent versions. In addition, I did `vagrant box update` to update my local copy of the vagrant Ubuntu box.
Shaz (@shazqadeer), are things now working on your end? You should maybe pull the develop branch from scratch.

**Comment by shazqadeer** [comment]
I just tried after disabling Hyper-V and using the -b develop branch.  It is working now.  Currently, it looks like the regressions are running.  Lots of PASSED ...

**Comment by zvonimir** [comment]
Fixed with commits a80a52c94bf and 719ed7639.
