### ISSUE TITLE
running SMACK

### ISSUE THREAD

**Issue by shazqadeer** [smackers/smack#157]
I now have SMACK running on the VM.   I am able to get smack to work as expected on simple.c.  Now, I would like to use SMACK on a large project containing multiple C files. What workflow should I use?  One option would be to keep the build process separate from SMACK.  I can already generated a .ll file from my build process.  Is there a way to feed the .ll file to SMACK?  Note that eventually I am going to have some model code (using inline Boogie feature perhaps) together with C source code.  I may also end up using either SMACK's memory safety instrumentation or the BPL-level instrumentation for memory safety that Shuvendu/Akash have implemented.

If any of the SMACKERs are willing to be pinged on Skype, please let me know.  Otherwise, I will continue to use the Issues forum for my questions.

Thanks for your help with the VM issues.

**Comment by michael-emmi** [comment]
There are quite a few routes actually.

1. If your project is a set of C files, you can pass them all to the `smack` command line. For instance, `smack -t my_project/*.c` should generate a Boogie translation of the entire thing.

2. You can keep the build process separate, modify it to generate LLVM bit code, and pass the generated bit code to the `smack` command line. For instance, `smack -t my_program.ll` should generate a Boogie translation.

3. If modifying the build is impractical, we also have experimental support for automation which hijacks the build process and generates LLVM bit codes for all compilation units.

I am available for the next couple of hours to discuss if you’d like.

**Comment by shazqadeer** [comment]
I am trying option #2 now.  I get the following error:

vagrant@vagrant-ubuntu-trusty-64:~/smack/qadeer/mpu6000$ smack -t mpu6000.ll
SMACK program verifier version 1.5.2
llvm-link: mpu6000.ll:141:122: error: expected value token
@_ZN7MPU6000C1EiPKcS1_9spi_dev_e8Rotationi = hidden alias %class.MPU6000* (%clas
s.MPU6000*, i32, i8*, i8*, i32, i32, i32), %class.MPU6000* (%class.MPU6000*, i32
, i8*, i8*, i32, i32, i32)* @_ZN7MPU6000C2EiPKcS1_9spi_dev_e8Rotationi

                                         ^
llvm-link: error loading file 'mpu6000.ll'

Error invoking command:
llvm-link -o /home/vagrant/smack/qadeer/mpu6000/a-kG4FqC.bc mpu6000.ll
llvm-link returned non-zero.

Any ideas?

**Comment by zvonimir** [comment]
Which version of clang are you using?

**Comment by shazqadeer** [comment]
Chris Lovett changed the clang version to 3.6.2 and now I get the following output which looks better:

vagrant@vagrant-ubuntu-trusty-64:~/smack/qadeer/mpu6000$ smack -t mpu6000.ll
SMACK program verifier version 1.5.2
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: ignoring inline asm passed as argument.
warning: ignoring inline asm passed as argument.
warning: ignoring inline asm passed as argument.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: ignoring inline asm passed as argument.
warning: ignoring inline asm passed as argument.
warning: ignoring inline asm passed as argument.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: ignoring inline asm passed as argument.
warning: ignoring inline asm passed as argument.
warning: ignoring inline asm passed as argument.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
SMACK generated a.bpl

**Comment by zvonimir** [comment]
@michael-emmi Do you think it would be worthwhile writing some of this up (i.e., various options for running SMACK on projects) on our wiki?

**Comment by michael-emmi** [comment]
Yes, I think the documentation should be improved across the board. Instructions for running SMACK is definitely a vital part to focus on.

I also think it will be a better idea to organize our documentation *in* the repository — as opposed to being wiki-based — so that it exists under version control and can differ between branches and commits.

This is possible via [relative links](https://help.github.com/articles/relative-links-in-readmes/) from `README.md`.

**Comment by zvonimir** [comment]
Ah, I did not know about relative links! Very neat. We should create an issue for this and move everything from wiki into `docs`.

**Comment by shaobo-he** [comment]
This issue seems to have been addressed. Closed.
