### ISSUE TITLE
Boogie declarations missing when source is LLVM bitcode

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#158]
When `smack` is invoked directly on LLVM bit codes, the SMACK library functions are not compiled and linked as they would be give C sources.

This was discovered by Shaz, who has modified his build to generate LLVM bit codes which he then passes to `smack`.

**Comment by zvonimir** [comment]
I believe we did this intentionally. By default, when `smack` is invoked directly on a bc file, we assumed that the user would make sure that SMACK library is linked with it. This makes sense to me since users will have their own build processes that should take care of this linking. In fact, we have a project here at Utah where they do this linking on their end. 
Now, the good thing is that I think if you link the same library twice, nothing bad is going to happen, right?

**Comment by michael-emmi** [comment]
I am wondering whether we should update our previous view that users should link the Smack libraries themselves in LLVM-input mode since:

1. this is asymmetric with how we do things for C-input mode, where we link the Smack libraries automatically,

2. our LLVM-input mode does linking anyways, since we allow multiple LLVM bit code inputs,

3. it is easier for users to forgo responsibility for linking Smack libraries: besides being one less thing to do manually, modifying their build process would be simpler,

4. in the presence of multiple Smack libraries (smack, pthread, spinlock, …) a user has to keep track of which libraries are needed, and

5. having Smack do the linking feels like a better abstraction: besides helping the user with the above concerns, it ensures better portability, e.g., if an update to Smack were to change the file names or locations of library files.

Thus I propose that the linking of Smack libraries is encapsulated in the `smack` command.

Besides a project or two that is so far doing manual linking of Smack libraries — the change to automatic linking should be simple to adopt — can you give any reasons why you think that users should take care of this linking?

The only possible snag I can imagine in Smack-managed library linking is in the case that linking could somehow fail if the users code were compiled differently than Smack libraries, e.g., with different compiler flags. However, I am not sure if this is possible or likely within our use cases. Any idea?

**Comment by zvonimir** [comment]
I just did some research, and it appears the linking the same library twice should have the same effect as linking it just once, i.e., the second linking is just ignored. So we should be fine even in this case.
Also, I agree with your arguments.

The last concern you raised is a valid one, and in fact it might come into play in Shaz's situation at some point, since their platform is I believe not x86. So the question is whether you can link together a bc file generated for x86 with a bc file generated for e.g. ARM. I vaguely remember that you cannot link bc files if their data layout fields do not match. I think we run into this issue at some point in the past.

To confirm this, I did a simple exercise to link a file compiled with `-m32` with a file compiled with `-m64`, and I get the following output from `llvm-link`:
```
WARNING: Linking two modules of different data layouts: '../../../test/basic/simple.bc' is 'e-m:e-p:32:32-f64:32:64-f80:32-n8:16:32-S128' whereas 'llvm-link' is 'e-m:e-i64:64-f80:128-n8:16:32:64-S128'

WARNING: Linking two modules of different target triples: ../../../test/basic/simple.bc' is 'i386-unknown-linux-gnu' whereas 'llvm-link' is 'x86_64-unknown-linux-gnu'
```
So this is just a warning, but certainly weird things could happen in this situation since it is not clear which data layout is used in the end.

**Comment by michael-emmi** [comment]
Nice investigation!

Three possible solutions to this problem — if we do go with automatic linking — seem to be:

1. Fix a “standard” data layout to use with Smack. Then we require users that are using their own build systems to set compile flags accordingly. This could be inconvenient, but then again, I am not convinced that all of Smack will work correctly with exotic data layouts anyways :-) Besides inconvenience, this might also put distance between analysis results and runtime behavior.

2. Allow the user to pass in compile flags. In fact this is already implemented with the `--clang-options` flag.

3. Have Smack determine the data layout or compile flags of any given LLVM bit codes, and replicate those flags or data layout when it compiles Smack libraries. Technically, I do not yet have answers for how this might be done.

Either way, there’s a hidden deeper question here: is Smack supposed to work correctly for all sorts of data layouts?

Still thinking…

**Comment by zvonimir** [comment]
Well, even for SVCOMP we are already using `-m32` and `-m64`, and that is working fine.

I do have to wonder whether e.g. big vs little endian would create any problems? Not sure.

I think that your suggestion 3 would not be trivial to implement from Python. You can find out what the data layout string is by doing `llvm-dis`. But I am not sure how you would map such a string back to compiler flags.

Suggestion 2 seems appealing, but I think it would create issues with cross-compilation. Meaning, if you generate a bc file on an ARM machine, and then attempt to verify it on x86. In that case, I would not even know exactly which flags to pass to clang on the x86 machine to get the same data layout as what we got on ARM. I guess one would have to use the `arch` flag and figure out the exact ARM machine architecture.

I am not particularly keen on suggestion 1.

Finally, I would like to add another one:
4. Add a flag to `smack` that turns off automatic linking.

**Comment by michael-emmi** [comment]
Further investigation suggests that the target data layout (string) is determined by the target triple, and as far as I can tell, the format of the target triple in LLVM bit code is identical to that which can be specified on the clang command line via the `-target` flag. So compiling our libraries to the same target as the user’s code might be very simple.

**Comment by zvonimir** [comment]
Ah, very good!
Is `llvm-dis` the only (or the best) way to get that triple from a bc file in Python?
I guess we can assume that `llvm-dis` is installed wherever `clang` is installed. Right?

**Comment by michael-emmi** [comment]
Right. As far as I know `llvm-dis` is the way to get the triple.

So integrating everything thus far we, the plan would be automatically detect the target triple (via `llvm-dis`) when LLVM codes are passed as input, and then add that to `clang_options` (via the `-target` flag) so that libraries are compiled with the same triple. I can create this patch shortly.

Now that we’re on the topic, it might be a good idea for us to expose target triples in the Smack interface as well, e.g., via a `--target` flag, according to the same format as Clang/LLVM. This would generally allow “cross verification” even from C sources.

Regarding your suggestion to disable automatic linking: are you suggesting to generate Boogie code without Smack libraries linked? or are you suggesting to generate LLVM code without Smack libraries linked? I’m not sure I see practical uses of either. For me, a clearer parallel with GCC/Clang is our `-t` / `--no-verify` flag.

M

**Comment by zvonimir** [comment]
Adding `--target` would potentially be useful, but one can already do that via `--clang-options`, right?
So `--target` would be a short cut for that part, and I am not sure if we need to add it explicitly.

By disabling automatic linking I meant that when a bc file is passed as input, when linking is disabled we do not attempt to link it automatically with `smack.c`. It would just allow users to disable that step if they want to, e.g., if they for some reason want to do linking with `smack.` within their build process.

**Comment by michael-emmi** [comment]
Is there practical use of what you are describing though? I don’t see why you would want to link *our* version of the Smack libraries within your own build process — for all of the reasons already mentioned.

The only practical use case I can think of is if they want to link in their own versions of Smack libraries. But this is a different angle entirely, for which I would think of possible flags as `--custom-verifier-libraries` or `--without-verifier-libraries`.

**Comment by zvonimir** [comment]
Sure. Given that linking twice is not a problem, I am ok with the proposed solution.
Currently we have to users who link their own SMACK library, and so I do not think we should be addressing that use case at this point.
Ok, I think that the proposed plan sounds good to me.

**Comment by michael-emmi** [comment]
Ok that should do it.

Still wondering whether `--target` should become a first-class Smack flag though. It seems to be more fundamental to the verification result of Smack than other compiler flags, since it dictates behavior of the *back end*, and perhaps something that should be more natively part of the Smack interface.

**Comment by zvonimir** [comment]
You are probably right about --target, and I would not mind having that as
an explicit flag.


On Wed, Mar 30, 2016 at 2:44 PM Michael Emmi <notifications@github.com>
wrote:

> Ok that should do it.
>
> Still wondering whether --target should become a first-class Smack flag
> though. It seems to be more fundamental to the verification result of Smack
> than other compiler flags, since it dictates behavior of the *back end*,
> and perhaps something that should be more natively part of the Smack
> interface.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/smackers/smack/issues/158#issuecomment-203628287>
>
-- 
http://zvonimir.info
http://soarlab.org

**Comment by zvonimir** [comment]
I just did a small experiment to check what happens when you link the same file twice. And you do get an error after all:
```
ERROR: Linking globals named '__VERIFIER_assume': symbol multiply defined!
```
So silently linking something under the hood might confuse users who perform this linking step on their own. We should I guess document this.

**Comment by my-code-cloud** [comment]
I I encountered the same error 
`Linking globals named '__VERIFIER_assume': symbol multiply defined!`
when smack is invoked directly on a .bc/.ll file translated by smack and found this related issue on the error.

I think the cause is just as you mentioned: 
**smack links links the same header file in the translation and compilation phases under the hood automaticly.**

However, I have not found a related wiki introduction nor a flag that turns off automatic linking. 
I support your proposal on this issue and hope that the relevant instructions on this error and a flag to disable automatic linking could be added soon. @zvonimir 
Thank you for your efforts and contribution.

> I just did a small experiment to check what happens when you link the same file twice. And you do get an error after all:
> 
> ```
> ERROR: Linking globals named '__VERIFIER_assume': symbol multiply defined!
> ```
> 
> So silently linking something under the hood might confuse users who perform this linking step on their own. We should I guess document this somewhere on our wiki.

**Comment by shaobo-he** [comment]
> I I encountered the same error
> `Linking globals named '__VERIFIER_assume': symbol multiply defined!`
> when smack is invoked directly on a .bc/.ll file translated by smack and found this related issue on the error.
> 
> I think the cause is just as you mentioned:
> **smack links the same header file in the translation and compilation phases under the hood automaticly.**
> 
> However, I have not found a related wiki introduction nor a flag that turns off automatic linking.
> I support your proposal on this issue and hope that the relevant instructions on this error and a flag to disable automatic linking could be added soon. @zvonimir
> Thank you for your efforts and contribution.
> 
> > I just did a small experiment to check what happens when you link the same file twice. And you do get an error after all:
> > ```
> > ERROR: Linking globals named '__VERIFIER_assume': symbol multiply defined!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So silently linking something under the hood might confuse users who perform this linking step on their own. We should I guess document this somewhere on our wiki.

Thank you for your reply. I think #718 could be a solution or something that can be addressed together.
