### ISSUE TITLE
Add attributes to Boogie identifier expression

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#163]
Sometimes source language semantic should be passed along to Boogie. For example, Corral requires function parameter with the type of pointer to a pointer be annotated because it can impose angelic side-effects to the heap when angelic verification is invoked. Please see the example below,

`procedure foo({:ref M} x : int, {:scalar} y : int);`

Attribute `{:ref M}`  means `x` corresponds to a pointer to pointer in C source code. `{:scalar}` means `y` is of a scalar type.

**Comment by michael-emmi** [comment]
Please demonstrate a specific example.

**Comment by michael-emmi** [comment]
Can you point to a list of accepted annotations and semantics?

**Comment by michael-emmi** [comment]
p.s. unless correcting typos, please post new comments rather than editing prior comments; otherwise, notifications of new comments are not sent, and the thread of conversation becomes incoherent.

**Comment by zvonimir** [comment]
@shaobo-he : Is this still an issue?

**Comment by shaobo-he** [comment]
> @shaobo-he : Is this still an issue?

No, it is not.
