### ISSUE TITLE
Model LLVM arithmetic with overflow intrinsics

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#165]
Rust compiler will compile arithmetic operations into LLVM arithmetic with overflow intrinsics. Take the following rust program as an example,

``` rust
fn main() {
    let mut v = 2 ;
    v = v * v;
    assert!(v == 4);
}
```

The corresponding bytecode is,

``` llvm
%0 = load i32* %v, align 4, !dbg !817
%1 = load i32* %v, align 4, !dbg !817
%2 = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 %0, i32 %1), !dbg !817
%3 = extractvalue { i32, i1 } %2, 0, !dbg !817
%4 = extractvalue { i32, i1 } %2, 1, !dbg !817
```

Rustc also uses similar [intrinsics](http://llvm.org/docs/LangRef.html#arithmetic-with-overflow-intrinsics) for other arithmetic operations.

We have identified an issue #162 that these intrinsics are dropped due to transformation pass used by SMACK. In this issue, we would like to implement proper translation of these intrinsics. 

One solution is to add a pass to change calls to these intrinsics to other functions with bodies that implement corresponding arithmetics. We can hand code the functions in a file and link it to the original bc file.

**Comment by michael-emmi** [comment]
Please give reasonable context and description of this issue.

**Comment by Guoanshisb** [comment]
@michael-emmi Please see the updated title and description.

**Comment by zvonimir** [comment]
@shaobo-he and @keram88 : Has this issue been resolved?
I think we now do have proper translation for these intrinsics. Right?

**Comment by keram88** [comment]
These intrinsics are now handled properly by the IntegerOverflow pass.

**Comment by zvonimir** [comment]
Ok, I thought so. Closing this then.
