### ISSUE TITLE
Virtual SMACK

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#166]
It should be easier to just run SMACK, e.g., without having to provision a (virtual) machine.

One idea is to use packer (https://www.packer.io) to create provisioned (i.e., having SMACK installed) vagrant boxes, e.g., built automatically on Soarlab’s servers in response to each commit.

Then we could provide a script named `vsmack` or `virtual-smack` or `smack-virtual` etc., which would:
1. check vagrant status
2. fetch and bring up a pre-provisioned vagrant box if absent
3. forward the command parameters to `smack` through vagrant ssh — assuming the working directory is mapped
4. bring down the box, or keep alive, per user request

So a user would only need to download that script, and of course have Vagrant and some provider — VirtualBox, for the moment — installed. The user provides the same inputs they would have provided to `smack`, and sees the same outputs that `smack` would have returned. Besides the overhead of launching the VM, the user should notice no difference between `smack` and `vsmack`.

**Comment by zvonimir** [comment]
One thing I realized is that having to download large files is not ideal. For example, if someone attempts to install SMACK at a conference, most likely they will not be able to do that since wifi typically is not good enough.
I wonder if we could create a really stripped down VM (by removing everything we do not need) that is not that large?

**Comment by michael-emmi** [comment]
I guess your comment is orthogonal to this issue, since the current workflow which first downloads a Vagrant base box and then provisions it — which includes additional downloads and compilation — is strictly worse, in principle.

However, you’re right that in both situations (pre-provisioned and un-provisioned) we should be able to use a more stripped down Vagrant base box, thus lowering the download time.

**Comment by zvonimir** [comment]
My comment was meant to be an addition to this issue. If we will provide our own box, we might as well make an effort to make it as small as possible.

**Comment by zvonimir** [comment]
We started looking into this. One question I have is how this would mesh with our development environment, i.e., where SMACK sources would reside and be built. Currently we have this very nice Vagrant-based setup (in my opinion) where it is easy to update and rebuild SMACK within the provisioned VM, while sources reside on the host machine. How would the proposed development flow look like if we do what you suggested?

**Comment by michael-emmi** [comment]
From what we have now, the easiest path seems to be simply to run `vagrant package` after having brought up our current development environment with `vagrant up`.

https://www.vagrantup.com/docs/cli/package.html

This will generate a `package.box` which can be uploaded to Atlas. I guess this can be done automatically, but for the moment I have manually uploaded such a box.

https://atlas.hashicorp.com/smackers/boxes/smack

The Virtual Smack prototype in `bin/vsmack` brings up that box. We should probably add a link to download `vsmack` from `README.md`. And we should also probably manage those boxes on Atlas in some coherent way, as discussed, and add a flag to `vsmack` to select an appropriate develop/release box.

We probably also want to try to minimize the size of these boxes #167, e.g., by removing unnecessary packages, clearing the apt cache, zeroing out unused disk, etc — I have seen several tricks posted on the internets.

**Comment by zvonimir** [comment]
I tried this out on Windows.
The first problem were backslashes in `synced_folder`, which had to be escaped (see 97b3d81).
The second problem are paths that are being passed to the SMACK script in the VM: there is a discrepancy between how those are written on the host Windows machine (using backslashes) and how they have to be specified within our Linux VM (using slashes). I do not have time to fix this at this point, but it would be good to either eventually address this issue or document it.
