### ISSUE TITLE
Reduce download impact of VM-based SMACK

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#167]
As mentioned in #166 we should reduce the size of Vagrant box downloads.

I am not sure what the lower limits are, but here is a 271MB version of 64-bit Ubuntu Trusty64.

https://atlas.hashicorp.com/minimal/boxes/trusty64

Maybe a good place to start since we support Ubuntu.

**Comment by zvonimir** [comment]
It would be good to create a Docker image too. I have to say that Docker seems to be more popular than Vagrant. I can look into this.

**Comment by michael-emmi** [comment]
Vagrant boxes are just wrappers of images for different “providers” including VirtualBox, VMWare, Docker, AWS, … So it’s not really Docker vs. Vagrant so much as it is Docker vs. VirtualBox. We could create stand-alone VirtualBox images and Docker containers, but wrapping them as Vagrant boxes makes it more convenient to run them, i.e., via `vagrant up`.

I have nothing against using a different provider (e.g., VirtualBox vs. Docker) especially if there are benefits, e.g., image size. But consider that using Docker as a provider is only useful for Linux host machines, since other hosts (e.g., OS X, Windows) will have to run a VM (e.g., VirtualBox, VMWare) anyways to run Docker containers. Docker containers are probably more efficient on Linux hosts — container size? speed? — since they do not add a VM layer. But on all others, where a VM layer is needed anyways, it might be better to stick with a VM image.

At any rate, a good solution could be to provide both Vagrant boxes for Docker and VirtualBox providers. This seems no harder to automate, e.g., with Packer (https://www.packer.io), and should come down to specifying two targets in the Packer template instead of one. Furthermore we should be able to share provisioning across both providers.

**Comment by michael-emmi** [comment]
Update: from a download-size point of view, Docker might be a better alternative on Windows and OS X as well; according to the following, the “default” VM for running Docker containers on OS X is only 24MB large: https://docs.docker.com/engine/installation/mac/

So I wonder how big a Docker container provisioned with SMACK would be. Unclear whether there will be significant savings versus a minimal Ubuntu VirtualBox but it does seem worth the experiment!

**Comment by shaobo-he** [comment]
Closed this issue as it's not relevant now. @michael-emmi @zvonimir feel free to reopen it if it becomes relevant.
