### ISSUE TITLE
Program defined stdlib functions

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#169]
Definition of `malloc` and `calloc` shows up in the bytecode of [tcsh](ftp://ftp.astron.com/pub/tcsh/) compiled by [wllvm](https://github.com/travitch/whole-program-llvm). For `malloc` SMACK will inject call to `$alloc` and then translates its body. For `calloc` there will be a link error since it is redefined in `smack.c`.

**Comment by zvonimir** [comment]
These functions are a part of the C standard and C's standard library. It would be good to understand why their definitions appear in the bytecode in the first place. I have never encountered this problem before. Is is because of wllvm?

**Comment by Guoanshisb** [comment]
Based on my observation, there are macros that choose which **malloc** function (from standard libary or user defined) to use. For example, in `tcsh`, we have the following code to control which **malloc** to use

```C
# if defined(SYSMALLOC) || defined(__linux__) || defined(__GNU__) || defined(__GLIBC__) || defined(sgi) || defined(_OSD_POSIX)
#  define NO_FIX_MALLOC
#  include <stdlib.h>
# else /* glibc */
#  define _GNU_STDLIB_H
#  define malloc __malloc
#  define free __free
#  define calloc __calloc
#  define realloc __realloc
#  include <stdlib.h>
#  undef malloc
#  undef free
#  undef calloc
#  undef realloc
# endif /* glibc || sgi */
```
And in another file, **malloc** is defined.

**Comment by zvonimir** [comment]
It is unclear what we would do about this issue in the first place since the application in question seems to redefine functions from the standard.

**Comment by michael-emmi** [comment]
I’m not sure I understand your objection @zvonimir. I would expect that alternate definitions of standard-library functions which conform to any relevant standards should be allowed. Smack itself does this, e.g., with the implementations of memory and string functions. Why would this be grounds for rejecting alternate definitions?

A distinct concern could be definitions of things that Smack needs to define (whether or not these functions are part of the C standard). Here there could be a legitimate concern alternate definitions of memory allocation functions, for instance, in that it can interfere with Smack’s own requirements.

**Comment by zvonimir** [comment]
Yes, I should clarify my objection better. We are not even remotely close to being able to handle something like custom memory allocators. And there are other functions that would fall in this category, most likely things such as `exit`, `memcpy`, `memset`, etc. So I think that investing time into trying to resolve this issue probably does not make a lot of sense at this point.
