### ISSUE TITLE
Weird behavior of --loop-limit with nested loops

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#171]
Here is a simple example illustrating this problem:

```
int main(void) {
  int i, j;
  for (i = 0; i < 2; i++) {
    for (j = 0; j < 2; j++);
  }
  assert(0 != 0);
  return 0;
}
```

One would expect that SMACK would report an assertion violation with `--loop-limit=3`, and yet that does not happen. When the inner loop is commented out, then a violation is reported with `--loop-limit=3`. I also tried `--loop-limit=10` just to test it, but that does not help either.
It would be good to understand what exactly is happening here.

**Comment by Guoanshisb** [comment]
Can we dump LLVM bytecode after certain optimization pass? Having this feature would facilitate debugging a lot.

**Comment by zvonimir** [comment]
How is dumping LLVM bytecode relevant to this issue?
In general, yes, maybe we should do that, but please create a separate issue for that.

**Comment by shaobo-he** [comment]
As of commit id 4894245, this example still doesn't work for Boogie but does for Corral.

**Comment by zvonimir** [comment]
Wait, setting `loop-limit` seems to be a noop for Boogie. Right?
Boogie doesn't use that command line argument since that functionality is not supported.

SMACK should probably throw an error when `--loop-limit` is used with Boogie (or anything else other than Corral I guess).

**Comment by shaobo-he** [comment]
> Wait, setting `loop-limit` seems to be a noop for Boogie. Right?
> Boogie doesn't use that command line argument since that functionality is not supported.
> 
> SMACK should probably throw an error when `--loop-limit` is used with Boogie (or anything else other than Corral I guess).

Sorry for the confusion, I actually used the `--unroll` flag.

**Comment by zvonimir** [comment]
Is there unroll number that actually works?
This might also be a SMACK bug somehow.

**Comment by shaobo-he** [comment]
> Is there unroll number that actually works?
> This might also be a SMACK bug somehow.

Let me test. Corral works with unroll bound 3.

**Comment by zvonimir** [comment]
I searched my email. Here is an old one from Shuvendu:
```
All I can say by looking at the output and the brief look at the loopunroll code is that Boogie does not have any notion of nested loops (since it deals with unstructured control flow). It only knows about Strongly Connected Components (SCCs), and in this case all the labels form a single SCC. Look at the attached example, where there are two loops but none of them are nested.

Given /loopUnroll:k, it ensures that the loop body is  executed at most k times. Hence if you have a nested loop and the outer loop needs to execute n1 times and the inner loop n2 times, then you need /loopUnroll:n1*n2 (+1) maybe.
```
Basically, this is not a bug, but expected behavior. You could of course try to implement a different loop unrolling in Boogie, that would match what Corral does and that would be more intuitive. But I think until then we are stuck with what Boogie already implements.

**Comment by shaobo-he** [comment]
> I searched my email. Here is an old one from Shuvendu:
> 
> ```
> All I can say by looking at the output and the brief look at the loopunroll code is that Boogie does not have any notion of nested loops (since it deals with unstructured control flow). It only knows about Strongly Connected Components (SCCs), and in this case all the labels form a single SCC. Look at the attached example, where there are two loops but none of them are nested.
> 
> Given /loopUnroll:k, it ensures that the loop body is  executed at most k times. Hence if you have a nested loop and the outer loop needs to execute n1 times and the inner loop n2 times, then you need /loopUnroll:n1*n2 (+1) maybe.
> ```
> 
> Basically, this is not a bug, but expected behavior. You could of course try to implement a different loop unrolling in Boogie, that would match what Corral does and that would be more intuitive. But I think until then we are stuck with what Boogie already implements.

Thank you for the reply. This is very helpful. Can we close this issue now?

**Comment by zvonimir** [comment]
Closing.
