### ISSUE TITLE
Too much memory allocated to Vagrant box

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#175]
Commit a9060db allocates 6 GB of memory to Vagrant boxes. This brings my 4 GB laptop to a screeching halt (swapping) at some point during building Smack when the box reaches about 2 GB, forcing a hard reboot!

While some uses (even regressions) require more memory, many machines just do not have 6 GB to spare. It probably better to leave memory allocation unspecified in Smack’s `Vagrantfile`, resorting to defaults which can be declared separately per user/machine, e.g,. in `~/.vagrant.d/Vagrantfile`. Then Vagrant’s default value (512 MB I believe) would be used unless you had specified another amount in `~/.vagrant.d/Vagrantfile`.

https://www.vagrantup.com/docs/vagrantfile/

And you can always change the memory allocation on a stopped machine with `VBoxManage`.

https://www.virtualbox.org/manual/ch08.html

**Comment by zvonimir** [comment]
I will look into this. It does not make sense for our regressions to fail by default. So if we are lowering memory for our Vagrant box, we should either disable some of the larger regressions, or maybe switch to using Corral by default since it often uses less memory.

**Comment by michael-emmi** [comment]
Actually all regressions invoked by `vagrant up` are passing with the default 512 MB setting. Previously I assumed they weren’t since that would have been good justification for commit a9060db in the first place.

**Comment by zvonimir** [comment]
Have you tried `--exhaustive`? Or maybe things just changed since then when it comes to Boogie.
