### ISSUE TITLE
Soliciting comments on a piece of code from TypeSafety

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#178]
See here:
https://github.com/smackers/smack/blob/develop/lib/DSA/TypeSafety.cpp#L421

In particular, this chunk of code:
```
          if(TypeInferenceOptimize) {
            if(const ArrayType *AT = dyn_cast<ArrayType>(*ni)) {
              Type *ElemTy = AT->getElementType();
              while(ArrayType *AT1 = dyn_cast<ArrayType>(ElemTy))
                ElemTy = AT1->getElementType();
              if(next_offset < (TD->getTypeStoreSize(ElemTy) + offset)) {
                assert(isa<StructType>(ElemTy) && "Array Not of Struct Type??");
                overlaps = false;
              }
            }
          }
```

It blows my mind that:
1. This assertion is supposed to hold!?!? Basically, why recursively drilling down through an array type would result in a structure type? Could we not have an array of e.g. ints here?
2. It makes sense to set `overlaps` to false here!?!? I have no idea what is the reasoning behind resetting `overlaps` here.

I have been looking at this for several hours now since I have a huge example that is hard to debug that breaks this assertion. It would be really helpful if someone could help me out with the above two questions.

**Comment by jtcriswell** [comment]
This optimization was added to DSA after the PLDI 2007 paper.  I believe it was added by a Master's student for her thesis project, and it isn't enabled by default (so SAFECode doesn't use it).  I wasn't even aware that this code existed within DSA.

I agree that the logic is baffling.  Given a potential overlap between two fields, it checks to see if the current field is an array and then strips away all the elements contained in the array to see if the base element (assumed to be a structure) might overlap with the next field.  This only makes sense to me if the TargetData::getTypeStoreSize() method returned different results for an array of a struct type with no elements and a struct type with no elements.

I suspect this code is a hack (based on my knowledge of the Master's thesis project and the odd assumption that the type within the array is always a struct type).  I think you should disable it.

I'd love to see the bit code and corresponding C source code that is triggering this assertion.
