### ISSUE TITLE
Updating our running example

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#180]
I find our running example (`examples/simple/simple.c`) to be quite unsatisfactory. For example, it contains a potential integer overflow that occasionally confuses people. There are also no conditionals for SMACK to explore. I propose that we switch to a slightly more involved example that could also be used to illustrate some key features of SMACK, such as bit-vector precision, dynamic memory allocation, structures, etc.
This is the example I propose and I would appreciate your feedback:
```
#include <stdlib.h>
#include "smack.h"

#define TRUE 1
#define FALSE 0
#define MAX_LIMIT 1000

// Bank Account Example

// Account structure
typedef struct {
  int balance;
  int limit;
} ACCOUNT, *PACCOUNT;

// Create and initialize account
PACCOUNT create(int limit) {
  if (limit <= 0 || limit > MAX_LIMIT) return 0;
  PACCOUNT acc = (PACCOUNT) malloc(sizeof(ACCOUNT));
  acc->balance = 0;
  acc->limit = limit;
  return acc;
}

// Get account balance
int get_balance(PACCOUNT acc) {
  return acc->balance;
}

// Deposit funds if not exceeding the account limit
int deposit(PACCOUNT acc, int n) {
  if (n <= 0) return FALSE;
  int tmp = n - acc->limit;
  if (acc->balance + tmp > 0) {
    return FALSE;
  }
  acc->balance = acc->balance + n;
  return TRUE;
}

// Withdraw if there is enough funds in the account
int withdraw(PACCOUNT acc, int n) {
  if (n <= 0) return FALSE;
  if (acc->balance >= n) {
    acc->balance = acc->balance - n;
    return TRUE;
  }
  return FALSE;
}

// Simple unit test for account
void test_account(int x, int y, int z) {
  PACCOUNT acc;
  int ops = 0;

  acc = create(x);
  if (!acc) {
    assert(x <= 0 || x > MAX_LIMIT);
    return;
  }
  ops += deposit(acc, y);
  assert(get_balance(acc) >=0 && get_balance(acc) <= MAX_LIMIT);
  ops += deposit(acc, z);
  assert(get_balance(acc) >=0 && get_balance(acc) <= MAX_LIMIT);
  ops += withdraw(acc, z);
  assert(get_balance(acc) >=0 && get_balance(acc) <= MAX_LIMIT);
  assert(ops < 3 || get_balance(acc) == y);
  return;
}

int main(void) {
  int x = __VERIFIER_nondet_int();
  int y = __VERIFIER_nondet_int();
  int z = __VERIFIER_nondet_int();

  // Check account with nondeterministic values
  test_account(x, y, z);
  return 0;
}
```

**Comment by MontyCarter** [comment]
I think that deposit would be more clear if it was changed from this

// Deposit funds if not exceeding the account limit
int deposit(PACCOUNT acc, int n) {
  if (n <= 0) return FALSE;
  int tmp = n - acc->limit;
  if (acc->balance + tmp > 0) {
    return FALSE;
  }
  acc->balance = acc->balance + n;
  return TRUE;
}


to this (remove tmp variable, and directly compare the new proposed sum to
the limit)

// Deposit funds if not exceeding the account limit
int deposit(PACCOUNT acc, int n) {
  if (n <= 0) return FALSE;
  if (acc->balance + n > acc->limit) {
    return FALSE;
  }
  acc->balance = acc->balance + n;
  return TRUE;
}


I found it difficult to assign a meaning to the tmp variable that
corresponds with a common concept (tmp is the amount by which n is greater
than the account limit?).

Another thing you might consider, in the interest of best practices, is to
have a function that frees the allocated ACCOUNT before the program
terminates.

Btw, where does this exercise bit-vector precision?  I must have glanced
over this.

-M

**Comment by zvonimir** [comment]
Heh, I had to think a bit about deposit :). 
Of course, my first version was the same as yours and used `acc->balance + n > acc->limit`. But this can cause integer overflow, which creates incorrect results. Using bit-vector precision catches that bug. Does this make sense?
Yes, freeing it is a good idea.

**Comment by MontyCarter** [comment]
Yes, makes sense.  Good catch.

Perhaps `if(acc->limit - acc->balance < n) {` is more intuitive?  (That is,
the extra capacity left in the account should be greater than the amount
trying to be added.)

I guess it doesn't matter so much.  If someone is taking the time to go
through the example at this level of detail, they'll take the time to
figure out what `int tmp = n - acc->limit;` represents.
