### ISSUE TITLE
Getelementptr instruction with negative index operand

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#181]
Hey guys,

It seems that we assume the index argument to GEP instruction is always positive(https://github.com/smackers/smack/blob/develop/lib/smack/SmackRep.cpp#L607). I observed that negative index operands showed up in several programs. SMACK will generate a large integer as the index to pointer arithmetic.

Shaobo

**Comment by zvonimir** [comment]
Could you create a small regression? It is hard to debug without that.

**Comment by Guoanshisb** [comment]
@zvonimir would you like a bc file or C file? I have a bc file that leads to this issue. But I found it non-trivial to create a C file.

**Comment by Guoanshisb** [comment]
@zvonimir I got one :-)
```C
#include <stdlib.h>
#include "smack.h"

void
foo (void *p)
{
  if (p != NULL)
    {
      if (((int *) p)[-1] == 42)
        {
          assert(0);
        }
    }
}

int main()
{
  int a[3] = {0};
  foo((void*)&a[1]);
}
```
SMACK will report a bug while there should not be one.
