### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by rahulku** [smackers/smack#184]
Hi folks, I have been trying to get SMACK to build on Windows. I ran into some link issues and was wondering if anyone had any thoughts. My steps are as follows:
1. Download LLVM/CLANG 3.5 as suggested on instructions
2. Build LLVM/CLANG successfully (using CMake)
3. Ensure that SMACK CMake files and build scripts point to correct LLVM source and build tree
4. Compile SMACK (using CMake)

I see link errors, that are somewhat weird. I am attaching the image below:

![image](https://cloud.githubusercontent.com/assets/8743193/18184415/dc55ce36-704d-11e6-98b0-2cf53d292f9f.png)

**Comment by rahulku** [comment]
Quick update. seems like the Cmake files are out of date? they seem to be missing some lib entries for LLVM. Adding a couple of those have made the errors go down...

**Comment by rahulku** [comment]
Adding all the libraries into the cmakelists.txt file resolves the issue. This is not the "Correct" fix since it is just adding all libraries blindly. It would be good to update the CMakeLists.txt file to have only the libs that are actually needed.

**Comment by zvonimir** [comment]
Are you doing this from the develop branch or master? I think you are using master, and we are overdue for a new release. So I suggest you switch to develop, which also uses LLVM 3.6. Some of the issues you encountered are maybe fixed there.

**Comment by rahulku** [comment]
I am doing this in master with LLVM/CLANG 3.5 as the documentation suggests. 

If I switch to develop branch, should I also change to LLVM3.6 or will LLVM3.5 work?

Note, I have it building now but cannot get smack.py to run correctly.

**Comment by zvonimir** [comment]
Yes, you would have to switch to LLVM 3.6. I am scrambling to make a release, but it will likely take another several days. Sorry about that.

**Comment by rahulku** [comment]
No worries. 
I have the latest LLVM - I am assuming that will not work. I specifically need 3.6 - right?

**Comment by zvonimir** [comment]
Yes, you need 3.6.

**Comment by rahulku** [comment]
Same problems in develop branch. I had to add the libraries manually. Also, after building successfully, I cannot run smack. I get the following errors:

Traceback (most recent call last):
  File "./bin/smack", line 12, in <module>
    import smack.top
  File "./bin\../share\smack\top.py", line 212
    print "Running %s" % " ".join(cmd)
                     ^
SyntaxError: invalid syntax

**Comment by rahulku** [comment]
turns out that print now requires parenthesis around the argument. once past that, I run into 

Traceback (most recent call last):
  File "./smack", line 12, in <module>
    import smack.top
  File ".\../share\smack\top.py", line 14, in <module>
    from svcomp.utils import svcomp_frontend
ImportError: No module named 'svcomp'

**Comment by zvonimir** [comment]
This is an old issue and since then SMACK advanced a lot. Hence, it would be hard to reproduce and fix it.
