### ISSUE TITLE
"x&1" not considered equivalent to "x%2", assuming one causes the other to fail

### ISSUE THREAD

**Issue by KPJoshi** [smackers/smack#214]
Consider the following code:

```
#include "smack.h"
int main() {
  unsigned long x = __VERIFIER_nondet_ulong();
	
  assume((x&1ul)==1ul);
  assert((x%2ul)==1ul);
	
  //assume((x%2ul)==1ul);
  //assert((x&1ul)==1ul);
	
  //assume((x&1ul)==0ul);
  //assert((x%2ul)==0ul);
	
  //assume((x%2ul)==0ul);
  //assert((x&1ul)==0ul);
	
  return 0;
}
```

When smack 1.7.2 is run on any of the 4 assume-assert pairs, it claims the assertation can fail.
The values of x for which the assertation is reported to fail seem to indicate that the `&` version works incorrectly while the `%` version works as expected.

**Comment by michael-emmi** [comment]
Hi @KPJoshi!
By default Smack has bit-precision turned off, and thus interprets bitwise operations like `&` imprecisely. You can enable bit-precision, and verify all the assertions in your example, simply by passing invoking smack with the `--bit-precise` flag like so:
````bash
smack --bit-precise a.c
````
Of course, enabling bit-precision demands more from the underlying solver, so larger examples will take longer to verify with it enabled.

**Comment by KPJoshi** [comment]
I see
Let me check this, if it works then I will close this issue.
