### ISSUE TITLE
Smack fails to find error in simple sum of digits program

### ISSUE THREAD

**Issue by KPJoshi** [smackers/smack#220]
I have a function from the PARI library that counts the sum of digits in an unsigned long. It uses a lookup table for the first 1000 numbers and calculates the sum using this table and dividing by 1000 each time.

I compared this against a simple function written by me that does the same:

```
ulong mydigitsum(ulong n)
{
	ulong sum=0;
	while(n)
	{
		sum += n%10;
		n/=10;
	}
	return sum;
}
```

Upon changing a value in the lookup table to a wrong value, SMACK failed to find that there was an error.

Here is a link to the source:
[digitsum-test.zip](https://github.com/smackers/smack/files/915739/digitsum-test.zip)

Try changing the last value in the array to 26. This should cause incorrect results for 999.

SMACK simply says that it found no errors. I am using the latest release of SMACK.

**Comment by zvonimir** [comment]
By default, SMACK works by unrolling loops a bounded number of times. Also, by default, it unrolls each loop only once. That is clearly not enough to catch the bug you mentioned. Have you already tried passing `--unroll=1000` to SMACK?
Such a large number of loop unrolls might cause SMACK to not terminate. In that case, you can either scale down the number of unrolls (and potentially miss bugs), or you can try to write loop invariants and then use the `--modular` command line switch.

**Comment by KPJoshi** [comment]
I might be getting unroll bound wrong here:

The number 999 is part of the search space. For that number, the loop is run only once. If the last value in the array is changed to a wrong value, it should be able to detect the problem, right?
Also, for the largest number supported by unsigned long is 19 digits. So shouldn't the unroll bound have to be a maximum of 19?

Am I misinterpreting the meaning of unroll bound?

**Comment by zvonimir** [comment]
I looked at the code more carefully now. You are right, you do not need to unroll 1000 times, something like 20 should be enough, as you said. I also performed a quick experiment where I changed the second element of the array from `1` into `5`. Then I run SMACK as `smack digitsum-test.c --unroll 2` and it reported a bug as expected. I am running it now with large unroll bounds (10, 20), but this might take a while.

**Comment by KPJoshi** [comment]
OK, but shouldn't `--unroll 1` be enough? 1 is part of the search space, for which the loop should only run once, and if you have changed the element then it should cause an error.

**Comment by KPJoshi** [comment]
Aah ok since my code (the code that I am checking against) does 3x as many iterations I will need at least unroll bound 3.
OK, this explains the results.

It is working correctly then. I am closing this issue.

**Comment by Guoanshisb** [comment]
Hi @KPJoshi,

`--urnoll 1` is not enough. With this flag, the C program SMACK actually verifies looks like the following,

```C
#include "smack.h"
//#include <stdio.h>

typedef unsigned long ulong;

static const ulong digsum[1000] ={...};
ulong
sumdigitsu(ulong n)
{
  ulong s = 0;
  if (n) {
      s += digsum[n % 1000];
      n /= 1000;
      for(;;) {}     
  }
  return s;
}

ulong mydigitsum(ulong n)
{
	ulong sum=0;
	if (n)
	{
		sum += n%10;
		n/=10;
               for(;;) {}
	}
	return sum;
}

int main()
{
	ulong n = __VERIFIER_nondet_ulong();
	
	assert(sumdigitsu(n) == mydigitsum(n));
	
	//printf("pari:%lu me:%lu\n",sumdigitsu(999),mydigitsum(999));
	
	return 0;
}
```

So the output of the two functions can only be 0 if they terminates. You can add assertion `assert(sumdigitsu(n) == 0)` to verify it. So in order to break out the while loops, you need unrolling depth 2 at least.
