### ISSUE TITLE
Adding support for storing and loading of structures

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#221]
SMACK currently fails an assertion when the input bc file contains store/load instructions that are storing/loading structures. This is the assertion that fails: https://github.com/smackers/smack/blob/develop/lib/smack/SmackInstGenerator.cpp#L356
Rust will generate code that contains such instructions, as the attached file on which SMACK fails illustrates: [fibtest-ptr.zip](https://github.com/smackers/smack/files/923709/fibtest-ptr.zip)

To fix this issue, we should write a pass that replaces storing/loading of structures with a sequence of stores/loads of individual elements. I think we need a separate pass so that DSA analyzes the newly introduced store and load instructions. It seems that we might be able to reuse these functions as helpers: http://llvm.org/docs/doxygen/html/InstCombineLoadStoreAlloca_8cpp_source.html#l00922

**Comment by Guoanshisb** [comment]
It seems that there are only loads to structures in this file, which are introduced by some hand-written LLVM IR functions (`smack.llvm.smul.with.overflow.*`). The pass Struct2Ret should be able to convert them into load/store of integers.

**Comment by zvonimir** [comment]
Wait, on my machine llvm2bpl fails on a store of a structure that happens in this function `_ZN18fibtest_ptr_vRq0AB3fib17h0c60fd93a7d4c806E`. Are you getting a different assertion failure?

**Comment by Guoanshisb** [comment]
Sorry I overlooked it. The error message didn't say which assertion failed.

**Comment by zvonimir** [comment]
@shaobo-he : I think you fixed this. Right? Could you add a comment here which commit fixed it. Thanks!

**Comment by shaobo-he** [comment]
This, PR #251 fixes it and gets merged with commit e8142c28245f3c8d06de8d8c1dc6644feecaba73.

**Comment by zvonimir** [comment]
Ok, closing this then.
