### ISSUE TITLE
Pointer to bit-vector conversion (and vice versa) is broken

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#230]
Our new memory model does not place a upper bound on the return value of memory allocation procedures whereas pointer variables may be cast to `bv32` first before loaded/stored to a map in bit-vector mode. For example, the following is the definition of function `$store.bytes.ref`:

```
function {:inline} $store.bytes.ref(M: [ref] bv8, p: ref, v: ref)returns ([ref] bv8) { $store.bytes.bv64(M,p,$p2i.ref.bv64(v)) }
function {:inline} $p2i.ref.bv64(p: ref) returns (bv64) { $zext.bv32.bv64($int2bv.32(p)) }
```

I'm not sure what would happen if `v` is a large value that cannot be represented by 32 bit. Corral seems to assume that the return value could be anything. Consider this small Boogie program,

```Boogie
function {:builtin "(_ int2bv 32)"} $int2bv.32(i: int) returns (bv32);

procedure {:entrypoint} main()
{
  var x : int;
  x := 33672543600640;
  assert $int2bv.32(x) != 0bv32;
}
```

Corral reports a bug even with the flag `/bopt:z3opt:smt.bv.enable_int2bv=true`.

**Comment by zvonimir** [comment]
Interesting observation. What is the semantics of `int2bv` (when the passed integer is larger than what can be represented by the bitvector) according to the SMTlib standard?
Furthermore, this can only cause for us to report false bugs. Is that right?

**Comment by Guoanshisb** [comment]
`int2` seems to be a z3-specific function. See this: https://github.com/Z3Prover/z3/issues/555

If it's uninterpreted, we should only witness false bugs.

**Comment by Guoanshisb** [comment]
A follow-up on this issue: we may have another problem which is `x < ==> bv2int(int2bv(x)) != x`. It is because `bv2int(x)` may cast `x` to an unsigned value. Consider the following Boogie program, 

```boogie

**Comment by shaobo-he** [comment]
Added an example to reproduce the issue,

```C
#include "smack.h"
#include <stdlib.h>
#include <string.h>

int main() {
  int** x = (int**)malloc(sizeof(int*));
  int* y = (int*)malloc(sizeof(int));
  if ((int*)x != y)
    *x = y;
  else
    memset(x, 0, sizeof(int*));
  assert(*x == y);
  return 0;
}
```
