### ISSUE TITLE
signbit failing with 0.0 and -0.0

### ISSUE THREAD

**Issue by Checkmate50** [smackers/smack#244]
The following code does not verify but should.  This appears to be an issue relating to `signbit(0.0)` not working properly with functions.

```
#include "smack.h"
#include <math.h>

int main(void)
{
  assert(!signbit(remainder(0.0, 1.0)));
}
```

**Comment by zvonimir** [comment]
@liammachado : is this working now?

**Comment by liammachado** [comment]
Yes, this now works.
