### ISSUE TITLE
Generating CounterExample for Array

### ISSUE THREAD

**Issue by guolong-zheng** [smackers/smack#246]
I am using SMACK to verify some loop invariants contains array. If I directly run SMACK, I can only get the trace for the loop counters if the invariant is not correct. How can configure SMACK so that it provides the counterexample for the array?

**Comment by michael-emmi** [comment]
Hi @gzhengTaken thank you for bringing this up. This is a current limitation stemming from the back-end verifiers’ limitation to scalar variables in counterexample-trace value reporting. We do hope to address this soon, but would certainly welcome a pull request from you in case you were inclined to implement this feature.

**Comment by shaobo-he** [comment]
@michael-emmi I thought you implemented this feature for Boogie, right? If so, can I close this issue?

**Comment by michael-emmi** [comment]
Ah right this looks like the problem I fixed in boogie-org/boogie#134

**Comment by shaobo-he** [comment]
> Ah right this looks like the problem I fixed in [boogie-org/boogie#134](https://github.com/boogie-org/boogie/pull/134)

Thank you. I closed this issue because this has been fixed.
