### ISSUE TITLE
pthread_join fails memory-safety check

### ISSUE THREAD

**Issue by Bo-Yuan-Huang** [smackers/smack#250]
In checking memory safety of multi-threaded programs, pthread_join will cause a counter example. (Seems to be the nondeterministic return pointer dereferencing) Running `smack --pthread --memory-safety example.c` on the following example will find one error.

```c
#include <pthread.h>                                                            
#include <stdlib.h>                                                             
#include "smack.h"                                                              
 
char buff[8];                                                                   

void* foo (void* in) {return in;}                                               

int main () {                                                                   
    pthread_t tid;
    pthread_create (&tid, NULL, foo, NULL);
    pthread_join (tid, NULL);
    return 0;
}
```

**Comment by shaobo-he** [comment]
Closed this issue as it cannot be reproduced using SMACK version 2.4.0.

**Comment by zvonimir** [comment]
Looks fine to me. This is indeed fixed with this line:
https://github.com/smackers/smack/blob/develop/share/smack/lib/pthread.c#L73
