### ISSUE TITLE
Debug output is disabled

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#254]
The `-debug` and `-debug-only` flags to `llvm2bpl` no longer work. I noticed this as follows:
````
$ smack --debug a.c
SMACK program verifier version 1.8.0
Running clang -c -emit-llvm -O0 -g -gcolumn-info -I/usr/local/share/smack/include -DMEMORY_MODEL_NO_REUSE_IMPLS -o /Users/mje/Code/smack/a-LlFBGZ.bc a.c
Running llvm-link -o /Users/mje/Code/smack/a-zWsVtG.bc /Users/mje/Code/smack/a-LlFBGZ.bc
Running clang -c -emit-llvm -O0 -g -gcolumn-info -I/usr/local/share/smack/include -DMEMORY_MODEL_NO_REUSE_IMPLS -o /Users/mje/Code/smack/smack-pnWjLJ.bc /usr/local/share/smack/lib/smack.c
/usr/local/share/smack/lib/smack.c:133:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
...
7 warnings generated.
Running llvm-link -o /Users/mje/Code/smack/b-Dm0TUx.bc /Users/mje/Code/smack/a-zWsVtG.bc /Users/mje/Code/smack/smack-pnWjLJ.bc
Running llvm2bpl /Users/mje/Code/smack/b-Dm0TUx.bc -bpl /Users/mje/Code/smack/a-6wXDkR.bpl -warnings -source-loc-syms -entry-points main -debug -mem-mod-impls
llvm2bpl: Unknown command line argument '-debug'.  Try: 'llvm2bpl -help'
llvm2bpl: Did you mean '-bpl'?
````
Invoking `llvm2bpl` directly confirms this problem:
````
$ llvm2bpl -debug a.bc 
llvm2bpl: Unknown command line argument '-debug'.  Try: 'llvm2bpl -help'
llvm2bpl: Did you mean '-bpl'?
````
similarly with the `-debug-only` flag:
````
$ llvm2bpl -debug-only=smack-rep a.bc 
llvm2bpl: Unknown command line argument '-debug-only=smack-rep'.  Try: 'llvm2bpl -help'
llvm2bpl: Did you mean '-debug-pass=smack-rep'?
````

Not clear why this is not working now; it did work at some point. I figure the `-debug` and `-debug-only` flags should come from linking some LLVM library.

Alternatively, perhaps it is possible to add a debug flag and connect it to the `DEBUG` macros manually, as suggested [here](https://llvm.org/docs/CommandLine.html#internal-vs-external-storage). This seems like a bad solution though, given that we ought to be able to reuse LLVM’s module.

**Comment by zvonimir** [comment]
These flags worked for me only when I would compile the whole of LLVM/clang with the debug build type from scratch. They never used to work on my end when I would install LLVM/clang from packages, which are I presume built using the release build type. I suspect this might be related to the issue you are observing.

**Comment by michael-emmi** [comment]
I think it is probably worth having Smack debug capabilities even when LLVM is installed from packages. This would greatly facilitate remote debugging, e.g., including Travis builds.
