### ISSUE TITLE
Duality: unknow sort assertsPassed 

### ISSUE THREAD

**Issue by Streifenhoernchen** [smackers/smack#268]
[sum.bpl.txt](https://github.com/smackers/smack/files/1318224/sum.bpl.txt)
[sum.c.txt](https://github.com/smackers/smack/files/1318225/sum.c.txt)

Hi everybody,

I am currently trying smack with the `-verifier duality` option, but whatever I try, I get this error:

```
smack  --verifier duality sum.c -v -bpl sum.bpl

SMACK program verifier version 1.8.1
/workstore/akarl/originals/install/share/smack/lib/smack.c:133:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
/workstore/akarl/originals/install/share/smack/lib/smack.c:139:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
/workstore/akarl/originals/install/share/smack/lib/smack.c:169:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULONG_MAX);
                    ~ ^  ~
/workstore/akarl/originals/install/share/smack/lib/smack.c:175:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULONG_MAX);
                    ~ ^  ~
/workstore/akarl/originals/install/share/smack/lib/smack.c:205:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULLONG_MAX);
                    ~ ^  ~
/workstore/akarl/originals/install/share/smack/lib/smack.c:211:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULLONG_MAX);
                    ~ ^  ~
6 warnings generated.
Single threaded program detected
Verifying program while tracking: {assertsPassed}
generate: 0.048429s
Verifying main_SeqInstr...
Prover error: line 519 column 17: unknown sort 'assertsPassed@@7'
```

(Sometimes with a different number behind the two "@".)

I tried it with the most recent commit in the master branch and am using the newest corral and z3 version of their master branches.

Unfortunately this line number does not tell me anything, since the .bpl file does not contain `assertsPassed` at all :(

Nevertheless, I've attached it as well as the c source code to this issue.

Thank you for your help!

**Comment by shaobo-he** [comment]
@Streifenhoernchen Thanks for your interest in SMACK. Based on the error information, Duality seems to produce invalid input for Z3. Could you also attach the input to Z3? To generate the input, you can pass `--verifier-options="/proverLog:sum.z3"` to SMACK. `sum.z3` is the input file.

**Comment by zvonimir** [comment]
Thanks for your interest in SMACK. What @shaobo-he wrote makes sense and would be helpful to foster debugging.
However, I have a more general question. We have not been using or testing Duality much in the past year or two. It is also my understanding (and I could be wrong here) that Ken McMillan is not actively developing it any more. So it would be helpful if you could clarify your interest in trying out Duality since I think we could help you out better then. Are you looking to compare against it? Or to extend it? Or something else?
Thanks!

**Comment by Streifenhoernchen** [comment]
First of all, thank you a lot for your help!
I had some building issues (something with a wrong llvm version installed), such that I will upload the z3 file later.

Regarding the question about the application, I just wanted to try Duality and apply it, no inted to extend it. I was not aware it is not actively developed anymore. I am looking for some verification tool, which can be used without a loop unrolling bound. Instead, I have some loop invariants. Is there any backend for Boogie, which is capable of this? In addition to this,  is there any publication describing the boogie verifier itself, not only the language? Especially, I'm intereseted in your "--modular" flag, but I don not completely understand, what it does.

Thank you!

**Comment by Streifenhoernchen** [comment]
[sum.z3.txt](https://github.com/smackers/smack/files/1320837/sum.z3.txt)
Finally managed to build and run everything again...
Here is the file.

**Comment by zvonimir** [comment]
So when you say "I have some loop invariants" so you mean that you would like to be able to write (or inject) your own loop invariants into the SMACK verification process?

The `--modular` command line options enables you to do exactly that. It is experimental, but there are some examples you can follow in the `test/contracts` folder.

Regarding Boogie, there is no really one paper that summarizes it well. I suggest maybe looking at "Specification and Verification of Object-Oriented Software" lectures from Rustan Leino's homepage. Maybe also "A Verifying Compiler for a Multi-threaded Object-Oriented Language". 
This is the seminal Boogie paper: https://www.microsoft.com/en-us/research/wp-content/uploads/2005/01/krml160.pdf
I hope these help.

**Comment by Streifenhoernchen** [comment]
Thank you a lot for your help! :)

I am working on LLVM bitcode, where every basic block starts with preconditions (assumptions), which should be sufficient to prove its postconditions (assertions).
Alternatively, I could inject calls to the "invariant"-functions for the `--modular` option.

Could you tell me the exact difference between boogie with modular and boogie withou the modular flag? Do I need the `--modular` flag if I am only using assertions/assumptions?

Thank you! :)

**Comment by zvonimir** [comment]
I see, interesting. Without the `--modular` flag, Boogie inlines all procedures and unrolls all loops up to a certain unroll depth bound. With `--modular` flag it instead tries to prove the program correct using pre- and post-conditions on procedures and loop invariants, which it seems would suite your needs better. Note, however, that Boogie was not built to perform modular verification per basic block, but rather per procedure. So one would have to think a little bit how to do it per basic block.

Actually, I do have another follow-up question - what is the reason for annotating all basic blocks with pre- and postconditions? Is it to perform modular per-block verification or something else?

If you are not looking to create modular proofs, you can run Boogie (or even Corral) in their default mode (without `--modular`) and simply annotate all basic blocks with assumptions and assertions. Boogie/Corral will prove them by inlining and unrolling as I described above. Even in this case (no real modular proving) it would be interesting to see if having all these assumptions and assertions actually speeds up verification. So maybe this would be something to try out first. You can easily encode assumptions and assertions using `assume` and `assert` statements.
