### ISSUE TITLE
Boogie incorrectly finding assert violations in Boogie files

### ISSUE THREAD

**Issue by liammachado** [smackers/smack#274]
Boogie is determining there to be an assert violation in Boogie files, even when the corresponding C source file contains no such assertions. However, it only does this when I separately generate the Boogie file in one command, and verify the Boogie file in the next. 

For example, for examples/rise4fun/rise_simple.c, if I run "smack rise_simple.c --verifier=boogie", Boogie correctly outputs that no errors were found.  
However, if I run:

"smack -t -bpl rise_simple.bpl rise_simple.c"
"smack rise_simple.bpl --verifier=boogie -v"

then I receive the following error message:

/home/vagrant/smack_master/test/basic/a-punuxP.bpl(209,3): Error BP5001: This assertion might not hold.
Execution trace:
    /home/vagrant/smack_master/test/basic/a-punuxP.bpl(202,1): $bb0#1

Boogie program verifier finished with 9 verified, 1 error
/usr/local/share/smack/lib/smack.c(42,1): This assertion might not hold.
Execution trace:
    /usr/local/share/smack/lib/smack.c(260,3):

SMACK found an error.

I have tested this on several Boogie files and receive the same result. Also, I have found this to occur on builds of both master and develop branches.

**Comment by michael-emmi** [comment]
Smack’s translation is tailored to specific back-end verifiers, specified with `--verifier`, the default being Corral. Your first `smack -t` command thus tailors the generated Boogie code for Corral, and then you give this code to Boogie. This is not supposed to work :-)

Instead, add the `--verifier=boogie` to your first (translation) command as well, and things will work as expected.
