### ISSUE TITLE
Smack fails with Permission denied

### ISSUE THREAD

**Issue by Hirse** [smackers/smack#282]
Environment: Win 10 1709 - WSL Ubuntu 16.04.3 LTS

I just installed SMACK using the [build-script](https://github.com/smackers/smack/blob/master/bin/build.sh) and wanted to test with the example from the ["Running SMACK" guide](https://github.com/smackers/smack/blob/master/docs/running.md) and this error occurred:
```
hirse@Carbonhirse:~/jerminator$ ./smack/bin/smack example.c
SMACK program verifier version 1.9.0
Traceback (most recent call last):
  File "./smack/bin/smack", line 13, in <module>
    smack.top.main()
  File "./smack/bin/../share/smack/top.py", line 679, in main
    verify_bpl(args)
  File "./smack/bin/../share/smack/top.py", line 548, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "./smack/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: /usr/local/bin/corral: line 2: /home/hirse/jerminator/a-fqSrVZ.bpl: Permission denied
```

Running as `sudo` I get the same error.

**Comment by michael-emmi** [comment]
Hi @Hirse I’m not sure we’ve seen this problem before, but I suspect it has something to do with WSL, on which, as far as I am aware, we have never tested Smack. While we figure out how to reproduce this environment, you might get more milage by running on Linux/OSX — if that is an option.

@zvonimir are you aware of anybody running smack on WSL?

**Comment by zvonimir** [comment]
@Hirse could you please try running the smack-doctor script from the bin folder and sharing the output here?
That would give us some more information to work with.

**Comment by Hirse** [comment]
<img width="388" alt="2017-11-17_12-50-33" src="https://user-images.githubusercontent.com/2564094/32968436-10964f32-cb96-11e7-9199-4129f045a2b6.png">

```
hirse@Carbonhirse:~/jerminator/smack$ ./bin/smack-doctor
Checking front-end dependencies...
[X] clang is in the path
[X] clang is executable
[X] clang++ is in the path
[X] clang++ is executable
[X] llvm-config is in the path
[X] llvm-config is executable
[X] llvm-link is in the path
[X] llvm-link is executable
Checking back-end dependencies...
[X] boogie is a bash script
[X] boogie redirects to BOOGIE
[-] BOOGIE environment variable is set
Traceback (most recent call last):
  File "./bin/smack-doctor", line 13, in <module>
    smack.doctor.main()
  File "./bin/../share/smack/doctor.py", line 99, in main
    check_verifier("boogie")
  File "./bin/../share/smack/doctor.py", line 56, in check_verifier
    check("%s environment variable is set" % var, var in os.environ)
  File "./bin/../share/smack/doctor.py", line 27, in check
    count += 1
NameError: global name 'count' is not defined
```

**Comment by zvonimir** [comment]
Ah, I fixed this problem with smack-doctor in the develop branch. Could you run it from the develop branch (instead of master)? Sorry about this.

**Comment by Hirse** [comment]
Running from develop:
<img width="310" alt="2017-11-18_09-52-53" src="https://user-images.githubusercontent.com/2564094/32983245-61f577f8-cc46-11e7-89db-6a4f9a205316.png">
```
hirse@Carbonhirse:~/jerminator/smack$ ./bin/smack-doctor
Checking front-end dependencies...
[X] clang is in the path
[X] clang is executable
[X] clang++ is in the path
[X] clang++ is executable
[X] llvm-config is in the path
[X] llvm-config is executable
[X] llvm-link is in the path
[X] llvm-link is executable
Checking back-end dependencies...
[X] boogie is a bash script
[X] boogie redirects to BOOGIE
[-] BOOGIE environment variable is set
[X] boogie is in the path
[-] boogie is executable
[X] corral is a bash script
[X] corral redirects to CORRAL
[-] CORRAL environment variable is set
[X] corral is in the path
[-] corral is executable
Checking SMACK itself...
[X] llvm2bpl is in the path
[X] llvm2bpl is executable
[X] smack is in the path
[X] smack is executable
```

**Comment by zvonimir** [comment]
It appears you forgot to set the required environment variables as described in the installation procedure. I added a blurb there to point this out better since this has been a common mistake. I hope that helps.

**Comment by Hirse** [comment]
Thanks for the debugging help.

Reading the following statement led me to believe I didn't have to do any further manual steps:
> Running this script on a fresh installation of Ubuntu or openSUSE Linux should actually result in the full installation of SMACK and its requirements.

Could you possible also add a short snippet showing which variables have to be set into the guide itself?

**Comment by zvonimir** [comment]
Thanks for pointing this out! I added more clarification there.
