### ISSUE TITLE
Adding simple check for environment variables into SMACK script

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#284]
It is a very common mistake for our users to forget to set the required environment variables. Yes, I understand that they should read the documentation maybe more carefully :), but it would be beneficial for everyone if we would have a simple check for that in our SMACK script.
Moreover, another problem is that not having these environment variables set typically leads to a cryptic exception that reports `Permission denied` as the error, which leads to further confusion (file permissions, etc.). So it would be nice to have a better error message (i.e., less misleading) for this problem.

**Comment by michael-emmi** [comment]
I wonder whether this check would more naturally fit into the `corral` and `boogie` shell scripts that we provide. Specifically, we can check both (a) whether the `$CORRAL`/`$BOOGIE` variables are set, and (b) whether the executables they point to are in the path, via `which`.
