### ISSUE TITLE
Loop detection

### ISSUE THREAD

**Issue by Hirse** [smackers/smack#285]
When testing whether SMACK can detect infinite loops, I found that the following example doesn't produce any warnings:
```c
#include "smack.h"

int main(void) {
    int i = 0;
    while (i < 5) {
        i--;
    }
    assert(i == 5);
    return 0;
}
```
(The error to detect in this simplified example being the usage of `--` instead of `++`.)

Setting a higher `loop-limit` doesn't seem to have any effect either:
```
hirse@Carbonhirse:~/jerminator$ smack --loop-limit=9 loop.c
SMACK program verifier version 1.9.0
SMACK found no errors with unroll bound 1.
```

Is this something SMACK should be able to find or is it out of scope anyway?

**Comment by zvonimir** [comment]
Hmmm, I don't fully understand what this example is trying to test for. It is true that SMACK cannot detect infinite loops. In its default mode SMACK performs bounded exploration, meaning that it unrolls loops and recursion up to the user-specified bound.
Now, what do you expect SMACK should produce for this example?
This loop is actually not infite btw since integers will underflow. In practice this typically means `i` would wrap around. However, this is undefined behavior according to the C standard and hence anything could actually happen.

**Comment by Hirse** [comment]
Ah, yes it is not infinite in C (I am doing a project where I compile another language to C so I can use model checkers), but by asserting the loop condition we can check if it went through correctly or wrapped around.

I was just hoping SMACK would be able to detect it.

**Comment by zvonimir** [comment]
Hmmm, I am confused here.
You would like for SMACK to detect that this is an infinite loop. Ok, I get that part.
But then what is the point of having the assertion in this example?
I guess I am still unsure what the expected output for this example should be. Could you maybe describe what the expected output should be for this example?
That way maybe I could point you in the right direction.

**Comment by Hirse** [comment]
I didn't have any particular output in mind. This was just one step of trying to see how I could use SMACK for detecting that infinite loop.

I thought, if the assertion is true, it means the loops was exited as intended. Otherwise it is skipped (or exited by overflow).

**Comment by zvonimir** [comment]
I see, thanks for clarifying this. Yep, SMACK is not capable of proving termination of loops, for that you need a different set of techniques that SMACK does not support. If termination is what you are after, a good place to start is looking at the tools that compete in the termination category in the annual SV-COMP software verification competition.

**Comment by Hirse** [comment]
Alright, I will have a look there then.

Thanks for your support and the advice.
