### ISSUE TITLE
Grep -P flag used in regressions is not cross-platform

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#287]
The regressions `test/basic/select{,_fail}.c` are not cross platform compatible due to the use of the `-P` grep flag:
````
// @checkbpl grep -P ":= if.+then.+else.+"
````
The `-P` flag is not available with the `grep` that comes with OS X 10.13. More generally speaking, it seems that the `-P` flag is only provided by GNU grep, and not BSD grep.

https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches

**Comment by zvonimir** [comment]
@shaobo-he : Please take a look into making this cross-platform compatible.

**Comment by shaobo-he** [comment]
@zvonimir No problem. Should I fix it in the develop branch or create a PR? The fix is quite tiny.

**Comment by zvonimir** [comment]
Just fix it in develop. Refer to this issue in your commit message so that we know you fixed it.
