### ISSUE TITLE
Issues on simple.c

### ISSUE THREAD

**Issue by j29scott** [smackers/smack#289]
Hi. I am very excited by the results of your tool but I am having some issues running it. I have tried building it on several different machines and fresh Ubuntu 14 and 16 machines.

I apologize if I am overlooking something trivial in the documentation.

When I run `bin/build.sh` everything seems to install correctly. The testing done at the end of the script says that all 196 instances pass the test.

Yet when I run the following `sudo smack simple.c` I get the following error:

>  SMACK program verifier version 1.9.0
> Traceback (most recent call last):
>   File "/usr/local/bin/smack", line 13, in <module>
>     smack.top.main()
>   File "/usr/local/bin/../share/smack/top.py", line 679, in main
>     verify_bpl(args)
>   File "/usr/local/bin/../share/smack/top.py", line 548, in verify_bpl
>     verifier_output = try_command(command, timeout=args.time_limit)
>   File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
>     raise Exception(output)
> Exception: /usr/local/bin/corral: line 2: /home/j29scott/smack/smack/examples/simple/a-R5YjfN.bpl: Permission denied

I have gotten this on all machines I tried it on. Furthermore, when I run the test script `test/regtest.py` I get all UNKNOWN.

I have further tried using the vagrant builds but have not had luck with those either.

**Comment by zvonimir** [comment]
You have to source `smack.environment` to set several needed environment variables. See here: https://github.com/smackers/smack/blob/master/bin/build.sh#L416
This is a common problem and we have an outstanding issue open (#284) to implement better error checking and error messages.

**Comment by j29scott** [comment]
Thank you so much. Works as expected now. Sorry for the redundant issue.

**Comment by zvonimir** [comment]
No problem. Glad to know it works.
