### ISSUE TITLE
Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause

### ISSUE THREAD

**Issue by elefthei** [smackers/smack#304]
I'm trying to run boogie on the output bpl file from Smack and I keep getting this error:

```
impl.bpl(133,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
impl.bpl(160,2): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $M.0
impl.bpl(176,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
```
Maybe the problem is I'm using the latest boogie version but I would actually be interested in help update Smack to match Boogie 2 expectations if that's something you'd be interested in having. Here's how I invoke Boogie stand-alone:

`mono /home/lef/boogie/Binaries/Boogie.exe -nologo -useBaseNameForFileName impl.bpl`

The BPL file was generated like this:
`smack --verifier boogie -bpl impl.bpl -t impl.c`

If there's another way to invoke the Boogie executable (stand-alone) that smack uses, that could also help. I have verified `smack impl.c` indeed works and passes with no errors, so I'm not attaching the C file.

**Comment by shaobo-he** [comment]
@elefthei Thanks for your interest in SMACK. I think you may want to add `/doModSetAnalysis` to the command line invoking Boogie. The reason is that the BPL files generated by SMACK do not contain any modifies clauses which are required by Boogie. The flag `/doModSetAnalysis` performs an analysis to acquire this type of information.

**Comment by elefthei** [comment]
That worked! Thank you!
