### ISSUE TITLE
Zero sized structure members break DSA

### ISSUE THREAD

**Issue by keram88** [smackers/smack#309]
In this ir file [https://gist.github.com/keram88/9b81a2cf33d8f2153cb325e35b259fe2](https://gist.github.com/keram88/9b81a2cf33d8f2153cb325e35b259fe2) there is a type
`%"core::marker::PhantomData<u64>" = type {}`
which is zero sized. This appears in a structure and causes a crash in DSA, specifically at
`llvm::DSNode::mergeTypeInfo(llvm::Type*, unsigned int) + 470`

The inlined structure would look like:
`%"S<u64>" = type { type {i32, type {}}, i32}`

The Rust code that generates this error is:
```
use std::marker::PhantomData;

#[macro_use]
mod smack;
use smack::*;

struct X<T> {
  x: i32,
  phantom: PhantomData<T> // To consume the generic type: this is zero-sized (type {})
}

struct S<T> {
  pub phantom: X<T>,
  pub data: i32,
}

fn main() {
  let mut x = S::<u64>{ phantom: X { x: 7, phantom: PhantomData }, data: 4 };
  x.data += 1;
  assert!(x.data == 5);
}
```

**Comment by shaobo-he** [comment]
Fixes via #550
