### ISSUE TITLE
Unsupported Constant Type

### ISSUE THREAD

**Issue by jjgarzella** [smackers/smack#310]
SMACK currently supports a limited subset of the types of LLVM IR constants. The following type of constant is used by the D programming language, but SMACK crashes whenever such a constant is used by code. 

Examples:
```
@.str = private unnamed_addr constant [13 x i8] c"Hello World!\00" ; [#uses = 1]
@.str.1 = private unnamed_addr constant [10 x i8] c"null this\00" ; [#uses = 1]
```

[examples.zip](https://github.com/smackers/smack/files/1864465/examples.zip)

To run the examples, use `smack [filename].ll --entry-points _Dmain`

**Comment by shaobo-he** [comment]
@jjgarzella This issue actually has nothing to do with the constant arrays representing strings. The reason is that constant structures are used as arguments.

```
define i32 @_Dmain({ i64, { i64, i8* }* } %unnamed) #0 comdat {
  call void @_D3std5stdio16__T7writelnTAyaZ7writelnFNfAyaZv({ i64, i8* } { i64 12, i8* getelementptr inbounds ([13 x i8], [13 x i8]* @.str, i32 0, i32 0) })
  ret i32 0
}
```
A structure of `{ i64, i8* }` is passed as the argument.
