### ISSUE TITLE
Problematic translation of phi instruction

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#314]
Hey guys,

Ian found an issue with SMACK's translation of phi instruction. Basically the current implementation adds assignment at the end of each predecessor block. This can be problematic if the incoming value is a value from the block where phi instruction resides. For example, consider the following CFG,

```
ENTRY: ...

BODY:  i = phi [0, ENTRY], [incr, BODY]
       incr = add i 1
       br *,  BODY, CONT

CONT: br EXIT

EXIT: f = phi [i, CONT], [*,*]
```
, the Boogie translation would be,

```
ENTRY: ...

BODY: incr := i + 1;
      i := incr;

CONT: f := i;

EXIT: ...
```
If we have a path ENTRY --> BODY --> CONT --> EXIT, we should expect `f` to be equal to `0` while in the Boogie program it's `1`.

**Comment by keram88** [comment]
This is fixed.
