### ISSUE TITLE
Some problems about duality

### ISSUE THREAD

**Issue by MumumuZi** [smackers/smack#315]
Hi everyone, recently I'm trying to do something by smack, but I'm encountering some pproblems. In the video of demo I saw a test program named unboundLoop ,but when I tested the example with the duality option ,it stuck.
int main(){
  long x = _VERIFIRE_nondet_long();
  long y = 0;
  long z = 0;
  assume(x > 100);
  for(;y < x; ++y)
     z += 1;
  assert(z != x);
  return 0;
}

lmz@ubuntu:~/smack/examples/unboundloop$ smack --verifier duality unboundedLoop_example.c 
SMACK program verifier version 1.9.0
unboundedLoop_example.c:2:12: warning: implicit declaration of function '_VERIFIRE_nondet_long' is invalid in C99 [-Wimplicit-function-declaration]
  long x = _VERIFIRE_nondet_long();
           ^
unboundedLoop_example.c:5:3: warning: implicit declaration of function 'assume' is invalid in C99 [-Wimplicit-function-declaration]
  assume(x < 100);
  ^
unboundedLoop_example.c:8:3: warning: implicit declaration of function 'assert' is invalid in C99 [-Wimplicit-function-declaration]
  assert(z != x);
  ^
3 warnings generated.
SMACK timed out.

**Comment by michael-emmi** [comment]
Hi @MumumuZi,
Your code is missing the header file which declares these functions, and you’ve mistyped one of the function names: `_VERIFIRE_nondet_long` should be `_VERIFIER_nondet_long`. Then prepend the following directive:
```
#include <smack.h>
```

**Comment by MumumuZi** [comment]
Thanks very much for your reply,@michael-emmi ,
 but after modifying my program according to your opinion, when using --verifier duality verification, the result still shows timeout, I tested on other programs and got the same result.

//examples/unboundloop/unbondedLoop_example.c
#include "smack.h"

int main(){
  long x =  __VERIFIER_nondet_long();
  long y = 0;
  long z = 0;
  assume(x > 100);
  for(;y < x; ++y)
     z += 1;
  assert(z != x);
  return 0;
}

**Comment by shaobo-he** [comment]
@MumumuZi Our Duality support is not up-to-date. Can you try the following command and see if there is a line in the output saying something like "Prover error: ..."?

```
smack --verifier duality unboundedLoop_example.c -v
```

**Comment by MumumuZi** [comment]
@shaobo-he  yes,you are right

lmz@ubuntu:~/smack/examples/unboundloop$ smack --verifier duality unboundedLoop_example.c -v
SMACK program verifier version 1.9.0
/usr/local/share/smack/lib/smack.c:133:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
/usr/local/share/smack/lib/smack.c:139:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
/usr/local/share/smack/lib/smack.c:169:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULONG_MAX);
                    ~ ^  ~
/usr/local/share/smack/lib/smack.c:175:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULONG_MAX);
                    ~ ^  ~
/usr/local/share/smack/lib/smack.c:205:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULLONG_MAX);
                    ~ ^  ~
/usr/local/share/smack/lib/smack.c:211:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULLONG_MAX);
                    ~ ^  ~
/usr/local/share/smack/lib/smack.c:252:5: warning: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Wimplicit-function-declaration]
    memset(ret, 0, num * size);
    ^
/usr/local/share/smack/lib/smack.c:252:5: note: include the header <string.h> or explicitly provide a declaration for 'memset'
7 warnings generated.
Single threaded program detected
Verifying program while tracking: {assertsPassed}
generate: 0.783831s
Verifying main_SeqInstr...
Prover error: line 545 column 17: unknown sort 'assertsPassed@@8'

**Comment by zvonimir** [comment]
I think we resolved this. Maybe in the long run we should remove support for Duality from SMACK since Duality is not being maintained any more. It is much better to use either Boogie or Corral verifiers, which are up to date and maintained.

**Comment by zhanye** [comment]
@zvonimir , I have met the same issue, the duality occurred an error of 'assertsPassed@@8'.
I have also tried Boogie and Corral, but they can not give the right answer of the unbondedLoop_example.
Is there any other way, I can try and get a right answer?
Thanks~

**Comment by zvonimir** [comment]
First of all, we removed the support for Duality in the most recent version of SMACK in the develop branch. We'll make a release soon without Duality support. The reason is that Duality itself is not supported any more, and it is not working reliably. So you should probably not try to use it.

Related to your example, you have to unroll its loop 101 times but providing `--unroll=101` to SMACK in the command line. Now, I suggest that you start by decreasing the number of this loop iterations to something smaller, such as 10, and then trying `--unroll=11` to make sure it works. Then you try to scale it to 100 iterations. At some point SMACK will time out due to the large number of loop unrolls, since currently SMACK cannot automatically infer loop invariants.

Alternatively, you can try to provide a loop invariant manually. If that is something you are interested in, I can point you to the right examples.

We should update our video that uses Duality since it is pretty outdated at this point.

**Comment by zhanye** [comment]
Thanks, I've tried --unroll=11, it works.
 But in most time, I don't know the number of the loop iterations or in some problems I want to find the 
number of iterations which can cause crash.
I think duality may be a good choice, But it seems duality don't work well.

Hope you can fix this problem or provide another method, thank you very much.
The SMACK is a good tool, thank you for sharing.
