### ISSUE TITLE
SMACK requires all input files to have the same file extension

### ISSUE THREAD

**Issue by jjgarzella** [smackers/smack#332]
See lines 282-283 of top.py.

For supporting cross-language verification, we should allow users to call smack with multiple files of different file types. We can compile them separately into llvm and link them. The fix can be done completely in top.py

**Comment by bjohannesmeyer** [comment]
Any update on this?

**Comment by jjgarzella** [comment]
@bjohannesmeyer The functionality should be there, try it out and let us know if you have any issues
