### ISSUE TITLE
C++ fields seem to be broken

### ISSUE THREAD

**Issue by jjgarzella** [smackers/smack#338]
SMACK cannot properly verify the following C++ regression:

```
// @expect verified

#include <smack.h>

class Point {
  public:
    int x;
    int y;
    Point(int _x, int _y) : x(_x), y(_y) {}
};

int main(void) {
    Point *l = new Point(2,3);
    assert(l->x == 2);
    delete l;
    return 0;
}
```
The problem has something to do with `l->x` returning nondet. I think this has something to with the way SMACK models memory, but I don't know enough to diagnose the problem. Furthermore, when I run it with `--bit-precise-pointers`, the bpl file fails to typecheck. Both of these can be tested with the latest develop (as of 7/8/18)

**Comment by elefthei** [comment]
Is it expected to work with clang++?
