### ISSUE TITLE
exit() function declared in smack header causes trouble

### ISSUE THREAD

**Issue by niekbouman** [smackers/smack#359]
@zvonimir ran into the following compile error
```
Exception: In file included from /home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:7:
/usr/include/stdlib.h:543:13: error: exception specification in declaration does not match previous declaration
extern void exit (int __status) __THROW __attribute__ ((__noreturn__));
```

I also experienced the same problem.
Simply commenting-out the line
```cpp
     void exit(int);
```
in `smack.h` seems to solve the issue.

**Comment by jjgarzella** [comment]
I have had similar problems in the past. Is this using C++? If I remember right, I was able to avoid this error with an `#ifdef` guard in smack.h.

**Comment by niekbouman** [comment]
Yes indeed, this problem occurs with C++.

**Comment by jjgarzella** [comment]
OK, does replacing that line with 

```
#ifndef __cplusplus
void exit(int);
#endif
```
fix the issue? If it does, I can submit a patch or you can

**Comment by zvonimir** [comment]
These are temporary patches. As I mentioned in issue #351, we should have a separate header for C++, instead of having a bunch of ifdefs in the current header. I think we should be able to accomplish that once pull request #348 gets merged.

**Comment by michael-emmi** [comment]
What business does the `exit` function from `<stdlib.h>` have being declared in `<smack.h>` anyhow? This should simply be deleted, period.

**Comment by zvonimir** [comment]
Well, `smack.h` currently (still) contains models for malloc, free, realloc, and so on. These should all be moved to their respective headers. So `exit` should not be simply deleted, but rather moved into the appropriate header.

**Comment by michael-emmi** [comment]
But `<stdlib.h>` is the appropriate header file for `exit`. Why should we give our own version of this header file?

**Comment by zvonimir** [comment]
I got confused, sorry. What I wanted to say is that the model for `exit` should be in `stdlib.c` and not `smack.c`. We should at some point probably create `stdlib.c`.
Hmmm, it seems that the declaration of `exit` in `smack.h` had something to do with SVCOMP while back. I have no idea why we added it. I agree we should remove it and then we'll see what happens with SVCOMP down the road.

**Comment by michael-emmi** [comment]
Ah ok, then yes, I agree; we should maintain a Smack-specific `stdlib.c` with a model for `exit`.

Regarding SVCOMP: we should probably do any SVCOMP-specific nonsense in SVCOMP-specific header(s), no?

**Comment by zvonimir** [comment]
This is fixed.
