### ISSUE TITLE
What does "warning: memory intrinsic length exceeds...." mean?

### ISSUE THREAD

**Issue by niekbouman** [smackers/smack#360]
I am happy to announce that `ct-verif` (with a few changes to smack) can now verify my C++ file successfully, (see the Dockerfile [in this repo](https://github.com/niekbouman/verifying-constant-time/tree/cplusplus), with which my environment can be reproduced) 
however, I get the following warning (repeated several times):
```
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
warning: memory intrinsic length exceeds threshold (0); adding quantifiers.
```
I've seen this warning being mentioned before in other issues. I'd guess that it is related to the memory-copy operation in the wrapper (see below). Anyway, __what is the meaning of this warning? And is it harmful (can it impact soundness of the verification) ?__

##### How I invoke `ct-verif`
```
ct-verif.rb --clang-options "-x c++ -std=c++14 -O1" -e _Z11add_wrapperPjS_ add.cpp
```
Interestingly, I get correct verification with `-O0` and `-O1` optimization level; with `-O2` and `-O3` Boogie runs into some problem.

##### My C++ program `add.cpp`
```cpp
extern "C" {
#include "ct-verif.h"
}

#include <cstdint>
#include <cstring>
#include <array>

// suppresses warning about undefined function
void *__gxx_personality_v0;

template <size_t N, typename T = uint64_t,
          typename = std::enable_if_t<std::is_integral<T>::value>>
struct big_int {
  std::array<T, N> repr;

  constexpr T &operator[](size_t i) { return repr[i]; }
  constexpr const T &operator[](size_t i) const { return repr[i]; }
  constexpr size_t size() const noexcept { return repr.size(); }
};

// multiprecision addition
template <typename T, size_t N>
constexpr auto add(big_int<N, T> a, big_int<N, T> b) {
  T carry{};
  big_int<N + 1, T> r{};

  for (auto i = 0; i < N; ++i) {
    auto aa = a[i];
    auto sum = aa + b[i];
    auto res = sum + carry;
    carry = (sum < aa) | (res < sum);
    r[i] = res;
  }

  r[N] = carry;
  return r;
}

auto add_wrapper(uint32_t* a, uint32_t* b) {
  // ct-verif annotations
  public_in(__SMACK_value(a));
  public_in(__SMACK_value(b));
  // (pointer values are public, memory where the pointers point to is secret)

  const size_t num_limbs = 4;
  big_int<num_limbs, uint32_t> A, B;

  for(auto i=0; i<num_limbs; ++i)
  {
    A[i]=a[i];
    B[i]=b[i];
  }

  // alternatively, initialize via memcpy
  //memcpy(&(A[0]), a, num_limbs * sizeof(uint32_t));
  //memcpy(&(B[0]), b, num_limbs * sizeof(uint32_t));

  return add(A,B);
}
```

**Comment by michael-emmi** [comment]
This warning is nothing to worry about when things are otherwise working fine. It is meant as a hint to why the resulting verifier queries may not converge quickly, due to the use of quantifiers, which SMT solvers typically do not handle very gracefully.

**Comment by shaobo-he** [comment]
Closed this issue because this question seems to be answered. @niekbouman feel free to reopen it if you have further questions.
