### ISSUE TITLE
Split smack.h into a C++ and a C header

### ISSUE THREAD

**Issue by jjgarzella** [smackers/smack#361]
We have had numerous problems recently using smack.h as both a C++ and a C header. It would be desirable to have two separate headers, so to not require  `#ifdef __cplusplus` guards all over the place.

**Comment by jjgarzella** [comment]
Something to consider - this is something that is very specific to C++. Every other language imports smack.h as a C header, and then uses C interoperability to bridge types between languages. I don't know if this is possible in C++.

**Comment by michael-emmi** [comment]
@niekbouman seems to have a good solution to this in #353:
```CPP
extern "C" {
#include "smack.h"
}
```
Does this solve your problem?

**Comment by niekbouman** [comment]
I think that creating a separate C++ header might be overkill. I'd say that the right approach would be to ensure that `smack.h` avoids the use of [old-style (K&R) function declarations](
https://en.cppreference.com/w/c/language/function_declaration) as currently used in `__SMACK_value`, and then use the `extern "C"` method of including the file. See also [Wikipedia](
https://en.wikipedia.org/wiki/Compatibility_of_C_and_C%2B%2B)


This will probably be beneficial for using smack from other languages as well.

**Comment by jjgarzella** [comment]
After a few discussions, esp. in #348, I think we've agreed that the best way forward is to factor out C-specifc and C++-specific parts which model language-specific functionality (which is not much) and leave the bulk of smack.h as a C header, which must be imported in the way that @michael-emmi proposed above.
