### ISSUE TITLE
Issue with specifying languages with -x

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#364]
Then I pass `-x=svcomp` to SMACK, I get the following error:
```
smack: error: argument -x/--language: invalid choice: 'svcomp' (choose from 'SVCOMP', 'BOOGIE', 'C', 'LLVM', 'D', 'FORTRAN', 'CXX', 'JSON', 'OBJC')
```
This should be fixed. All languages should be lower-case to be backward compatible.

**Comment by jjgarzella** [comment]
@zvonimir Do we need this backwards-compatibility for languages other than svcomp? If so, then I should switch the --language parameter to work with the file extension, not the "language" structure
