### ISSUE TITLE
Warning about expression comparison always being true somehow appears

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#369]
As of commit d4e4ee8b1bcfaff88 this warning starts always appearing:
```
zvonimir@betina:~/projects/smack-project/smack/src/test/basic$ smack simple.c 
SMACK program verifier version 1.9.0
/home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:128:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
/home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:134:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= UINT_MAX);
                    ~ ^  ~
/home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:164:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULONG_MAX);
                    ~ ^  ~
/home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:170:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULONG_MAX);
                    ~ ^  ~
/home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:200:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULLONG_MAX);
                    ~ ^  ~
/home/zvonimir/projects/smack-project/smack/install/share/smack/lib/smack.c:206:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
  __VERIFIER_assume(x >= 0 && x <= ULLONG_MAX);
                    ~ ^  ~
6 warnings generated.
SMACK found no errors with unroll bound 1.
```
I would like to understand what in this commit caused for this warning to start appearing. Maybe this is something we should be worried about.

**Comment by zvonimir** [comment]
I managed to root cause this a little bit. It has nothing to do with header files I believe, but with the way the commands (clang) are being run. After this commit, the warning gets printed out on the screen by default. Before this commit, the warning only gets printed out when `--debug` is passed in to SMACK. So I guess that before we used to suppress somehow clang warnings when `--debug` is not present, which makes sense. The new implementation should reflect this and do the same kind of suppression.

**Comment by jjgarzella** [comment]
Does this have anything to do with the `lib` parameter in `default_clang_compile_command`? It's definitely possible that in the restructure, this parameter isn't set for smack.c or something. In this case, the flag that would be different is `-ftrapv` or `-DSIGNED_INTEGER_OVERFLOW`.

**Comment by zvonimir** [comment]
No, it's not that. It is related to this: https://github.com/smackers/smack/blob/3d1da47bbb1b329b41d1534e7fd82b7a3fcb1d05/share/smack/utils.py#L28
In particular, to the `console` argument. Previously, it seems that `console` would not be set to true when library files were being compiled. Now it seems it is being set to true for both library and input files. Hence, warnings are being printed out on the screen for library files as well.

**Comment by zvonimir** [comment]
Let me think about a better fix.
