### ISSUE TITLE
Overflow due to left shift not being detected

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#382]
Left shift operation can cause an overflow, as per C11 standard. That happens when the result of shifting exceeds the max number that can be stored in the used signed integer type. For example, a signed integer overflow error should be reported for this example:
```
int main(void) {
  int x = __VERIFIER_nondet_int();
  int y;
  assume(x >= 1024);
  y = x << 30; // this overflows
  return y;
}
```
However, when we run SMACK on this example with `--integer-overflow` enabled it misses this overflow.

**Comment by keram88** [comment]
```
The result of E1 << E2 is E1 left-shifted E2 bit positions; vacated
bits are ﬁlled with zeros. If E1 has an unsigned type, the value of
the result is E1 * 2^E2, reduced modulo one more than the
maximum value representable in the result type. If E1 has a signed
type and nonnegative value, and E1 * 2^E2 is representable in the
result type, then that is the resulting value; otherwise, the behavior
is undeﬁned.
```
Am I right that this means any non-negative left-shift is defined for unsigned values? If this is the case, then it seems for now that we're forced to choose between false negatives and false positives:
1) LLVM doesn't have an instruction like `llvm.add.with.overflow` for left shifts.
2) The only thing I can get Clang to do is generate a call to `__ubsan_handle_shift_out_of_bounds` with the `-fsanitize=shift` option, but it does this for every left shift including those with unsigned arguments.

**Comment by keram88** [comment]
I was wrong about what Clang does with UBSan:  it generates the code to correctly detect undefined behaviors regarding left shifts, then conditionally calls `__ubsan_handle_shift_out_of_bounds` which prints out the error then terminates the program.
