### ISSUE TITLE
isfinite() macro giving an error

### ISSUE THREAD

**Issue by jjgarzella** [smackers/smack#384]
When importing math.h (as a c++ header `#include <math.h>`), the isfinite macro seems to be giving an error. 

    #define isfinite(x) (sizeof(x) == sizeof(long double) ? __isfinitel(x) : sizeof(x) == sizeof(double) ? __finite(x) : __finitef(x))

It seems like `__isfinitel(x)` should be `__finitel(x)` to fit with the pattern, and sure enough below in the file, `__isfinitel` is not declared but `__finitel` is.

Before I submit a patch, I'd just like to confirm: which is the proper prefix here?

**Comment by liammachado** [comment]
I apologize for leaving this for so long. Yes, please submit a patch changing `__isfinitel(x)` to `__finitel(x)`.
