### ISSUE TITLE
Smack generates invalid BPL

### ISSUE THREAD

**Issue by lzbaer** [smackers/smack#391]

**Comment by lzbaer** [comment]
I ran the following command on Ubuntu 16.04:

smack gcc_coreutils_64_O1_mkdir.bc -bpl gcc_coreutils_64_O1_mkdir.bpl 

These were the resulting errors:
Exception: gcc_coreutils_64_O1_mkdir.bpl(13836,14): Error: undeclared type: i6
gcc_coreutils_64_O1_mkdir.bpl(39954,12): Error: use of undeclared function: $trunc.i8.i6
gcc_coreutils_64_O1_mkdir.bpl(39959,12): Error: use of undeclared function: $slt.i6
gcc_coreutils_64_O1_mkdir.bpl(39966,12): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(39974,12): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(56972,12): Error: undeclared type: i5
gcc_coreutils_64_O1_mkdir.bpl(57091,10): Error: use of undeclared function: $trunc.i32.i5
gcc_coreutils_64_O1_mkdir.bpl(57096,10): Error: use of undeclared function: $slt.i5
gcc_coreutils_64_O1_mkdir.bpl(57103,10): Error: use of undeclared function: $eq.i5
gcc_coreutils_64_O1_mkdir.bpl(57111,10): Error: use of undeclared function: $eq.i5
gcc_coreutils_64_O1_mkdir.bpl(57180,10): Error: use of undeclared function: $slt.i5
gcc_coreutils_64_O1_mkdir.bpl(57187,10): Error: use of undeclared function: $eq.i5
gcc_coreutils_64_O1_mkdir.bpl(57195,10): Error: use of undeclared function: $eq.i5
gcc_coreutils_64_O1_mkdir.bpl(59671,13): Error: undeclared type: i5
gcc_coreutils_64_O1_mkdir.bpl(59877,13): Error: undeclared type: i6
gcc_coreutils_64_O1_mkdir.bpl(60829,14): Error: undeclared type: i6
gcc_coreutils_64_O1_mkdir.bpl(63973,11): Error: use of undeclared function: $trunc.i32.i5
gcc_coreutils_64_O1_mkdir.bpl(63978,11): Error: use of undeclared function: $slt.i5
gcc_coreutils_64_O1_mkdir.bpl(63985,11): Error: use of undeclared function: $eq.i5
gcc_coreutils_64_O1_mkdir.bpl(63993,11): Error: use of undeclared function: $eq.i5
gcc_coreutils_64_O1_mkdir.bpl(64892,11): Error: use of undeclared function: $trunc.i8.i6
gcc_coreutils_64_O1_mkdir.bpl(64897,11): Error: use of undeclared function: $slt.i6
gcc_coreutils_64_O1_mkdir.bpl(64904,11): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(64912,11): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(66104,12): Error: use of undeclared function: $trunc.i64.i6
gcc_coreutils_64_O1_mkdir.bpl(66903,12): Error: use of undeclared function: $slt.i6
gcc_coreutils_64_O1_mkdir.bpl(66910,12): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(66917,12): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(84830,13): Error: undeclared type: i6
gcc_coreutils_64_O1_mkdir.bpl(86640,11): Error: use of undeclared function: $trunc.i32.i6
gcc_coreutils_64_O1_mkdir.bpl(86664,11): Error: use of undeclared function: $slt.i6
gcc_coreutils_64_O1_mkdir.bpl(86671,11): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(86679,11): Error: use of undeclared function: $eq.i6
gcc_coreutils_64_O1_mkdir.bpl(129319,2): Error: wrong number of result variables in call to free_: 0

I attached a zip file with the .bc file, full output of the command, and resulting .bpl file. Any advice would be appreciated.
[gcc_coreutils_64_O1_mkdir.zip](https://github.com/smackers/smack/files/2654549/gcc_coreutils_64_O1_mkdir.zip)

**Comment by zvonimir** [comment]
@lzbaer: Did my fix help to resolve this issue?

**Comment by lzbaer** [comment]
Yes! It removed most of the errors but I am still getting the following:

gcc_coreutils_64_O1_mkdir.bpl(128742,2): Error: wrong number of result variables in call to free_: 0
1 name resolution errors in gcc_coreutils_64_O1_mkdir.bpl

I attached the .bc file recompiled to target the architecture "x86_64-pc-linux-gnu-elf" to aid with debugging.

[gcc_coreutils_64_O1_mkdir.bc.zip](https://github.com/smackers/smack/files/2672255/gcc_coreutils_64_O1_mkdir.bc.zip)

**Comment by zvonimir** [comment]
Ok, I managed to root-cause this, and here is what is going on.
If you look at the ll code of your file (`llvm-dis gcc_coreutils_64_O1_mkdir.bc -o code.ll`), you can find this declaration in it:
```
declare extern_weak x86_64_sysvcc i64 @free(i64) #6
```
This line is declaring `free` to be an external function that returns `i64` integer value. This clashes with the signature of `free` as specified by the C standard, which says that it is a `void` function.
I think it would be good to try to understand where this unusual declaration of free is coming from in your file.

**Comment by lzbaer** [comment]
Okay, thank you for the feedback and bug fix! I will examine where that it is happening when I generate the bitcode file.
