### ISSUE TITLE
Passing loop control options to backend verifier

### ISSUE THREAD

**Issue by bitcalc** [smackers/smack#398]
I want to pass the backend the following option to let Corral handle a loop bound:
```
--verifier=corral --verifier-options="/maxStaticLoopBound:15"
```
However, SMACK always uses its own unrolling argument, which is either default to 1 or given by `--unroll=N`.

How to disable SMACK's unrolling control behavior and let the backend Corral to handle the loop bound?

For example, for the following code
```
#include <stdlib.h>
#include "smack.h"

#define SIZE 10

int main(int argc, char **argv) {
  int *a = malloc(SIZE * sizeof(int));
  for (int i = 0; i < SIZE; ++i) {
    if (i == SIZE - 2) {
      a[SIZE] = 0;
    }
  }
  free(a);
  return a[0];
}
```

When I run Corral on the generated bpl file, I got somewhat useful information about the loop:
```
$ $CORRAL loop1.bpl /maxStaticLoopBound:50
Warning: Using default recursion bound of 1
Single threaded program detected
LB: Loop main_loop_$bb1 requires minimum 11 iterations
LB: Took 0.87 s
Verifying program while tracking: {assertsPassed}
Program has a potential bug: True bug
PersistentProgram(1764,1): error PF5001: This assertion can fail

loop1.bpl(856,1): error PF5001: This assertion can fail
...
```

**Comment by zvonimir** [comment]
Hmmm, I am not sure I understand exactly what your concern is here.
If you look at Corral's output you posted, you can see this:
```
Warning: Using default recursion bound of 1
```
So Corral by default chooses to unroll all loops once if . This should be the same as passing `--unroll=1` (or not passing anything) to SMACK. No?

**Comment by bitcalc** [comment]
My question was how to make SMACK ignore the unroll parameter and ask Corral to estimate a lower bound. I'm not sure if this might do it: make the unroll argument of SMACK `--unroll=N` the same as the `/maxStaticLoopBound:N` of Corral. For example:
```
smack --verifier=corral --verifier-options="/maxStaticLoopBound:90" --unroll=90 file.c
```
What I want is to make Corral do things like the following:
```
...
LB: Loop main_loop_$bb1 requires minimum 11 iterations
...
```
for the above example.

My original concern was that SMACK only passes its `unroll` argument value to Corral no matter what, and that argument isn't used in the `maxStaticLoopBound` option of Corral.

**Comment by bitcalc** [comment]
I see. Thanks.
