### ISSUE TITLE
Integer overflow checker tests do not compile on OSX

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#403]
The `--integer-overflow` does not seem to work on OSX. All five regressions which use it (`bits/left_shift_*.c`) fail with `UNKNOWN`. Here’s what a manual invocation yields:

```
$ smack --bit-precise --integer-overflow ./test/bits/left_shift_overflow.c 
SMACK program verifier version 1.9.3
/usr/local/share/smack/lib/string.c:8:7: error: expected parameter declarator
char *strcpy(char *dest, const char *src) {
      ^
/usr/include/secure/_string.h:83:46: note: expanded from macro 'strcpy'
                __builtin___strcpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                                           ^
/usr/include/secure/_common.h:39:62: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                             ^
/usr/include/secure/_common.h:30:32: note: expanded from macro '_USE_FORTIFY_LEVEL'
#    define _USE_FORTIFY_LEVEL 2

```

**Comment by michael-emmi** [comment]
The same happens with the `--memory-safety` flag and regressions.

**Comment by michael-emmi** [comment]
I think this is the commit that broke it: 0a3c98b

**Comment by keram88** [comment]
Memory safety and integer overflow checks enable string support here:
https://github.com/smackers/smack/blob/1ec5879cdeac9c5c6bc054fa5513d4b06348a2f7/share/smack/frontend.py#L247

I'm not really sure what the reason for enabling strings with these to options is.

We could fix the string portion's compilation issues by adding `-D_FORTIFY_SOURCE=0` to the clang command line for Darwin.

**Comment by michael-emmi** [comment]
Confirmed: this worked on 3f844ef but not 0a3c98b

**Comment by michael-emmi** [comment]
@keram88 are you suggesting that the fix is to disable memory safety checks on OSX?

The problem is that without our own custom `string.h` header, compiling on OSX will pull in a system `string.h` header which defines string functions like `strcpy` as macros, which interferes with the definitions we provide in `string.c`.

**Comment by keram88** [comment]
No, I'm just not sure why strings is enabled with integer overflow.

Do we use the checks generated when using fortify source for memory safety?

**Comment by zvonimir** [comment]
We enable strings with integer overflows and memory safety because of SVCOMP, since strings are there often needed for such benchmarks.
Otherwise, I don't know how to fix this problem. It seems that on MacOS strcpy gets expanded into something weird, which is causing this problem. Not sure.

**Comment by michael-emmi** [comment]
I had already fixed this, by adding our own custom string.h header, which the aforementioned commit deleted, thus re-breaking it.

**Comment by zvonimir** [comment]
Ah, sorry, I get it. Yeah, I thought that using system headers would be ok. So we should put that file back in.
Can I just put it in the `include` folder, or does it have to be `include/string`?

**Comment by michael-emmi** [comment]
Well, if you put it in its own directory, then you could have better control over which custom headers are used. For instance, if we have both custom string.h and math.h in the same directory, then we will be forced to override math.h if we want to override string.h, since the overriding mechanism works by prefixing the include search path.

I’m not sure whether there’s a good reason to want the fine grained control afforded by separate directories though.

**Comment by zvonimir** [comment]
Oh, man, right. Ok, let me for now put it in the same top-level directory. We can change that if more fine-grained control will be needed in the future.

**Comment by michael-emmi** [comment]
👍🏼

P.s. i can make the fix if it’s easier, since I’ll have to test it anyways.

**Comment by zvonimir** [comment]
Almost done.

**Comment by zvonimir** [comment]
Please test it and let me know how it goes.

**Comment by michael-emmi** [comment]
All good 👍
