### ISSUE TITLE
handle pointer parameters of main()

### ISSUE THREAD

**Issue by bitcalc** [smackers/smack#408]
For the following C code:

```
#include "smack.h"

int main(int argc, char **argv) {
  int b = 1;
  if (argc >= 2) {
    b = argv[0];
  }
  return b;
}
```
SMACK reports an invalid pointer dereference at argv[0].

**Comment by zvonimir** [comment]
Well, SMACK cannot know how many arguments to expect for any given input program. Hence, you have to model this on your own, based on how many and what kind of arguments you are expecting.
For example, you can do something like this for your example:
```
int main(void) {
  int argc = __VERIFIER_nondet_int();
  assume(argc > 0);
  assume(argc < 5);
  char **argv = (char**)malloc(argc*sizeof(char*));
  int i;
  for(i = 0; i < argc; i++) {
    int length = __VERIFIER_nondet_int();
    assume(length > 1);
    assume(length < 5);
    argv[i] = (char*)malloc(length * sizeof(char));
  }
  return orig_main(argc, argv);
}

int orig_main(int argc, char **argv) {
  int b = 1;
  if (argc >= 2) {
    b = argv[0];
  }
  return b;
}
```
You will have to play with this a little bit, but I hope that the main idea makes sense.

**Comment by bitcalc** [comment]
Thanks for the example code!

I noticed that there are `__SMACK_nondet_*` and `__VERIFIER_nondet_*`. I guess that `__VERIFIER_nondet` is translated into `havoc` in boogie? Which one should be used in what situation?

**Comment by zvonimir** [comment]
You should almost always use `__VERIFIER_nondet_*` functions since they constrain returned values to max and min for the given type. The `__SMACK_nondet_*` functions are in some sense "lower" since they do not come with such constraints.
