### ISSUE TITLE
Support Ubuntu 18.04

### ISSUE THREAD

**Issue by computereasy** [smackers/smack#411]
Hello Smackers,

I am writing to inquire the feasibility and timeline of supporting Ubuntu 18.04. I tried to hack the provided `build.sh`, following what is given for Ubuntu 16.04, but so far it does not work.  

In particular, the following code seems to cause some issue. 

````
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
sudo apt-get install -y apt-transport-https
````

Could anyone suggest some workaround for this? Thanks a lot.

**Comment by zvonimir** [comment]
Thanks for reporting this! We don't have much experience running SMACK on 18.04, and so I have no idea why this is happening. I'll take a closer look next week.

**Comment by computereasy** [comment]
@zvonimir  Thank you! I appreciate. `smack` runs quite well on our Ubuntu 16.04 machine for some model checking tasks but since our machine has been upgraded into 18.04, I am looking for some solutions to setup the environment there. 

I look forward to your advice!

**Comment by computereasy** [comment]
@zvonimir  Thanks. Just had more time to look into this. I tried to manually install all the required packages (e.g., llvm-3.9), and everything works as expected. I am going to close this issue for now, and in case you have time, perhaps a ready-to-go build.sh for Ubuntu 18.04 would be a good option;) but note that Z3 does not have a corresponding release version, although the 16.04 release works fairly well.
