### ISSUE TITLE
Remove floats-related quantified axioms

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#412]
I would like that we discuss removing all the floats-related quantified axioms found here:
https://github.com/smackers/smack/blob/develop/share/smack/lib/smack.c#L1150

As we know, quantifiers suck and it is really good to avoid them if possible. And these are the only quantified formulas we have when memory safety checking is turned off. So it would be really nice to get rid of them somehow.

Here is how they look like:
```
  D("axiom (forall f: bvhalf :: $bitcast.bv16.bvhalf($bitcast.bvhalf.bv16(f)) == f);");
  D("axiom (forall f: bvfloat :: $bitcast.bv32.bvfloat($bitcast.bvfloat.bv32(f)) == f);");
  D("axiom (forall f: bvdouble :: $bitcast.bv64.bvdouble($bitcast.bvdouble.bv64(f)) == f);");
  D("axiom (forall f: bvlongdouble :: $bitcast.bv80.bvlongdouble($bitcast.bvlongdouble.bv80(f)) == f);");
  //D("axiom (forall b: bv16 :: b[15:10] == 31bv5 && b[10:0] != 0bv10 ==> $bitcast.bvhalf.bv16($bitcast.bv16.bvhalf(b)) == b);");
  //D("axiom (forall b: bv32 :: b[31:23] == 255bv8 && b[23:0] != 0bv23 ==> $bitcast.bvfloat.bv32($bitcast.bv32.bvfloat(b)) == b);");
  //D("axiom (forall b: bv64 :: b[63:52] == 2047bv11 && b[52:0] != 0bv52 ==> $bitcast.bvdouble.bv64($bitcast.bv64.bvdouble(b)) == b);");
  //D("axiom (forall b: bv80 :: b[79:64] == 32768bv15 && b[64:0] != 0bv64 ==> $bitcast.bvlongdouble.bv80($bitcast.bv80.bvlongdouble(b)) == b);");
  // TODO: add more constraints

  D("axiom (forall f: bvfloat, rm1: rmode, rm2: rmode :: dtf(rm1, ftd(rm2, f)) == f);");
  D("axiom (forall f: bvlongdouble, rm1: rmode, rm2: rmode :: dtl(rm1, ltd(rm2, f)) == f);");

  D("axiom (forall f: bvhalf, i: i16 :: $bitcast.bvhalf.i16(f) == i <==> $bitcast.i16.bvhalf(i) == f);");
  D("axiom (forall f: bvfloat, i: i32 :: $bitcast.bvfloat.i32(f) == i <==> $bitcast.i32.bvfloat(i) == f);");
  D("axiom (forall f: bvdouble, i: i64 :: $bitcast.bvdouble.i64(f) == i <==> $bitcast.i64.bvdouble(i) == f);");
  D("axiom (forall f: bvlongdouble, i: i80 :: $bitcast.bvlongdouble.i80(f) == i <==> $bitcast.i80.bvlongdouble(i) == f);");
```

First of all, what is the purpose of each of there?
Second, how could we remove them?

**Comment by zvonimir** [comment]
Here is what @liammachado wrote in an email on this topic:
"Those last two axioms were added to optimize the performance of the float versions of the math.h functions. Take a look at this line, for example:

https://github.com/smackers/smack/blob/develop/share/smack/lib/math.c#L9

See how we convert double to float, and then back again? We thought that this was impacting performance and that adding these axioms should help. However, I have still noticed a performance discrepancy despite these axioms being present."

So are we ok to remove the last two right away?

**Comment by keram88** [comment]
Does "last two" refers to these?
```
  D("axiom (forall f: bvfloat, rm1: rmode, rm2: rmode :: dtf(rm1, ftd(rm2, f)) == f);");
  D("axiom (forall f: bvlongdouble, rm1: rmode, rm2: rmode :: dtl(rm1, ltd(rm2, f)) == f);"
```

I did a few experiments and it seems LLVM eliminated the intervening vararg conversion to double. Do we have an example where this doesn't happen?

**Comment by keram88** [comment]
I think we should remove these axioms. I've tested with and without them and there is no noticable performance difference all else being equal.

**Comment by zvonimir** [comment]
@keram88 : which axioms are you exactly referring to? Just these ones?
```
  D("axiom (forall f: bvfloat, rm1: rmode, rm2: rmode :: dtf(rm1, ftd(rm2, f)) == f);");
  D("axiom (forall f: bvlongdouble, rm1: rmode, rm2: rmode :: dtl(rm1, ltd(rm2, f)) == f);");
```
Sure, I agree with you and I'll look into removing them and then testing on SVCOMP.
But what about other axioms?

**Comment by keram88** [comment]
@zvonimir : Just those two so far, as I suspect they make no difference.

Incidentally, I found this: https://bitbucket.org/viperproject/axiom-profiler/src

"A tool for visualising, analysing and understanding quantifier instantiations made via E-matching in a run of an SMT solver (at present, only Z3 has been modified to provide the necessary log files). The tool takes a log file and presents information visually, primarily using a graph representation of the quantifier instantiations made and their causal connections. This graph can be filtered and explored in a variety of ways, and detailed explanations of individual quantifier instantiations are assembled and displayed in the left-hand panel."

**Comment by zvonimir** [comment]
I just confirmed that removing all of these axioms has no effect on the performance of SMACK on SV-COMP benchmarks:
```
D("axiom (forall f: bvfloat, rm1: rmode, rm2: rmode :: dtf(rm1, ftd(rm2, f)) == f);");
  D("axiom (forall f: bvlongdouble, rm1: rmode, rm2: rmode :: dtl(rm1, ltd(rm2, f)) == f);");

  D("axiom (forall f: bvhalf, i: i16 :: $bitcast.bvhalf.i16(f) == i <==> $bitcast.i16.bvhalf(i) == f);");
  D("axiom (forall f: bvfloat, i: i32 :: $bitcast.bvfloat.i32(f) == i <==> $bitcast.i32.bvfloat(i) == f);");
  D("axiom (forall f: bvdouble, i: i64 :: $bitcast.bvdouble.i64(f) == i <==> $bitcast.i64.bvdouble(i) == f);");
  D("axiom (forall f: bvlongdouble, i: i80 :: $bitcast.bvlongdouble.i80(f) == i <==> $bitcast.i80.bvlongdouble(i) == f);");
```
In fact, its performance improves by a tiny margin on the floating-points category. This makes sense to me.

Now, the question still remains how to get rid of these ones:
```
  D("axiom (forall f: bvhalf :: $bitcast.bv16.bvhalf($bitcast.bvhalf.bv16(f)) == f);");
  D("axiom (forall f: bvfloat :: $bitcast.bv32.bvfloat($bitcast.bvfloat.bv32(f)) == f);");
  D("axiom (forall f: bvdouble :: $bitcast.bv64.bvdouble($bitcast.bvdouble.bv64(f)) == f);");
  D("axiom (forall f: bvlongdouble :: $bitcast.bv80.bvlongdouble($bitcast.bvlongdouble.bv80(f)) == f);");
```

**Comment by zvonimir** [comment]
Ok, here is my proposed solution, which I think should work.
Whenever there is assignment of the form:
```
x := $bitcast.bv16.bvhalf(y);
```
we turn it into the following sequence:
```
x := $bitcast.bv16.bvhalf(y);
assume $bitcast.bvhalf.bv16(x) == y;
```
And we also turn an assignment:
```
x := $bitcast.bvhalf.bv16(y);
```
into the following sequence:
```
x := $bitcast.bvhalf.bv16(y);
assume $bitcast.bv16.bvhalf(x) == y;
```
I think this ought to work and we can use it to replace those leftover quantified axioms.
Thoughts?

**Comment by zvonimir** [comment]
Ok, it is more complicated then my suggestion above since we have to deal with load/store.bytes functions too. I have to think more about this.

**Comment by zvonimir** [comment]
Ok, I implemented this. Whenever a cast such as `$bitcast.bvfloat.bv32(x)` gets introduced, which happens due to bitcast instructions or stores into byte maps, I introduce an assume such as:
```
assume ($bitcast.bv32.bvfloat($bitcast.bvfloat.bv32(x)) == x);
```
I'll thoroughly test my solution on SVCOMP benchmarks.
