### ISSUE TITLE
Dealing with C promoting floats into doubles in __SMACK_code

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#413]
So according to the C standard, floats are automatically promoted into doubles when passed into vararg functions. Here is a discussion covering this:
https://stackoverflow.com/questions/28097564/why-does-printf-promote-a-float-to-a-double

This almost certainly creates performance issues for us since whenever we invoke `__SMACK_code` and pass in floats, they will get cast to doubles by clang beforehand, and reasoning about doubles is painfully slow in SMT solvers. So we should think about how to deal with this problem.

I came up with two solutions with different pros/cons:

1. We add several special `__SMACK_code_floatN` functions, where `N` determines the number of float arguments each function takes. That is how we avoid vararg in the first place. In `llvm2bpl` these functions would have to be handled separately, but in a way almost identical to the regular `__SMACK_code`. The issue with this proposal is that we are introducing these special functions.

2. We add a piece of code in the processing of `__SMACK_code` that determines for each argument if a cast from float to double is happening just before the invocation. If it is, then we remove the cast. The issue with this proposal is that we don't really know if a user actually intentionally introduced such a cast, which might happen in some situations, and we would remove all such casts. Also, this might be a bit complicated/awkward to implement since for each cast we would have to look ahead to see if the value is being passed to `__SMACK_code`, in which case we would omit generating bpl code for it. Maybe it would be better to remove such instructions in LLVM IR instead. Not sure.

Thoughts? Other proposals?

**Comment by shaobo-he** [comment]
We add a new function like `__SMACK_type_cast()` to signal if we want to use the original type or promoted type. For example, `__SMACK_code(__SMACK_type_cast(a))` means the original type of `a` is used instead of promoted type of `a`.

Or we can add substrings to `__SMACK_code` as hints that we shouldn't use the promoted types of arguments. For example, `__SMACK_code("^1,2,3^ blahblah")`.

**Comment by keram88** [comment]
I benchmarked this, and these conversions are a big problem. Simple single precision programs like this:
```
float f = __VERIFIER_nondet_float();
assume(!__isnan(f));
float g = fabsf(f);
assert(g >= 0);
```
take about three times longer with the conversions than without.

Currently, we are producing code that looks like this:
```
procedure {:inline 1} fabsf($f0: bvfloat) returns ($r: bvfloat)
{
$bb0:
  $f2 := ftd($f0);
  $f4: = dtf($f2);
  $f3 := $abs.bvfloat($f4);
  $f1 := ftd($f3);
  $r := dtf($f1);
  return;
}
```
Interestingly, removing the first `dtf(ftd(x))` chain seems to have no effect on performance.

This is the faster, simplified function:
```
procedure {:inline 1} fabsf($f0: bvfloat) returns ($r: bvfloat)
{
$bb0:
  $r := $abs.bvfloat($f0);
  return;
}
```

**Comment by zvonimir** [comment]
I really like @shaobo-he's second proposal. So we could extend `__SMACK_code` string syntax with `@f`, which would denote that this particular argument should be treated as float (and not promoted to double). So we would have `@` as now, and also this special `@f`. Yes, I think that could work really well.

Who would like to take a stab at proposing how to implement this? I suggest @liammachado take the lead on this one, unless someone else would like to do it.
I think the only potential obstacle is the fact that Boogie code will already be generated for this cast before we hit `__SMACK_code` invocation, and so one would have to go back somehow and change/remove this already generated code.

**Comment by zvonimir** [comment]
@keram88 Thanks for benchmarking this! Yeah, my hunch was it would be a big performance bottleneck.
