### ISSUE TITLE
SMACK Warnings Always Enabled

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#415]
It appears SMACK always prints warning messages: https://github.com/smackers/smack/blob/develop/share/smack/top.py#L323. We should make it optional.

Here's some evidence: http://node0.smackbenchwebserver.smack.emulab.net/results.py?runset=runs%2Fexec_2019.02.23_15.08.43.068981_Systems_DeviceDriversLinux64_ReachSafety&runset=runs%2Fexec_2019.02.23_12.36.36.318657_Systems_DeviceDriversLinux64_ReachSafety. The faster version disables warnings that are printed in DSA monitor as well as those embedded in Boogie comments. Namely, the faster version does the following two things,
```
diff --git a/lib/smack/SmackInstGenerator.cpp b/lib/smack/SmackInstGenerator.cpp
index 2c07fd1..87fac14 100644
--- a/lib/smack/SmackInstGenerator.cpp
+++ b/lib/smack/SmackInstGenerator.cpp
@@ -25,7 +25,7 @@ namespace smack {
 using llvm::errs;
 using namespace llvm;

-const bool CODE_WARN = true;
+const bool CODE_WARN = false;
 const bool SHOW_ORIG = false;

 #define WARN(str) \
```
```
diff --git a/share/smack/top.py b/share/smack/top.py
index 3ee26d5..bc3a25b 100755
--- a/share/smack/top.py
+++ b/share/smack/top.py
@@ -320,7 +322,7 @@ def llvm_to_bpl(args):
   """Translate the LLVM bitcode file to a Boogie source file."""

   cmd = ['llvm2bpl', args.linked_bc_file, '-bpl', args.bpl_file]
-  cmd += ['-warnings']
+  #cmd += ['-warnings']
   cmd += ['-source-loc-syms']
   for ep in args.entry_points:
     cmd += ['-entry-points', ep]
```

**Comment by zvonimir** [comment]
Duplicate of #406

**Comment by zvonimir** [comment]
I agree with this, and I already opened a more general issue related to this one.

**Comment by shaobo-he** [comment]
Let's close this issue and discuss it in #406.

**Comment by shaobo-he** [comment]
Some stat between the aforementioned two configurations.
[speedup.pdf](https://github.com/smackers/smack/files/2898925/speedup.pdf)
