### ISSUE TITLE
'realloc' symbol multiply defined

### ISSUE THREAD

**Issue by abhcs** [smackers/smack#417]
I have a large dll (1.2M) made using whole-program-llvm on top of llvm-clang 3.8. I wish to translate it to boogie. I have used the command `smack test.bc -bpl test.bpl -t -v`. This is the output I get:

```
SMACK program verifier version 1.9.3
ERROR: Linking globals named 'realloc': symbol multiply defined!
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 612, in main
    frontend(args)
  File "/usr/local/bin/../share/smack/top.py", line 317, in frontend
    return link_bc_files(bitcodes,libs,args)
  File "/usr/local/bin/../share/smack/frontend.py", line 301, in link_bc_files
    try_command(['llvm-link', '-o', args.linked_bc_file, args.bc_file] + smack_libs)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: ERROR: Linking globals named 'realloc': symbol multiply defined!
```

I only found 1 definition of realloc in the human-readable IR file generated using `llvm-dis-3.8 test.bc`. Any idea what is causing the error?

**Comment by zvonimir** [comment]
SMACK comes with its own definition of `realloc` (and a bunch of other C library functions). See here: https://github.com/smackers/smack/blob/develop/share/smack/lib/stdlib.c#L27
When you invoke SMACK, these definitions get automatically linked with your bc files, which is likely causing the error you are experiencing.

Would it be possible for you to try to remove your custom definition of `realloc` somehow and then give it a try again?

**Comment by abhcs** [comment]
The library I wish to analyze will not be loaded in user space (ring 3); thus it has not been linked to stdlib (the `-nostdlib` option was used), and it has an internal definition for `realloc`. Ideally, I would not make changes to the library, and just avoid linking with stdlib during the translation with smack. Is there a way to get a "pure" translation using smack? This may be unrealistic since you generate memory models that may depend on `realloc` and other memory management functions satisfying some properties, but still worth asking.

**Comment by abhcs** [comment]
Also, the memory management functions in the library do not conform to stdlib. I think they are called `AllocatePool`, `ReallocatePool`, `FreePool`. Only a portion of the library needs a stdlib interface, so a shim with redirects from `malloc` to `AllocatePool`, etc. is implemented. So, even if I removed the shim containing `realloc`, calls to the actual `ReallocatePool` would still exist in my library. It would be great if I could communicate to smack that functions `x,y,z` are my memory management functions and they satisfy the axioms `a,b,c` needed by you.

**Comment by zvonimir** [comment]
I see. So to summarize, there are two related issues here:
1. You code contains definitions of standard functions such as `malloc`, `realloc`, etc.
2. On top of that, your code implements custom memory management in `AllocatePool`, `ReallocatePool`, `FreePool` functions.

Both of these likely create problems for SMACK. So I suggest you try the following:
1. Remove definitions of `malloc`, `realloc`, `free` from your code.
2. Replace your current implementations of `AllocatePool`, `ReallocatePool`, `FreePool` with very simple models. For example `AllocatePool` should simply invoke `malloc`, `FreePool` should invoke `free`, and so on.

I would guess/hope that this would not be that hard to try out. Thoughts?

**Comment by abhcs** [comment]
Thanks for your suggestion. I will try it and let you know if I run into any issues.

Apart from assuming that memory management in the C code is done via stdlib through these three functions, does the smack translation to boogie assume other things of the C implementation that I need to be aware of?

**Comment by zvonimir** [comment]
Hmmm, nothing comes to mind at this point.
It seems to me that you are probably dealing with quite low-level code. Note that there are low-level features that SMACK does not handle soundly/precisely, and two that come to my mind are:
1. Inlined assembly
2. Manipulation of stack pointers

Please let me know how this goes and if I can help out more.

**Comment by abhcs** [comment]
I have managed to generate the Boogie translation (bc -> bpl) using Smack. However, at least one symbol that is defined in the bc file is missing in the bpl. This function is essential to my analysis. Any idea why Smack could be skipping one or more fun symbols? (I can share the bc file privately, if needed.)

**Comment by abhcs** [comment]
Nvm, I could fix the translation by specifying the argument `--entry-points` :). I will probably have more questions once I have examined the translation closely.
