### ISSUE TITLE
Clarification regarding our handling of external memory

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#418]
I can't wrap my head around the following two regressions:
https://github.com/smackers/smack/blob/master/test/basic/extern_mem.c
https://github.com/smackers/smack/blob/master/test/basic/extern_mem_fail.c

Why should the first one pass and the second one fail?

**Comment by zvonimir** [comment]
@michael-emmi I think you created these regressions and so maybe you remember this better. Thanks!

**Comment by zvonimir** [comment]
Ok, I looked at this a bit more. For me the `extern_mem_fail` example does make sense if we invoke `foo` using an address of `x`, as in `foo(&x)` and then of course change its type to `foo(int**)`. Thoughts?

**Comment by michael-emmi** [comment]
I think the idea was that we wanted to suppose a separation between program-allocated memory and memory allocated by external libraries. So unless a program-allocated address is passed to some external library function, it will not alias one returned from an external library function. The first test checks the separation, and the second test checks the “unless” part, where the address escapes to an external library.

**Comment by zvonimir** [comment]
I see, I get it, thanks.

**Comment by zvonimir** [comment]
For our future reference, this came up when I tried to replace our current hard-coded malloc/free invocations with models in `stdlib.c`. It seems that adding an implementation of `malloc` somehow changes DSA results, which ultimately causes the outcome of `extern_mem_fail` to change. In particular, the return value of `bar` gets marked as `isExternal` and the assertion passes.
While I do think that having models of malloc and free in `stdlib.c` would be nice, fighting DSA over this probably does not make sense.
