### ISSUE TITLE
Pointers to distinct regions should be distinct.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#42]
When we can determine that pointers point to distinct regions, we should further determine that those pointers cannot be equal. The following example (added as `examples/failing/extern_mem2.c` by commit db3aa79) demonstrates the problem:

```
void foo(int*);
int* bar();

int main() {
  int *x = malloc(4);
  int *y = malloc(4);
  int *z;

  foo(y);
  z = bar();

  *x = 1;
  *z = 2;

  __SMACK_assert(x != z);
}
```

One solution would be to introduce Boogie predicates which determine the region of each pointer, and then axioms that say pointers in separate regions must be different. For instance, in an abridged version of what would be generated from above:

```
function $R(int) returns (int);
axiom (forall x, y: int :: $R(x) != $R(y) ==> x != y);
// ...
procedure main() {
  call $p1 := $malloc(4);
  assume $R($p1) == 0; // $p1 in region 0
  call $p2 := bar();
  assume $R($p2) == 1; // $p2 in region 1
  assert $p1 != $p2;
}
```

**Comment by shaobo-he** [comment]
It seems that this has been resolved by introducing the predicate `isExternal` since malloced/alloced pointers cannot alias. So I temporarily closed it as the immediate issue to decide when a pointer is external or not.
