### ISSUE TITLE
Boogie seems output inconsistent results with Corral

### ISSUE THREAD

**Issue by ireneGP** [smackers/smack#422]
Hello,

i am using the `Boogie` backend to model check some LLVM IR code, but it seems to output some very inconsistent results, comparing with `Corral` (but `Corral` is just too slow).

For instance, I got the following model checking results when checking one safe instance (I have manually checked and made sure this case is safe):

<img width="1296" alt="Screen Shot 2019-03-20 at 5 01 01 PM" src="https://user-images.githubusercontent.com/44623557/54699731-dfb25d80-4b31-11e9-96ba-bf10e54fdb65.png">

And this is the corresponding checking results of `Corral`:

<img width="1103" alt="Screen Shot 2019-03-20 at 5 03 11 PM" src="https://user-images.githubusercontent.com/44623557/54699829-14beb000-4b32-11e9-8389-d9b3644f77dc.png">

How should I interpret this?

**Comment by ireneGP** [comment]
@ZackPierce  Is it a good idea to update `Boogie` to its latest version and see how it works? 

Also, it seems that `Corral` does not properly handle recursive call (becomes extremely slow or even timeout), any suggestion on that?

**Comment by ireneGP** [comment]
After some debugging, my intuition is that Boogie somehow conservatively merges evaluation results on different branches and always find the least upper bound to infer the proper. So it is "must vs. may". That's way it says "this assertion might not hold". 

Is there anyway to let `Boogie` infer the "must" fact?

**Comment by ireneGP** [comment]
https://github.com/smackers/smack/issues/423

**Comment by ireneGP** [comment]
#423

**Comment by zvonimir** [comment]
@ireneGP : has this been resolved? Is this incompleteness due to large arrays as we suspected?
Please let me know so that I can maybe close this. Thx!

**Comment by shaobo-he** [comment]
Closed this issue for now since we haven't received any feedback. @ireneGP feel free to reopen it if figure it out.
