### ISSUE TITLE
Verified(?) result when using symbooglix back-end

### ISSUE THREAD

**Issue by JiaxiangLIU** [smackers/smack#427]
Dear developers,

I used Smack 1.9.3 with the symbooglix back-end to verify my program. Smack returned "SMACK found no errors with unroll bound 1", which I understood as saying "the input program is correct". However, if I let Smack generate the corresponding Boogie file (using --bpl option), and then feed the Boogie file directly into symbooglix, symbooglix will return "NOTE: Bugs may have been missed! Exiting with NO_ERRORS_NO_TIMEOUT_BUT_FOUND_SPECULATIVE_PATHS". This result with speculative paths should be understood as "unknown" w.r.t. [this issue](https://github.com/boogie-org/symbooglix/issues/31#issuecomment-315474006). 

Are there any reasons why Smack can conclude "correct" according to the "unknown" output by symbooglix?

Here is my example program (foo.c): [foo.zip](https://github.com/smackers/smack/files/3033400/foo.zip)
<pre><code>
#include "smack.h"
int main(void) {
  unsigned long x, y, m;
  x = __VERIFIER_nondet_ulong();
  m = __VERIFIER_nondet_ulong();
  if (x >= m) {
    y = x - m;
  } else {
    y = x;
  }
  assert(y % m == x % m);
  return 0;
}
</code></pre>

Command to verify it with Smack and generate the Boogie file (foo.bpl):
<code>smack --bit-precise --bpl foo.bpl --verifier symbooglix foo.c</code>

Command to verify foo.bpl using symbooglix:
`mono sbx.exe foo.bpl`

Thanks very much!

Jiaxiang

**Comment by JiaxiangLIU** [comment]
I had a look at the source code of Smack.
In the function `verification_result()` (line 415 in smack/share/smack/top.py) which parses the output from the verifier, it seems that a string "NO_ERRORS_NO_TIMEOUT" in the output will make Smack return "verified" (line 418). I guess that is what happened to my example program. 

So that is probably a bug to be fixed?

**Comment by zvonimir** [comment]
Yes, you are right about this, good catch! Would you maybe be interested to submit a patch?
It should be fairly easy to fix this. Thanks!

**Comment by shaobo-he** [comment]
Closed this issue as Symbooglix is no longer developed. @JiaxiangLIU please feel free to reopen it if you can it necessary.
