### ISSUE TITLE
Use UBSan to generate overflow-checking assertions

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#428]
Currently we rely on `-ftrapv` which is not a Clang flag. Moreover, we may want to cover more checks of UBSan.

**Comment by zvonimir** [comment]
Sounds like a good idea to me. Was there a (good) reason why we did not do this in the first place?
I somehow vaguely remember we did discuss it.

**Comment by shaobo-he** [comment]
I think when I first implemented overflow checking, UBSan was not shipped
with Clang. But I'm not sure. The bitcode emitted by `-ftrapv` is easy to
understand while I was not sure if UBSan produces other stuff that are not
easy to model.

Zvonimir <notifications@github.com> 于2019年4月4日周四 上午8:20写道：
