### ISSUE TITLE
Compiler warnings in regression tests

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#430]
This is definitely not urgent. But we do have some compiler warnings in our regressions. For example,

```
vagrant@vagrant:~/smack$ smack test/basic/init_funcs_global.c
SMACK program verifier version 1.9.3
test/basic/init_funcs_global.c:15:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main() {
^
test/basic/init_funcs_global.c:15:1: note: change return type to 'int'
void main() {
^~~~
int
1 warning generated.
SMACK found no errors with unroll bound 1.
```

**Comment by zvonimir** [comment]
Let's clean this up. Could you generate all of them for all regressions and paste here?
So that we fix all in one commit, or at least all apart from the drivers regressions.

**Comment by shaobo-he** [comment]
The following lists contain tests that crash with compiler flag `-Werror`.

This list contains tests with compiler warnings about signatures of the `main` function.
```
./basic/init_funcs_global.c
./basic/init_funcs_global_fail.c
./basic/jain_1_true.c
./basic/jain_2_true.c
./basic/jain_4_true.c
./basic/jain_5_true.c
```
This list contains benchmarks that have other compiler warnings.
```
./bits/unaligned_struct.c
./bits/unaligned_struct_fail.c
./memory-safety/structure1.c
./memory-safety/structure1_fail.c
```
