### ISSUE TITLE
Support extractvalue when --bit-precise is enabled

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#441]
Currently we do not translate extractvalue instruction when --bit-precise is enabled, which has been a problem for Rust support. We implemented one version in the `rust-prelims` branch like this: https://github.com/smackers/smack/blob/rust-prelims/share/smack/lib/smack.c#L1167-L1211. If it looks reasonable, we should merge it in. @zvonimir @michael-emmi Any thoughts?

**Comment by zvonimir** [comment]
If I am reading this right, what you implemented is uninterpreted, yes?
I am ok with this. Except that I think we should implement this in our C++ prelude generator, and not in `smack.c`. Please create a pull request.
