### ISSUE TITLE
Handling different translation of __finite with new LLVM version

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#449]
This issue is related to pull request #444:
"It turns out Clang translates the function `__finite(d)` to `one(llvm.fabs.f64(d), inf)` where `llvm.fabs.f64` is an LLVM intrinsic (https://llvm.org/docs/LangRef.html#llvm-fabs-intrinsic). It appears the previous version of Clang directly calls the __finite function instead."
I created it so that we don't forget about it after we update to the new LLVM version.

**Comment by zvonimir** [comment]
@liammachado : Could you write a simple regression that reveals this problem? It would be helpful to have it ready while we are working on a fix.

**Comment by shaobo-he** [comment]
Closed via #451.
