### ISSUE TITLE
Erroneous warning about un-modeled overflow intrinsics

### ISSUE THREAD

**Issue by keram88** [smackers/smack#458]
I just noticed we warn about `llvm.sadd.with.overflow.i32` being un-modeled, due to the new intrinsics code.

SMACK prints the following warning when checking overflow:
```
~/smuck$ smack test.c --integer-overflow
SMACK program verifier version 1.9.3
warning: over-approximate call to : llvm.sadd.with.overflow.i32 
```
However, the intrinsic is properly modeled, but we leave the call to `llvm.sadd.with.overflow.i32` (or similar) in the basic block, as shown below:
```
 call $p1 := llvm.sadd.with.overflow.i32($i0, 1); // Problematic code
  $i2 := $sext.i32.i64($i0);
  $i3 := $sext.i32.i64(1);
  $i4 := $add.i64($i2, $i3);
  $i5 := $trunc.i64.i32($i4);
  $i6 := $sgt.i64($i4, 2147483647);
  $i7 := $slt.i64($i4, $sub.i64(0, 2147483648));
  $i8 := $or.i1($i6, $i7);
  $i9 := $zext.i1.i32($i8);
  call __SMACK_check_overflow($i9);
```
The new intrinsic code is triggered by this intrinsic and notifies the user as it does not handle the function

**Comment by zvonimir** [comment]
Wait, is this in any way related to #437? Seems totally unrelated.
Could you please explain what the issue is in a bit more detail. Also, is there a simple regression that would catch this?

**Comment by keram88** [comment]
I updated the original post. We'd need to check SMACK's console output to do a regression test. This is more of a usability issue since we shouldn't say something isn't modeled when it is.

**Comment by zvonimir** [comment]
Ah, I see. Ok, no need for regression then. Why do we leave the call in?
Would it be safe to simply remove the call during the integer overflow pass?

**Comment by keram88** [comment]
I think the reasoning was "it doesn't hurt to leave it."
The result of the call is never used again after this pass, so we just need to remove the instruction.

**Comment by zvonimir** [comment]
Yep, I think that would be the appropriate fix.
