### ISSUE TITLE
Should bit-precise-pointers imply bit-precise?

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#460]
I've been studying what SMACK does on this simple example:
```
#include <stdlib.h>
#include <stdint.h>
#include "smack.h"

int main() {
  int *a = (int*)malloc(sizeof(int));
  intptr_t b;

  b = (intptr_t)a;
  *((int *)b) = 1;
  assert(*a == 1);
  free(a);
  return 0;
}
```
When I invoke it using:
```
smack pointers5.c --bit-precise-pointers --no-memory-splitting
```
we get a type checking error in the generated bpl file. It happens when we try to store a pointer (which is a bit-vector) into memory (that maps bit-vectors into integers). The fix, which we could probably implement, would be to cast this pointer bit-vector into an integer during stores, and then back during loads.
Now, we know that such casts are horribly slow if done precisely. Another solution would be to use uninterpreted functions, but then I think we'll encounter lots of false bugs.

So I am wondering if using `--bit-precise-pointers` without `--bit-precise` makes sense in practice. Maybe we should simply set `--bit-precise` whenever `--bit-precise-pointers` is selected.

Thoughts?

**Comment by michael-emmi** [comment]
In my head that was always the assumption: I can’t think of a scenario for which you’d want but precision for pointers but not integers. The opposite is of course common: need to handle bit operations on into, but don’t want to slow down reasoning for pointers.
