### ISSUE TITLE
about documents

### ISSUE THREAD

**Issue by zhanye** [smackers/smack#463]
Hello, I have strong interest in SMACK, but I don't know how to learn it systematically.
Did you have a detail documents about the meaning of "__VERIFIER_nondet_int()"(Will it traverse all integers?), "--bit-precise",  "--verifier", and so on, Thanks very much.

**Comment by keram88** [comment]
Hello,
I'm not sure if we have a document for the functions like `__VERIFIER_nondet`. These come from the SV-COMP standard. You can read about some of them here: https://sv-comp.sosy-lab.org/2017/rules.php under "Benchmark Verification Tasks". The nondet functions will explore all possible values. `smack --help` gives short descriptions of what each flag does.

If you have more questions, feel free to ask.

**Comment by zhanye** [comment]
@keram88 , OK, thanks, I'll read the document first. If any questions, I'll ask you for help, Thanks again.

**Comment by shaobo-he** [comment]
This documentation (https://github.com/shaobo-he/smack/blob/add-usage-notes/docs/usage-notes.md) may be interesting to you.

**Comment by shaobo-he** [comment]
Closed via #305.
