### ISSUE TITLE
Mysterious failing assertion with passing struct arguments.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#47]
```
#include <smack.h>

struct S {
  int x;
  int y;
};

bool eq(struct S p1, struct S p2) {
  return p1.y == p2.y;
}

int main() {
  struct S p;
  struct S q;
  p = q;
  // __SMACK_assert(p.y == q.y);  // passes
  __SMACK_assert(eq(p,q));        // fails

  return 0;
}
```

**Comment by zvonimir** [comment]
Coming back to this. I think this example is fine when `--bit-precise` flag is added, which can then precisely handle packing/unpacking instructions. So I would add it to our regressions with `--bit-precise` turned on.

**Comment by shaobo-he** [comment]
@zvonimir It seems this example is still not in our regression. I can add it and close this issue.

**Comment by zvonimir** [comment]
Good idea. Please add it to our bit-vector regressions. Your commit should reference this issue. Thx!

**Comment by zvonimir** [comment]
Maybe also add a comment into the regression that what happens under the hood is packing of structures.

**Comment by shaobo-he** [comment]
We've added a regression for this issue. So I closed it as we've got to the bottom of this issue.
