### ISSUE TITLE
Duplicate AST class

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#481]
@hajduakos points out: the IfThenElseExpr class is identical the existing CondExpr class — modulo the enclosure in parentheses when printing. These should be merged.

https://github.com/smackers/smack/blob/cff319a0eb8808bd4265651ebe9adb380bd71837/include/smack/BoogieAst.h#L248

**Comment by zvonimir** [comment]
Good catch, this was somehow missed in several code reviews.
@keram88 : I think you introduced the additional class, and so please merge them. It should be easy to do that. I think I like the `IfThenElseExpr` name better since I find it to be more descriptive.

**Comment by hajduakos** [comment]
Make sure that parentheses are included when printing (`CondExpr` has them but `IfThenElseExpr` does not). We had some examples where missing parentheses caused a wrong expression due to operator precedence. (We were using the AST classes independently from SMACK.)

**Comment by keram88** [comment]
@zvonimir @shaobo-he actually introduced this. ;-) Anyway I have a PR to address this.
