### ISSUE TITLE
`llvm2bpl.py` failure

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#49]
The following crashes `llvm2bpl.py`. One wonders whether there is a way NOT TO crash `llvm2bpl.py` :-)
````
$ llvm2bpl.py simple.bc
Traceback (most recent call last):
  File "/usr/local/bin/llvm2bpl.py", line 62, in <module>
    bpl = llvm2bpl(args.infile, args.debug, args.memmod, args.memimpls)
AttributeError: 'Namespace' object has no attribute 'memmod'

**Comment by zvonimir** [comment]
I think this can be closed since I have not been able to currently reproduce these issues. It appears that they have been fixed.

**Comment by michael-emmi** [comment]
No longer reproducible.
