### ISSUE TITLE
Need analysis on UPI methods for MID: Cq2sW3f6sKC2bb

### ISSUE THREAD

**Issue by swapnikapervelarazorpay** [smackers/smack#495]
Need to run an analysis for MID: Cq2sW3f6sKC2bb on UPI as a method. The merchant wants to know the following 

1) Total number of UPI transactions till date 
2) Out of all the UPI transactions, what is the split on all modes 
3) Modes: Gpay,Phonepe, BHIM etc
4) The analysis is basically to understand out of all the UPI transactions till date, what is the split on each PSP application

**Comment by zvonimir** [comment]
This looks like a spam issue :). Closing it.
