### ISSUE TITLE
Re-support remainder operations

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#496]
The CVC support PR made remainder functions uninterpreted, which causes a number of false alarms in SV-COMP benchmarks. It'd be better that we add the support again. Since `rem` is not defined in the SMT lib, we can express it using the existing operations like `mod` (see https://cs.nyu.edu/pipermail/smt-lib/2014/000823.html).

**Comment by zvonimir** [comment]
@shaobo-he : could you create a regression for this?
