### ISSUE TITLE
Some rust regressions fail with the reuse memory model

### ISSUE THREAD

**Issue by keram88** [smackers/smack#497]
Some Rust regressions, such as closure.rs, fail with the reuse memory model, but work with the other memory models. This behavior is present in booth Boogie and Corral.

**Comment by shaobo-he** [comment]
It seems that the false alarm only manifests when `--bit-precise` is enabled.

**Comment by zvonimir** [comment]
Is this still a problem?

**Comment by shaobo-he** [comment]
> Is this still a problem?

I cannot reproduce this bug now. @keram88 please reopen it if you find it otherwise.
