### ISSUE TITLE
Some Rust regressions need bit-precise unnecessarily

### ISSUE THREAD

**Issue by keram88** [smackers/smack#498]
An example is in the `arith.rs` regression. This appears to be due to bit-wise code that is executed after each arithmetic operation, which leads Smack into a `panic` branch incorrectly.

**Comment by zvonimir** [comment]
@keram88 Could you please provide a minimal regression here that triggers this issue?

**Comment by shaobo-he** [comment]
@keram88 Is this issue resolved?

**Comment by zvonimir** [comment]
This is fixed.
