### ISSUE TITLE
Need to run an analysis for MID: Cq2sW3f6sKC2bb on UPI as a method

### ISSUE THREAD

**Issue by swapnikapervelarazorpay** [smackers/smack#502]
Need to run an analysis for MID: Cq2sW3f6sKC2bb on UPI as a method. The merchant wants to know the following

Total number of UPI transactions till date
Out of all the UPI transactions, what is the split on all modes
Modes: Gpay,Phonepe, BHIM etc
The analysis is basically to understand out of all the UPI transactions till date, what is the split on each PSP application

**Comment by zvonimir** [comment]
Spam.
