### ISSUE TITLE
Overly strict checking for assert function.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#515]
```console
% cat a.c && echo --- && clang -c a.c && echo --- && cat b.c && echo -- && clang -c -I/usr/local/share/smack/include b.c
#include <assert.h>

int main() {
    int x = 0;
    int *y = &x;
    assert(y);
}
---
---
#include <smack.h>

int main() {
    int x = 0;
    int *y = &x;
    __VERIFIER_assert(y);
}
--
b.c:6:23: warning: incompatible pointer to integer conversion passing 'int *' to parameter of type
      'int'; dereference with * [-Wint-conversion]
    __VERIFIER_assert(y);
                      ^
                      *
/usr/local/share/smack/include/smack.h:56:27: note: passing argument to parameter here
void __VERIFIER_assert(int);
                          ^
1 warning generated.
```

**Comment by michael-emmi** [comment]
@nchong-at-aws says: what if we changed `VERIFIER_assert(x)` into `if (!x) VERIFIER_assert(0)`?

**Comment by zvonimir** [comment]
I think the proposed fix makes sense. We can make`__VERIFIER_assert` to be a macro that expands into `if (!x) {__SMACK_code("assert false")}`. At least I think so, I would have to give it a try.

**Comment by zvonimir** [comment]
Ok, there are some dependencies to `__VERIFIER_assert` being a function, in particular in `replay.py`. So we have to be a bit more careful about this.

**Comment by zvonimir** [comment]
@nchong-at-aws Please use `assert` instead of `__VERIFIER_assert`.

**Comment by nchong-at-aws** [comment]
Thanks @zvonimir, This works fix works for me.
