### ISSUE TITLE
Modularize dependencies.

### ISSUE THREAD

**Issue by michael-emmi** [smackers/smack#518]
Currently Smack is fairly heavy-handed when it comes to installation: besides requiring install from source (see #516), Smack insists on an odd anti-convention for its Boogie and Corral dependencies: installing its own `boogie` and `corral` scripts into the path which refer to `$BOOGIE` and `$CORRAL` environment variables which must be set.

Besides going against conventions — `boogie` and `corral` should just show up in the `$PATH` — this makes packaging (see #516) inconvenient. Ideally, we would declare package dependencies on Boogie and Corral, allowing the usual modularity afforded by package management systems.

Of course, currently there is only one release of Boogie and Corral packages, respectively:
* https://www.nuget.org/packages/Boogie/2.4.1-netcore-alpha
* https://www.nuget.org/packages/Corral/2.4.1-netcore-alpha

but versioning and release automation is in the works.

Ultimately, we could declare dependencies on these packages.

As a first step, I propose we adopt the usual convention of assuming `boogie` and `corral` are in the `$PATH`, rather than doing this funky environment variable and script gymnastics.

**Comment by michael-emmi** [comment]
FYI Boogie has it’s own wrapper: https://github.com/boogie-org/boogie/blob/master/Binaries/boogie

We should assume that is in the `$PATH`, and optionally install that script if `$BUILD_BOOGIE` is set in our `bin/build.sh`.

**Comment by michael-emmi** [comment]
Adding the same for Corral: https://github.com/boogie-org/corral/pull/103

**Comment by zvonimir** [comment]
This is done.
