### ISSUE TITLE
Make boogie and corral outputs uniform

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#52]
SMACK should postprocess boogie and corral outputs and make them uniform by turning them into a SMACK-specific output. This will also result in simplifying regression scripts since we won't have to check outputs against boogie and corral specific patters.

**Comment by delcypher** [comment]
@zvonimir If it helps I already [have an infrastructure for doing part of this](https://github.com/symbooglix/boogie-runner).

This framework abstracts away the differences in tool output to produce a consistent output. I'm currently using it for my own work. Some of the code is a mess and will be cleaned up eventually but it's in a fairly usable state right now.
