### ISSUE TITLE
smack stub `pthread_join` is not memory safe

### ISSUE THREAD

**Issue by nchong-at-aws** [smackers/smack#528]
The stub for `pthread_join` in `share/smack/lib/pthread.c` dereferences `__thread_return` before checking it is non-null.

A program that is checked with `--memory-safety` using `pthread_join` with `__thread_return==NULL` will have an `invalid pointer dereference.`

```
// smack prog.c --pthread --memory-safety
#include "smack.h"
#include <pthread.h>
#include <stdlib.h>

void *t1(void *arg) {
  return NULL;
}

int main() {
  pthread_t tid1;
  pthread_create(&tid1, 0, t1, 0);
  pthread_join(tid1, NULL); //< __thread_return==NULL
  return 0;
}
```

**Comment by zvonimir** [comment]
Good catch and thanks for your fix. We implemented memory safety checking after pthreads, and they were never really properly tested together.
