### ISSUE TITLE
Leverage llvm.assume intrinsic in SMACK

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#53]
http://llvm.org/docs/LangRef.html#llvm-assume-intrinsic

So our current assume should become something like:
void assume(int x) {
    __builtin_assume(x);
}

**Comment by zvonimir** [comment]
I don't remember any more what I meant by this :). So I am closing it.

**Comment by michael-emmi** [comment]
I think the idea was that LLVM optimizations could potentially make use of source-level assume statements. And taking advantage of that might be as simple as defining `__VERIFIER_assume` as `__builtin_assume` or whatever it’s called nowadays. So long as LLVM optimizations preserve these calls.

**Comment by zvonimir** [comment]
Ah, ok, makes sense, thanks for the reminder. This should be pretty easy to try out on SVCOMP benchmarks and see if it makes a difference at all.

**Comment by shaobo-he** [comment]
Fixed via #478
