### ISSUE TITLE
Soundly model integer overflow

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#54]
Currently we are not modeling integer overflows soundly. This should be addressed at some point.

**Comment by cmr** [comment]
@zvonimir Signed overflow is only undefined in LLVM when nsw is used, see http://llvm.org/docs/LangRef.html#i-add. Rust defines signed overflow.

**Comment by shaobo-he** [comment]
Fixed via #569. Now we support wrapped integer arithmetic via flag `--integer-encoding=wrapped-integer`.
