### ISSUE TITLE
Does "--memory-safety" conflicts with the functionality of SMACK's assert?

### ISSUE THREAD

**Issue by StanPlatinum** [smackers/smack#546]
We have tried the "--memory-safety" and found something weird.

When trying to use SMACK to verify the following file and assert with `smack test.c`, an error will occur since the  `assert(a == b);`. However, if we use `smack --memory-safety test.c`, it reports no error!

```
//filename: test.c
#include "smack.h"

int main()
{
    int a = 1;
    int b = 2;
    assert(a == b);
    return 0;
}
```

Is this a bug, or it's a feature?  Thanks.

**Comment by zvonimir** [comment]
This is a design decision we made. When either memory safety or overflow checking is turned on, we disable checking of assertions. This was partially inspired by SVCOMP rules, but it also seemed like a sensible decision. I hope this helps.
We should probably document this to avoid this confusion.

**Comment by michael-emmi** [comment]
Given that assertion and memory-safety checking are mutually exclusive, perhaps it makes more sense to instead have a modal option which selects which one to check. For example, `--check=assertions` and `--check=memory-safety`. This would be extensible to any additional modes we might want in the future. I guess the default mode would be `assertions`.

**Comment by shaobo-he** [comment]
> Given that assertion and memory-safety checking are mutually exclusive, perhaps it makes more sense to instead have a modal option which selects which one to check. For example, `--check=assertions` and `--check=memory-safety`. This would be extensible to any additional modes we might want in the future. I guess the default mode would be `assertions`.

We also want to include integer overflow checking in this discussion. Currently, the three types of checks (assertion, memory safety, integer overflow) are not mutually exclusive.  AFAIK, assertion checking is mutually exclusive to either of the other two checkings whereas memory safety and integer overflow are not exclusive.

**Comment by zvonimir** [comment]
This is fixed now.
