### ISSUE TITLE
sea-dsa is unsound for pthread modeling

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#555]
The regression that shows this issue is `test/c/pthread/join_return.c`. In this example, `ret` and `retptr` should alias because in `pthread_join`, `ret`'s value is updated to `retptr` via a Boogie level global variable. This issue is closely related to #553. One possible solution is to create a C level global variable that links these pointers.

**Comment by zvonimir** [comment]
I just fixed this.
