### ISSUE TITLE
Unsigned comparisons

### ISSUE THREAD

**Issue by hernanponcedeleon** [smackers/smack#568]
I'm using smack to convert the following llvm code to Boogie:

> define i32 @main() local_unnamed_addr {
>   %1 = tail call i32 (...) @__VERIFIER_nondet_int()
>   %2 = icmp ult i32 %1, 11
>   br i1 %2, label %3, label %12
> 
> ; <label>:3:                                      ; preds = %0
>   %4 = mul nsw i32 %1, 1000000
>   br label %5
> 
> ...
> 
> ; <label>:12:                                     ; preds = %9, %0
>   ret i32 0
> }

results in

> procedure main()
> {
> bb0:
>   call i0 := __VERIFIER_nondet_int();
>   i1 := i0 < 11;
>   goto bb1, bb2;
> bb1:
>   assume (i1 == 1);
>   i2 := i0 * 1000000;
>   i3 := 0;
>   goto bb4;
> bb2:
>   assume (i1 != 1);
>   goto bb3;
> bb3:
>   return;
> bb4:
> ...
> }

When __VERIFIER_nondet_int() returns a negative number, %2 in the llvm code is 0, thus the jump goes to label 12 and the whole functions returns.

The same is not true in the Boogie code: the comparison in i1 returns 1 and thus we end up in bb1 instead of bb2 (which leads to the return in bb3).

I assume that this is related to #187 and my previous questions #545.
#187 says there is a partial solution, but I don't think it works in this particular case.

**Comment by shaobo-he** [comment]
@hernanponcedeleon if you're fine with integer modulo operation, we could revive the integer-encoding-fix branch that should fix this type of issue once for all.

@zvonimir @michael-emmi @keram88 I looked at the integer-encoding-fix branch, it's just function definition changes. How about adding them to Prelude.cpp and then use an option to switch them on and off?

**Comment by hernanponcedeleon** [comment]
If I understand correctly, this solution (using $tou functions) will be TOTAL at the price of using the expensive MOD function.

It was claimed in #187 that "modulo operations are sprinkled all over the place." ... this should ONLY happen to operations using unsigned operands right, or do they propagate more?

If this is the case, this might still be the best solutions for us. I did some testing on using your bit-precise encoding, but then I need to use the bitvectos rather than the Integer theory in the back-end SMT solvers and this results in a much slower performance.

**Comment by shaobo-he** [comment]
Fixed via #569.

**Comment by zvonimir** [comment]
@hernanponcedeleon Just to keep you in the loop, @shaobo-he implemented a pure integer encoding that can soundly handle bit-vector operations as well.

**Comment by hernanponcedeleon** [comment]
That's great to hear. Is this merged into master already or in which branch?

**Comment by zvonimir** [comment]
It's in the develop branch.

**Comment by hernanponcedeleon** [comment]
Great. I'll give it a try this week and let you know if I encounter any issue. Thanks again for the support about this.

**Comment by hernanponcedeleon** [comment]
Which is the option I need to select for the soundly encoding? `unbounded-integer` or `wrapped-integer` (or anything different)?

**Comment by zvonimir** [comment]
It would be the `wrapped-integer` one. Note that it can be really slow for some benchmarks since it uses mod.
