### ISSUE TITLE
Invalid Boogie programs generated for programs with memset/memcpy when --bit-precise is used

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#589]
Consider the following program,

```C
#include <string.h>
#include "smack.h"

int main(void) {
  unsigned long long x = 0;
  memset(&x, 1, sizeof(x));
  assert(x == 1);
  return 0;
}
```

SMACK generates a syntactically incorrect Boogie program.
This is due to sea-dsa only records one accessed type so `isTypeSafe` returns true for that node (https://github.com/seahorn/sea-dsa/issues/88).

**Comment by zvonimir** [comment]
This is fixed and so I am closing it.
