### ISSUE TITLE
Verification failing status is printed in stderr while error trace is printed in stdout

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#596]
For example,

```bash
vagrant@vagrant:~/smack$ smack test/c/basic/simple_fail.c > /dev/null
SMACK found an error.
```

**Comment by zvonimir** [comment]
So here is how we should fix it. This function: https://github.com/smackers/smack/blob/develop/share/smack/top.py#L19
should return message, exit_code pair for all entries. Status `verified` should have exit_code of 0, others should be 1, 2, etc.
Then messages should be printed, and only the exit_code should be passed to sys.exit (not the message as well).

I think this will be a nice solution. Thoughts?
