### ISSUE TITLE
[Question] verifying C programs

### ISSUE THREAD

**Issue by hernanponcedeleon** [smackers/smack#607]
I have being using SMACK for a while now, but only for translating C programs into Boogie.
Today I tried for the first time to use it to verify a program and I'm getting some problems.

I followed the installation instructions in the GitHub of boogie and the installation worked
```
ponce bin % boogie
*** Error: No input files were specified.
```
However if I try to run smack with boogie as the verifier, I get an error (I'm using the code example from [here](https://github.com/smackers/smack/blob/master/docs/usage-notes.md))
```
ponce smack % ./bin/smack a.c --verifier boogie
SMACK program verifier version 2.4.1
llvm2bpl: a.c:6:5: warning: over-approximating bitwise operation lshr; try adding flag(s): --bit-precise 
 Traceback (most recent call last):
  File "./bin/smack", line 13, in <module>
    smack.top.main()
  File "./bin/../share/smack/top.py", line 688, in main
    verify_bpl(args)
  File "./bin/../share/smack/top.py", line 510, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "./bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: *** Error: '/noinfer': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).
```
I also tried to use SMACK to convert the C file into boogie and then use the verifier directly, but this also leads to errors
```
ponce smack % smack a.c -bpl a.bpl -t               
SMACK program verifier version 2.4.1
llvm2bpl: a.c:6:5: warning: over-approximating bitwise operation lshr; try adding flag(s): --bit-precise 
 SMACK generated a.bpl
ponce smack % boogie a.bpl 
Boogie program verifier version 2.4.1.10503, Copyright (c) 2003-2014, Microsoft.
a.bpl(1468,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1487,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1507,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1526,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1545,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1705,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1772,2): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $CurrAddr
a.bpl(1779,2): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $CurrAddr
a.bpl(1813,12): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $CurrAddr
a.bpl(1816,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1831,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1846,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
a.bpl(1857,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $M.0
a.bpl(1858,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $M.1
a.bpl(1860,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
15 type checking errors detected in a.bpl
```
Is there any option I am missing?

**Comment by shaobo-he** [comment]
> I have being using SMACK for a while now, but only for translating C programs into Boogie.
> Today I tried for the first time to use it to verify a program and I'm getting some problems.
> 
> I followed the installation instructions in the GitHub of boogie and the installation worked
> 
> ```
> ponce bin % boogie
> *** Error: No input files were specified.
> ```
> 
> However if I try to run smack with boogie as the verifier, I get an error (I'm using the code example from [here](https://github.com/smackers/smack/blob/master/docs/usage-notes.md))
> 
> ```
> ponce smack % ./bin/smack a.c --verifier boogie
> SMACK program verifier version 2.4.1
> llvm2bpl: a.c:6:5: warning: over-approximating bitwise operation lshr; try adding flag(s): --bit-precise 
>  Traceback (most recent call last):
>   File "./bin/smack", line 13, in <module>
>     smack.top.main()
>   File "./bin/../share/smack/top.py", line 688, in main
>     verify_bpl(args)
>   File "./bin/../share/smack/top.py", line 510, in verify_bpl
>     verifier_output = try_command(command, timeout=args.time_limit)
>   File "./bin/../share/smack/utils.py", line 69, in try_command
>     raise Exception(output)
> Exception: *** Error: '/noinfer': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).
> ```
> 
> I also tried to use SMACK to convert the C file into boogie and then use the verifier directly, but this also leads to errors
> 
> ```
> ponce smack % smack a.c -bpl a.bpl -t               
> SMACK program verifier version 2.4.1
> llvm2bpl: a.c:6:5: warning: over-approximating bitwise operation lshr; try adding flag(s): --bit-precise 
>  SMACK generated a.bpl
> ponce smack % boogie a.bpl 
> Boogie program verifier version 2.4.1.10503, Copyright (c) 2003-2014, Microsoft.
> a.bpl(1468,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1487,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1507,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1526,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1545,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1705,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1772,2): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $CurrAddr
> a.bpl(1779,2): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $CurrAddr
> a.bpl(1813,12): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $CurrAddr
> a.bpl(1816,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1831,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1846,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> a.bpl(1857,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $M.0
> a.bpl(1858,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $M.1
> a.bpl(1860,7): Error: command assigns to a global variable that is not in the enclosing procedure's modifies clause: $exn
> 15 type checking errors detected in a.bpl
> ```
> 
> Is there any option I am missing?

Hey @hernanponcedeleon,

Could you share the version information of SMACK as well as Boogie that you're using? For the second issue, you probably need Boogie flag `/doModSetAnalysis` since Boogie need explicit modifies clauses which SMACK does not generate.

**Comment by hernanponcedeleon** [comment]
Hi @shaobo-he , below are the versions. Using the `/doModSetAnalysis` worked. Thanks.

```
ponce smack % boogie /version
Boogie program verifier version 2.4.1.10503, Copyright (c) 2003-2014, Microsoft.
ponce smack % smack --version
SMACK version 2.4.1
```

**Comment by zvonimir** [comment]
Looking at your first SMACK error that you reported, I think you maybe have another problem here. There, the error seems to involve SMACK setting the `/noinfer` flag for Boogie, which leads to Boogie throwing an error since as of recently Boogie does not support this flag any more. So it seems that you are maybe running an "older" (back from April) version of SMACK with a newer version of Boogie, and there are some compatibility issues there since Boogie changed some key flags.

I suggest you switch to using the latest release of SMACK that we did a few days ago to prevent such issues from happening.

**Comment by hernanponcedeleon** [comment]
As @zvonimir suggested, the problem disappear with smack 2.5.0. Thanks!
