### ISSUE TITLE
[Feedback] bit precision

### ISSUE THREAD

**Issue by hernanponcedeleon** [smackers/smack#611]
It seems the old --bit-precise options has been replaced by `--integer-encoding bit-vector` in version 2.5.0.
If the options is not given, the integer encoding is used by default.
If the program has bitwise operations, the warning still suggests to use the old --bit-precision flag
```
warning: over-approximating bitwise operation xor; try adding flag(s): --bit-precise 
```
Probably you forgot to update the warning msg.

**Comment by zvonimir** [comment]
Good catch! I just issued a pull request that fixes this.
