### ISSUE TITLE
Weird naming convention in SmackWarnings

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#614]
To me it seems that functions `warnIfUnsound` and `warnUnsound` are also reporting incompleteness warnings.
For example, this `warning: over-approximating bitwise operation and` is an incompleteness warning if we are indeed over-approximating this operation. So I am confused about the naming convention here.

To me it seems we should split this into `warnUnsound` and `warnIncomplete` functions. Thoughts?

**Comment by zvonimir** [comment]
@shaobo-he could you maybe comment on this since I think you wrote that code? Maybe I am missing something? Thanks!

**Comment by shaobo-he** [comment]
> @shaobo-he could you maybe comment on this since I think you wrote that code? Maybe I am missing something? Thanks!

I think we discussed this when I implemented this feature. I remember that unsound may seem intuitive to the users than incomplete.

**Comment by zvonimir** [comment]
Hi Shaobo. Coming back to this. Soundness and completeness mean two different things. Unsound means that bugs can be missed, while incomplete means that false bugs can get reported. So I don't quite understand your argument to use unsound instead of incomplete. Could you please elaborate? Thanks!

**Comment by shaobo-he** [comment]
> Hi Shaobo. Coming back to this. Soundness and completeness mean two different things. Unsound means that bugs can be missed, while incomplete means that false bugs can get reported. So I don't quite understand your argument to use unsound instead of incomplete. Could you please elaborate? Thanks!

Ok. I think what you said makes more sense. Let me update the names.

**Comment by zvonimir** [comment]
This is fixed.
