### ISSUE TITLE
Weird space in the beginning of warning lines

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#615]
Here is an example:
```
SMACK program verifier version 2.5.0
WARNING: inttoptr @ addr 0x1ad0f88 is (unsoundly) assumed to point to a fresh memory region.
 WARNING: inttoptr @ addr 0x1ad10e8 is (unsoundly) assumed to point to a fresh memory region.
 WARNING: detected ptrtoint instruction that might be escaping the analysis. (@28120376)
```
It would be nice to get rid of this weird space.

**Comment by zvonimir** [comment]
This is a really annoying one, and warnings from sea-dsa have the same problem. I have no idea where this whitespace is coming from. So weird. Any suggestions?

**Comment by shaobo-he** [comment]
It appears this comes from this line: https://github.com/smackers/smack/blob/bbf96881b90fc94ea71bc83986241f3282f6e7c9/share/smack/utils.py#L74

**Comment by zvonimir** [comment]
This has been fixed. Closing.
