### ISSUE TITLE
Division operation for bitvectors

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#62]
It seems that there is no built-in division operations of Z3 for bit-vectors. Should I write one derived from multiplication?

**Comment by michael-emmi** [comment]
Z3 does have bit-vector division operations, in fact it has two: `bvudiv`, `bvsdiv`. Look here for a nice list of operations:
http://research.microsoft.com/en-us/um/people/leonardo/z3_doc/group__theories.html
