### ISSUE TITLE
callbr instruction is not modeled

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#623]

**Comment by zvonimir** [comment]
LLVM IR description says (https://llvm.org/docs/LangRef.html#callbr-instruction):
```
This instruction should only be used to implement the “goto” feature of gcc style inline assembly. Any other usage is an error in the IR verifier.
```
Given that we already do not model inline assembly, I think this instruction should be a noop and we should issue a warning about it.

@shaobo-he What do you think? If you agree, then I can easily implement this. Thx!

**Comment by shaobo-he** [comment]
> LLVM IR description says (https://llvm.org/docs/LangRef.html#callbr-instruction):
> 
> ```
> This instruction should only be used to implement the “goto” feature of gcc style inline assembly. Any other usage is an error in the IR verifier.
> ```
> 
> Given that we already do not model inline assembly, I think this instruction should be a noop and we should issue a warning about it.
> 
> @shaobo-he What do you think? If you agree, then I can easily implement this. Thx!

I agree.

**Comment by zvonimir** [comment]
This is fixed now.
