### ISSUE TITLE
Global structures

### ISSUE THREAD

**Issue by hernanponcedeleon** [smackers/smack#628]
Whenever there is a global array, the Boogie code has something like `const {:count X}` where `X` is the size of the array.
This works perfectly for me because I can use it as a hint that I should allocate that space in memory without having to use SMACK memory model.

Unfortunately the same is not true for structures. For example, the following code
```
struct {
int x;
int y;
} data;
```
would result in a constant 
```
const data: ref;
axiom (data == $sub.ref(0, 1032));
```
SMACK memory model would take care of allocating enough memory for `x` and `y`, but since I'm not using SMACKs memory model, I'm having problems with examples having global structures.

I was wondering if it would be possible to add the `{:count X}` tag (actually any kind of tag would work) for variables coming from global structures. I assume that this should not have any impact in SMACK analysis, but I cannot tell for sure.

**Comment by zvonimir** [comment]
Thanks for reporting this. Yeah, we can look into adding the same tag for global objects. I think it should be doable.
Having said that, we've been super busy with SVCOMP and other deadlines. Is this urgent?

**Comment by shaobo-he** [comment]
@hernanponcedeleon a follow-up question here: just to double-check we're at the same page, you'd like an attribute that tells how many bytes a global variable takes, right? In your example, it'd probably be `{:size 8}`. I used `size` here because `count` makes sense for arrays but not for structures.

**Comment by hernanponcedeleon** [comment]
> Thanks for reporting this. Yeah, we can look into adding the same tag for global objects. I think it should be doable.
> Having said that, we've been super busy with SVCOMP and other deadlines. Is this urgent?

No, it is not.



> @hernanponcedeleon a follow-up question here: just to double-check we're at the same page, you'd like an attribute that tells how many bytes a global variable takes, right? In your example, it'd probably be `{:size 8}`. I used `size` here because `count` makes sense for arrays but not for structures.

Yes, in the end what I need to know is how much space in the memory the object needs. The tag `size` looks good to me. Assuming the solution would also work out-of-the box for arrays, it would be useful to also have the tag for them.

**Comment by hernanponcedeleon** [comment]
@shaobo-he, did you have the change to take a look to this?

**Comment by hernanponcedeleon** [comment]
Hi @shaobo-he, any change you might have some time to take a look to this?

Sorry to be "pushy" but since @zvonimir said it should be doable, I decided to give it another try :D ... specially because now we are having quite a few problems because of this with benchmarks using structs

**Comment by shaobo-he** [comment]
> Hi @shaobo-he, any change you might have some time to take a look to this?
> 
> Sorry to be "pushy" but since @zvonimir said it should be doable, I decided to give it another try :D ... specially because now we are having quite a few problems because of this with benchmarks using structs

Hi @hernanponcedeleon, sorry for the late reply. I've been busy with work stuff and a paper deadline recently. I think I'll have some time to take a look at this over this weekend.

**Comment by shaobo-he** [comment]
Hi @hernanponcedeleon, I implemented something simple in 3aa7c34. Basically, it adds `:allocSize` attribute to globals. Please note that this size is derived from LLVM's `getTypeAllocSize` which includes alignment padding as opposed to `getTypeStoreSize`. We can easily change that if the latter is actually preferred. Could you give it a try and see that's what you want? If it looks good, I'll create a PR.

**Comment by hernanponcedeleon** [comment]
@shaobo-he thanks! it looks good to me. 

Just a short question before you merge. Is this (`getTypeAllocSize`) the same one you are using for computing your static heap allocation? The few examples I checked suggest that for every global variable, you assign it to some negative address and the difference between the addresses of two (consecutive) variables is 1024 + size of the variable (w.r.t `getTypeAllocSize` I assume). Am I correct about this?

**Comment by shaobo-he** [comment]
> @shaobo-he thanks! it looks good to me.
> 
> Just a short question before you merge. Is this (`getTypeAllocSize`) the same one you are using for computing your static heap allocation? The few examples I checked suggest that for every global variable, you assign it to some negative address and the difference between the addresses of two (consecutive) variables is 1024 + size of the variable (w.r.t `getTypeAllocSize` I assume). Am I correct about this?

No, the size in `1024 + size` is actually more complicated than the `allocSize` attribute. That being said, the essential case for the former leverages LLVM's `getTypeStoreSize`.

**Comment by hernanponcedeleon** [comment]
All good from my side so please go ahead with the PR.

Thanks for implementing this.

**Comment by zvonimir** [comment]
This has (finally) been merged. I apologize for the delay.

**Comment by hernanponcedeleon** [comment]
NP. Thanks for taking care of this
