### ISSUE TITLE
Set up continuous integration for SMACK

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#64]
I feel like we reached a development stage with SMACK where we (or at least myself :)) are wasting a lot of time catching and fixing issues with our build system. So it would be great to set up some kind of continuous integration process with SMACK. That way we would catch any potential issues sooner, which would be helpful I think.

[Travis CI](https://travis-ci.org) seems like a good choice for both Linux and OS X builds, and that is where I would probably start.
[AppVeyor](http://www.appveyor.com/) might be good for Windows.

**Comment by jon-whit** [comment]
I've worked with Travis CI enough to feel comfortable setting it up. I'd have to familiarize myself with the build process. If you'd like me to look into that I would be more than willing to take a shot at it on a feature branch.

**Comment by jon-whit** [comment]
I've worked with Travis CI enough to feel comfortable setting it up. I'd have to familiarize myself with the build process. If you'd like me to look into that I would be more than willing to take a shot at it on a feature branch.

**Comment by zvonimir** [comment]
That would be awesome and very helpful!

We have a bunch of build scripts (all of them were updated the other day and also ubuntu 14.04 was added) in our bin folder. You should be working of our develop branch. Given that Travis is it seems running Ubuntu 14.04, this would be the script I would start with:
https://github.com/smackers/smack/blob/develop/bin/build-linux-cmake.sh
I am curious if you would be able to install all the dependencies without any problems.

If you would like to create a feature branch, this is the branching model we try to follow:
http://nvie.com/posts/a-successful-git-branching-model/

Finally, drop me an email when needed and I will give you push privileges to our repo. Thx!

Oh, and another thing worth exploring would be whether Travis CI supports OS X. Actually, there is one more thing :) - Travis CI seems quite easy to use, which is great. But what we would ideally need is to be able to build on various Linux distros (Ubuntu, openSUSE, CentOS). So I also looked into that and some people are suggesting Jenkins + Vagrant for that, and there is even this Jenkins Vagrant plugin. I use Virtual Box on my desktop machine for such testing, and it would be awesome to automate that. So I would appreciate if you could explore that direction too, before we jump on Travis CI. I hope that is ok with you... Thanks :)!

**Comment by jon-whit** [comment]
Sounds great! I'll take a look into it. I'm quite familiar with Jenkins and Vagrant. I use Vagrant and Jenkins for development at the company I work for currently.

**Comment by jon-whit** [comment]
Also, as a follow up.. It appears that Travis CI has support for installing [Mac Packages](http://docs.travis-ci.com/user/installing-dependencies/#Installing-Mac-Packages).

**Comment by michael-emmi** [comment]
What is the status on this?

**Comment by jon-whit** [comment]
Jenkins CI is still running on kepler.cs.utah.edu:8080, so we have a functioning CI server building SMACK. I'm still working on getting Jenkins CI up and running on kornat.cs.utah.edu, but it's been a slow process due to some issues that arose with Vagrant. I started an internship with Intel and Micron Flash, so I've been occupied with that at the moment.

**Comment by zvonimir** [comment]
This has been a long story, but at this point we have Travis CI comfortably and reliably running our regressions. We moved away from Jenkins CI since we did not need support for multiple platforms any more. Closing this issue.
