### ISSUE TITLE
boogie to C mapping

### ISSUE THREAD

**Issue by hernanponcedeleon** [smackers/smack#659]
Thanks to #650 I learned that you are using some of clang debug information for e.g. getting the C line numbers.

I also noticed that clang provides information about variable declarations e.g.
```
!37 = !DILocalVariable(name: "j", scope: !31, file: !9, line: 16, type: !35)
```
Would it be possible to use such information to have a mapping between the boogie variables and the corresponding C ones? This would be super useful for e.g. witness generation.

**Comment by shaobo-he** [comment]
Hi @hernanponcedeleon, you should be able to find `boogie_si_record_*` calls in the Boogie code generated by SMACK. They serve as a mapping from C variable names to Boogie variables.

**Comment by hernanponcedeleon** [comment]
I cannot believe how I miss this!!!
This is exactly what I needed. Thanks @shaobo-he
