### ISSUE TITLE
Repeating variables in modifies clauses

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#67]
So all regressions are failing when using Boogie on the bitvector branch. The reason is that modifies clauses are generated with repeated variable names, such as this one:
modifies $Alloc, $CurrAddr, $exn, $exnv, $exn, $exnv, $M.0, $M.1;

Boogie does not like this and throws an exception... It is weird that nobody else encountered this issue.

**Comment by Guoanshisb** [comment]
There are redundant definitions for `$exn`, `$env`, `$extracvalue`. Fixed.

**Comment by michael-emmi** [comment]
What version of Boogie is used which complains about repeated modifies clauses? The version I have, below, which is the latest from Codeplex, does not complain.
````
Boogie program verifier version 2.3.0.61016, …
````

**Comment by zvonimir** [comment]
This is how we try to close issues:
https://help.github.com/articles/closing-issues-via-commit-messages/
When you do it like that, then there is a trail to the commit which fixed it, which is nice.

**Comment by zvonimir** [comment]
Mine is 4124:a776dc352a84 from Jan 28, so yours is newer Mike. I suspect that somebody pushed a bug into Boogie, which got fixed later on.
We should still fix this in SMACK, no point in repeating variables.

**Comment by zvonimir** [comment]
Can this be closed?

**Comment by zvonimir** [comment]
Shaobo fixed this in SMACK, and on top of that most Boogie versions seems to not experience this problem.
