### ISSUE TITLE
SMACK can generate inconsistent axioms on variables using the ``unique`` keyword

### ISSUE THREAD

**Issue by delcypher** [smackers/smack#71]
I've been experimenting with my proto-type symbolic execution tool on Boogie programs generated by SMACK and one of the things it does is check that satisfiability of axioms before it starts executing. It has detected unsatisfiable axioms in two programs that SMACK generated and that are in the [``sbb`` repo](https://github.com/smackers/sbb)

* [sv-comp/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--media--rc--keymaps--rc-lirc.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl](https://github.com/smackers/sbb/blob/master/sv-comp/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--media--rc--keymaps--rc-lirc.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl)
* [sv-comp/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--misc--tifm_core.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl](https://github.com/smackers/sbb/blob/master/sv-comp/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--misc--tifm_core.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl)

I'm using the programs from the ``sbb`` repo so these issues have been fixed since then, then please let me know.

The unsatisfiability of the axioms in these two programs relate to the use of the ``unique`` keyword.

In the first program the issue is basically the following declarations

```
axiom (lirc_map == -5210);
axiom (lirc == -5210);
const unique lirc: int;
const unique lirc_map: int;
```

The second programs was a bit trickier because the constraint enforcing the ``unique`` property is huge and there are many axioms but with the help of Z3's unsat core feature I managed to reduce the problem to the following declarations.

```
const unique __key___4: int;
const unique __key___5: int;
axiom (__key___4 == -6178);
axiom (__key___5 == -6178);
```

A nice way of confirming the issue is sticking ``assert false;`` at the beginning of entry points and passing it to a tool like Corral. You'll see no bugs reported due to the inconsistent assumptions in the program.

**Comment by michael-emmi** [comment]
Thanks for the bug report! we’ll look into it.

**Comment by delcypher** [comment]
@michael-emmi Thanks for taking a look at the issue. I had another look through the [generated SV-COMP benchmarks](https://github.com/smackers/sbb) and I had found two more that had inconsistent assumptions. My tool missed these because it currently removes "dead" global variables, functions and axioms before it starts checking the axioms.

These are

* [ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--caif--caif_virtio.ko-entry_point_true-unreach-call.cil.out.c_.bpl](https://github.com/smackers/sbb/blob/master/sv-comp/ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--caif--caif_virtio.ko-entry_point_true-unreach-call.cil.out.c_.bpl)
* [ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--staging--iio--dds--ad5930.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl
](https://github.com/smackers/sbb/blob/master/sv-comp/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--staging--iio--dds--ad5930.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl)

For the first program the issue is

```
const unique features: int;
...
const {:count 2} unique id_table: int;
...
axiom id_table == -6043;
axiom features == -6043;
```

For the second program the issue is

```
const unique __key___6: int;
const unique ldv_mutex: int;
...
axiom ldv_mutex == -5794;
...
axiom __key___6 == -5794;
```

I see you already have some fixes in, hopefully those catch these two issues as well but I thought I'd share them with you just in case they catch bugs elsewhere in SMACK.

**Comment by delcypher** [comment]
Appologies I had the last program path wrong it should be

* [ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--video--backlight--lcd.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl](https://github.com/smackers/sbb/blob/master/sv-comp/ldv-linux-3.4-simple/32_1_cilled_true-unreach-call_ok_nondet_linux-3.4-32_1-drivers--video--backlight--lcd.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.c_.bpl)
