### ISSUE TITLE
Allow targetted memory-safety checking

### ISSUE THREAD

**Issue by keram88** [smackers/smack#713]
Hello,

SMACK's memory-safety checking currently applies to every function which accesses memory. However, this behavior is not always necessary. For example, some languages such as Rust have have "safe" subsets that can be assumed to be memory-safe. In this circumstance, it may be desirable to only check memory safety on functions which are determined to be potentially unsafe.

Because it may be of some use for other programming languages where only a few functions may be determined to be potentially unsafe, this could be implemented by:
1) Adding a new option for indicating to SMACK which functions are interesting for checking memory safety (like the current `--entry-points` options).
2) Change the `MemorySafety` pass to only annotate the functions from 1.

Beyond implementation details, it is not clear what soundness issues could arise even if only truly unsafe functions were checked, i.e., could unsafe and unsafe code interact through global memory?

**Comment by zvonimir** [comment]
This is a great feature to implement, and we've seen the need for this in the past as well. I think we should maybe briefly meet to discuss this.

**Comment by shaobo-he** [comment]
I think this also enables some optimizations such as if a pointer points to a statically known size of memory.

**Comment by zvonimir** [comment]
I don't understand how this feature would enable that?

**Comment by zvonimir** [comment]
This is done. Closing.
