### ISSUE TITLE
Run smack with solver cvc4 get `Unexpected prover response` error

### ISSUE THREAD

**Issue by Sword-of-Damox** [smackers/smack#714]
Hello, Smacker's. I encountered a problem when using smack with cvc4 as solver.   
I run smack with following code:
```C
#include <stdlib.h>

void test1() {
  int *ptr = malloc(sizeof(int));
  ptr[1] = 10; // should failed at here
}
```
with command: `smack -v --check=memory-safety test-1.c -bpl test1.bpl --entry-points test1 --solver cvc4`

here's what I got:
```
SMACK program verifier version 2.6.3
WARNING: inttoptr @ addr 0xb12878 is (unsoundly) assumed to point to a fresh memory region.
 Corral program verifier version 1.0.17.0
 Single threaded program detected
 LB: Took 0.00 s
 Verifying program while tracking: {assertsPassed}
 Prover error: Unexpected prover response (getting info about 'unknown' response): (:reason-unknown incomplete)

 Corral encountered a prover error. Giving up.
 Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 959, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 911, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 91, in try_command
    raise Exception(output)
Exception: Corral program verifier version 1.0.17.0
Single threaded program detected
LB: Took 0.00 s
Verifying program while tracking: {assertsPassed}
Prover error: Unexpected prover response (getting info about 'unknown' response): (:reason-unknown incomplete)

Corral encountered a prover error. Giving up.
```

I dont known, is there my installation problem for cvc4 or cvc4 just dont work with corral?   
I checked with boogie also, with command: `smack -v --check=memory-safety test-1.c -bpl test1.bpl --entry-points test1 --solver cvc4 --verifier boogie`  
here's what I got:
```
SMACK program verifier version 2.6.3
WARNING: inttoptr @ addr 0x1114cf8 is (unsoundly) assumed to point to a fresh memory region.
 Prover error: Unexpected prover response (getting info about 'unknown' response): (:reason-unknown incomplete)

 test1.bpl(1498,25): Verification inconclusive (test1)

 Boogie program verifier finished with 0 verified, 0 errors, 1 inconclusive
 SMACK result is unknown.
```
 
I also run smack with fix version of this code:
```C
#include <stdlib.h>

void test1() {
    int *ptr = malloc(sizeof(int));
    ptr[0] = 10;
    free(ptr);
}
```
for using `corral` as verifier, it falls as showed before. but for `boogie`, it's strangely **verified**!? I checked the result bpl file, there's no compiler optimization as far as I can see. 

for most of the case, it seems to be same problem as `Unexpected prover response`.    
it may indicate my installation problem, but I fallowed the [cvc4 install instruction](https://github.com/CVC4/CVC4/blob/1.8/INSTALL.md), run similar command like:
```shell
./contrib/get-antlr-3.4
./configure.sh --python3
cd build
make
make check
make install
```
none of this getting any errors. so I dont known when or what I get it wrong?

I current using:
- Ubuntu 16.04
- smack 2.6.3
- Corral 1.0.17.0
- Boogie 2.8.6.0
- z3 4.8.9
- cvc4 1.8.0

Thanks.

**Comment by zvonimir** [comment]
Thanks for reporting this. I managed to reproduce it, and the issue seems to be related to incompleteness of CVC4. I filed the following issue with CVC4 developers, and we'll see what they say: https://github.com/CVC4/CVC4/issues/6274

**Comment by Sword-of-Damox** [comment]
Thanks, zvonimir !! I will follow this question on that branch. 
And since my question is not about Smack, I will close this issue. Thanks all.
