### ISSUE TITLE
Implicit type conversion

### ISSUE THREAD

**Issue by sanjit-bhat** [smackers/smack#721]
I'm not completely sure, but it seems like SMACK doesn't model implicit type conversion as per the C spec. For a concrete MVE, the following code in SMACK gives me an assertion error with `a = 2147483648UL (-2147483648)` and `b = 6UL`. I ran SMACK with `--integer-encoding=bit-vector`.
```C
#include "smack.h"

int main(void) {
    int a = __VERIFIER_nondet_int();
    int b = __VERIFIER_nondet_unsigned_int();
    assume(a < -5);
    assume(b > 5 && b < 10);
    assert(a > b);
}
```

In the above example, the assertion should always pass. [The C ISO](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf), Section 6.3.1.8(1), states that for all arithmetic conversions,

> Otherwise, if the operand that has unsigned integer type has rank greater or equal to the rank of the type of the other operand, then the operand with signed integer type is converted to the type of the operand with unsigned integer type.

Applying this, we get that `a`, which is restricted to be negative, is converted to a very large unsigned number. Since `b` is restricted to be a small unsigned number, `a` is always greater than `b`. However, if `a` and `b` were incorrectly interpreted as integers or incorrectly converted to signed values, `a` would always be less than `b`.

Plugging the counterexample into C, I get that `a > b` produces `1` (True). That means the counterexample above triggers an assertion error in SMACK, even though C code would pass the assertion.
```C
#include <stdio.h>

int main(void) {
    int a = 2147483648UL;
    unsigned int b = 6UL;
    printf("%d", a > b);
}

**Comment by keram88** [comment]
Hi @sanjit-bhat,

Did you mean `unsigned int b = ...` in your first example? It appears you are comparing two signed ints in that example, which I believe shouldn't undergo any conversion in the comparison, so this should produce an assertion violation.

It's been a while since I've reviewed C's promotion rules, so I could be wrong, but I think SMACK is doing the right thing here. Changing the types in the first example to the types in the second gives the expected result.

Thanks,
Mark

**Comment by zvonimir** [comment]
Indeed, there is a discrepancy between the program you are verifying using SMACK and the C code you are using to test the counterexample. If I change the program you are trying to verify into (I changed `b` to be `unsigned int`):
```
#include "smack.h"

int main(void) {
    int a = __VERIFIER_nondet_int();
    unsigned int b = __VERIFIER_nondet_unsigned_int();
    assume(a < -5);
    assume(b > 5 && b < 10);
    assert(a > b);
}
```
then the assertion is passing when I invoke SMACK on it.

**Comment by zvonimir** [comment]
Alternatively, if I change your C program to match the program you are trying to verify (so `b` is just `int`):
```
#include <assert.h>

int main(void) {
    int a = 2147483648UL;
    int b = 6;
    assert(a > b);
}
```
then this assertion is indeed failing when I compile and run it.

**Comment by sanjit-bhat** [comment]
Hi @keram88 and @zvonimir,

Thank you both for your quick responses! You're right, that was a typo on my part when creating the issue.

I also realized I was alternating between using `smack` with and without `--integer-encoding=bit-vector`. It turns out that with the changed program, it fails without bit-vectors, but it passes with bit-vectors. I didn't realize that bit-vectors were needed for proper signed/unsignedness, but it makes sense now!

Just like how `smack` outputs a warning if you're doing bit operations without bit-vectors, could we add a warning if you use both signed/unsigned types in your program without using bit-vectors?

**Comment by zvonimir** [comment]
Great!

As a side note, this is a long story, but we have this issue when bit-vectors are not used because LLVM IR does not distinguish between signed and unsigned integers. Other LLVM IR based verifiers struggle with the same problem.

Absolutely! When you reported this, my first thought was exactly that we should really be issuing warnings about this. I'll create a pull request addressing this.

**Comment by sanjit-bhat** [comment]
Oh... that's an interesting point about LLVM. I saw that when I was comparing the IR for signed/signed and signed/unsigned relational operators. Both bitcodes had `i32` operands. The only thing that changed was the `icmp` instruction went from `sgt` to `ugt`. 

I assume this detection would happen at a higher level than the LLVM extraction stage?
