### ISSUE TITLE
Undefined behavior in `ExtractContracts.cpp`

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#724]
See:

https://github.com/smackers/smack/blob/465280b2433d3b61d1ebfc86f4ffb39ad0c047f3/lib/smack/ExtractContracts.cpp#L95

`LI.getLoopFor(B)` could be a nullptr if `B` is not in `LI`. We haven't hit a crash probably because it's a method call that doesn't access `this`.

**Comment by zvonimir** [comment]
This is fixed.
