### ISSUE TITLE
Update (or maybe remove) vsmack

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#729]
I just realized how outdated `vsmack` is. In fact, I could not get it up and running on my machine. And the SMACK version it comes with is ancient. We should do something about it - we should either update it and clean it up if needed, or we should remove it.

**Comment by zvonimir** [comment]
@michael-emmi Any thoughts on this?

**Comment by michael-emmi** [comment]
I'm not aware of anybody who is using this, so there's probably no reason to maintain it.
