### ISSUE TITLE
Vagrant installation guide too restrictive

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#737]
There are multiple providers for vagrant. For example, Hyper-V is shipped with Windows 10, so its users do not have to have VirtualBox installed.

**Comment by zvonimir** [comment]
Have you tried it with anything else?

**Comment by shaobo-he** [comment]
> Have you tried it with anything else?

I tried Hyper-V on my desktop. It works mostly smoothly except for some configurations (e.g., SMB) in which Vagrant provides detailed information.

**Comment by zvonimir** [comment]
Ok. Yeah, this makes sense. So maybe we should update our documentation a little bit.

**Comment by zvonimir** [comment]
Do you want to make this update?
We can say "SMACK has been tested and is commonly used with the following Vagrant setups, but we expect others to work as well:"
