### ISSUE TITLE
Docker do not work

### ISSUE THREAD

**Issue by TheKingShun** [smackers/smack#748]
when i try to build SMACK itself by source i meet so many problems so i try docker 
but the cmd output is:          fatal: not a git repository (or any of the parent directories): .git

VMware:
Ubuntu20.04LTS

**Comment by zvonimir** [comment]
What is the command that you used? Could you give up a bit more information about your setup so that we can help you out?

**Comment by TheKingShun** [comment]
use <Local Build>
1.docker version:20.10.2
2.download smackv2.7.0
3.unzip it & cd smack root
4.run docker build . -t smack
the cmd output: Installing required packages,...... and after a while output:
            The command '/bin/sh -c bin/build.sh' returned a non-zero code: 4

**Comment by zvonimir** [comment]
@shaobo-he or @keram88  could you help out here?
I don't know docker.

**Comment by keram88** [comment]
Hello @TheKingShun,

It seems that one of our dependencies is not present in the zip file version of the release, and the git configuration files aren't available either.
As a work around, can you try running this?
```
git clone https://github.com/smackers/smack.git
git checkout master
```
This should point the cloned SMACK repo at the most recent release version.
This should solve the error reported in your original post.

Best,
Mark

**Comment by TheKingShun** [comment]
@keram88 
Thanks to your help, I succeeded！！！！！！
