### ISSUE TITLE
`vsmack` link in `installation.md` is dead

### ISSUE THREAD

**Issue by avanhatt** [smackers/smack#756]
Hi! I was trying to follow `installation.md`, but the link to `vsmack` found [here](https://github.com/smackers/smack/blob/master/docs/installation.md#super-quick-setup-virtual-smack) results in a Github `Page not found`: https://github.com/smackers/smack/blob/master/docs/bin/vsmack

**Comment by shaobo-he** [comment]
Hey @avanhatt, thank you for your interest in SMACK. vsmack is outdated so we removed it in the latest release. The recommended way to install SMACK is either to use vagrant or Docker. I closed this issue but feel free to reopen it if you think it's not addressed.
