### ISSUE TITLE
Cleaning up smackd stuff

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#759]
It seems that initially many years ago `smackd` option (and `smackdOutput` function) were implemented to generate json output for the Eclipse SMACK plugin (that we named smackd). However, this plugin has not been maintained in years, and there is no point in keeping smackd functionality around.
Having said that, after I explored this for a bit, I noticed that `smackdOutput` was being used by the SVCOMP script. Why is that so?
I am trying to start a discussion on how to properly clean this up.

**Comment by zvonimir** [comment]
@shaobo-he you recently refactored this code. Any thoughts on this?
At the very least we should probably rename this function as something else and remove the `smackd` command line option (and maybe replace it with `json`).

**Comment by shaobo-he** [comment]
You're right about the origin of this function. We used it in the SV-COMP script because it used to generate JSON error traces. I agree it should be removed.

**Comment by zvonimir** [comment]
Why would we completely remove it? It is kind of nice to have json traces, no?

**Comment by shaobo-he** [comment]
> Why would we completely remove it? It is kind of nice to have json traces, no?

I didn't think of it when I refactored the code. I thought maybe we still have a need for smackd.

**Comment by zvonimir** [comment]
Sorry, what do you mean?
Does current `smackdOutput` generate a nice error trace in json format?
Is this error trace the same as the error trace we print on the screen?
Is `smackdOutput` actively used by the SVCOMP script?
This will help me to understand what the heck is going on here :). Thx!

**Comment by shaobo-he** [comment]
> Sorry, what do you mean? Does current `smackdOutput` generate a nice error trace in json format? Is this error trace the same as the error trace we print on the screen? Is `smackdOutput` actively used by the SVCOMP script? This will help me to understand what the heck is going on here :). Thx!

`smackdOutput` used to generate not-so-good error trace in JSON format and it was only used by the SV-COMP error witness generation function, which converts JSON error traces into error witnesses. The PR basically rewrote the JSON error trace generation and therefore made `smackdOutput` a wrapper of `json_output` function. 

We can just rename the `smackd` option into something like `json` and remove this function completely.
