### ISSUE TITLE
Boogie type error when verifying function contracts.

### ISSUE THREAD

**Issue by m-alvarez** [smackers/smack#87]
(Using SMACK 1.5.1, LLVM 3.5.2, and Boogie 2.3.0.61016 on Ubuntu 14.04 x64 and mono 3.8.0)
When trying to verify the following code:

```
#include <stdlib.h>
#include <smack.h>
#include <smack-contracts.h>
int g;
void p() {
    ensures(g == 0 && g == 0);
    g = 0;
}
int main() {
    return 0;
}
```

using the command `smackverify.py --verifier boogie main.c`, I get no output at all from the Boogie verifier. If I try to manually invoke boogie on the generated a.bpl, I get the following error message:

```
a.bpl(135,9): Error: a return expression must be of type bool (got: i1)
```

The line that triggers the error is returning a variable `$p2` of type `i1` from a function that should return a `bool`. If I change the return statement so that it returns `($p2 == 1)` boogie does succeed in verifying the property.

**Comment by zvonimir** [comment]
This seems to work fine now.
