### ISSUE TITLE
smackverify.py: Verifier not called properly when -o parameter contains a space

### ISSUE THREAD

**Issue by MontyCarter** [smackers/smack#89]
With smackverify.py if the filename passed in with the -o switch contains a space, the file is properly created by llvm2bpl.py, however, when the verifier is called, it seems to be splitting this name into two separate args.

I haven't had time to chase this down, but I wanted to get it recorded.  I also suspect it might apply to other switches where spaces can appear in the switch argument...

For example, with input test.c, if you call:

    smackverify.py test.c "test space.bpl"

the bpl file, "test space.bpl", is created, but the following output is seen:
    
    Usage error: Unknown command line argument: test
    Usage: cba fname [Flags]
    
    -------------------------------------------------------------
    Flags:
     /k:int                  Sets execution context bound
     /main:str               Sets main procedure name
     /recursionBound:int     Set recursion depth bound
     /trackAllVars           Track all shared variables.
     /track:str              Track variable str.
     /useArrayTheory         Use native array theory for z3.
                             (This doesn't allow user-defined types.)
     /timeLimit:n            Set Z3 timeout to n sec (default 500)
     /flags:file             Read flags from file.
     /printBoogieExt         Prints language extensions made to Boogie
    
    -------------------------------------------------------------
    
    SMACK encountered an error when invoking corral. Exiting...

This is only verified on linux, but I imagine it will likely apply to windows as well.

**Comment by jon-whit** [comment]
I get the same thing on Mac OSX. I'll take a look into that today. My first guess is that this is a side effect of Boogie itself. Boogie doesn't like being invoked on a filename containing a space. For example, running `boogie "test space.bpl"` returns the error:

```
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
*** Error: 'test': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).
```

It seems like Boogie treats the space separated tokens as separate programs all together.

**Comment by delcypher** [comment]
@jon-whit @MontyCarter It's not an issue with Boogie. It's SMACK's wrapper scripts
See #90

**Comment by MontyCarter** [comment]
@jon-whit @delcypher Dan's right, Jon.  Boogie relies on .NET, so it must be executed using mono.  The env var `boogie` gets exported as something like `mono /path/to/boogie.exe`.  Then, on top of this we use a wrapper to pass command line args to the corral and boogie env vars.  These are /src/bin/boogie and /src/bin/corral

I'm not entirely sure why you can't just pass command line args directly to the env var invocation, rather than using these wrappers...

**Comment by delcypher** [comment]
#90 was made against the wrong branch, #91 is against the development branch (confusingly not master)

**Comment by michael-emmi** [comment]
Please confirm whether this is resolved on develop.

**Comment by MontyCarter** [comment]
It seems like the bash scripts "boogie" and "corral" are now working properly, as they now accept bpl files with spaces in the name...  However, smack.py is still breaking things despite the fix.

The following four commands work as they should:

    boogie test\ space.bpl
    corral test\ space.bpl
    boogie "test space.bpl"
    corral "test space.bpl"

However, it seems smack.py is splitting a concatenated command line string before passing it to python's subprocess.  In smack.py's verify_bpl function, it builds a command by concatenating each argument using spaces as delimiters.  Just before it passes the command to try_command(), it splits this string on spaces (https://github.com/smackers/smack/blob/0716431ddabde70b218a51b08cc8a30fad0cf531/bin/smack.py#L281).  As a result, what should be 

    ["corral","test spaces.bpl"]

becomes 

    ["corral","test","spaces.bpl"]

Maybe it would be better to build these directly as lists, instead of space delimited string concatenations?
