### ISSUE TITLE
Mutiple precedure declarations for a single function

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#92]
Hi guys,

I found a bug when verifying one svcomp benchmark. In `ldv-consumption/32_7a_cilled_true-unreach-call_linux-3.8-rc1-drivers--media--usb--em28xx--em28xx.ko-main.cil.out.c`,  function `video_device_release` has two declarations with same id while different signatures:

`procedure video_device_release(p0:ref);`
`procedure video_device_release(p0:ref, p1:ref, p2:ref, p3:ref, p4:ref, p5:ref, p6:ref, p7:ref, p8:ref, p9:ref, p10:i32, p11:i32, p12:i32, p13:i16, p14:i64, p15:i32, p16:ref, p17:ref, p18:i32, p19:i64, p20:i64, p21:ref, p22:ref, p23:ref, p24:ref);`

It seems the users of this function is not limited to itself in `SmackRep::decl`.

**Comment by michael-emmi** [comment]
I cannot reproduce this on the develop branch. Please provide complete instructions to reproduce.

**Comment by Guoanshisb** [comment]
I cannot reproduce this bug on the latest develop branch either. I think this issue can be closed.
