### ISSUE TITLE
Change output folder of all *.bc and *.bpl files to match that passed on --bc and -o options

### ISSUE THREAD

**Issue by MontyCarter** [smackers/smack#93]
Smack currently leaves clutter of smack.bc and loopBound.bpl in current directory where smackverify.py was executed.

This is a problem if running things in a batch script, where smack gets executed from a single directory, but puts output files in a separate directory.

My proposed solution would be to grab the folder of any file passed with the --bc and -o command line options, and output any *.bc and *.bpl files in these directories, respectively.

**Comment by michael-emmi** [comment]
Can you clarify why it is problematic for intermediate files to be left in the working directory?

**Comment by MontyCarter** [comment]
This basically comes down to running SMACK in batch executions, specifically multiple parallelized executions.  Long story short, I'm worried about two instances stomping on each other.  For example, if instance 2 is in the process of overwriting smack.bc when instance 1 is trying read the smack.bc file it just wrote, I'm worried smack.bc wont be in a consistent state.

With that said, I'm open to other solutions, such as giving smackverify.py a command line option that sets the working directory.

The longer version is:

Right now I am working on a benchmarking framework for SVCOMP.  There is a main data folder, under which folders with timestamps get created for each benchmark run (e.g., exec_2015.05.20....).

The script runs from this main data folder.  If the input file is /data/sv-benchmarks/ntdrivers/benchmark1.c, then smackverify is called from the /data/ folder with "-o ./exec_<timestamp>/results/sv-benchmarks/ntdrivers/benchmark1.c.bpl" and with "--bc ./exec_<timestamp>/results/sv-benchmarks/ntdrivers/benchmark1.c.bc".

In order to parallelize benchmark testing, the current setup requires launching smackverify.py from the data folder multiple times concurrently.  I worry about one instance stomping on the smack.bc & loopBound.bpl of another instance.

**Comment by michael-emmi** [comment]
I believe this issue has been fixed. The `smack.py` script now generates only uniquely-named intermediate files — besides any `.bc` and `.bpl` targets specified as command-line options — and Corral no longer stores `loopBound.bpl` to disk.

Can you confirm resolution?

**Comment by MontyCarter** [comment]
Yes, this seems like it is working fine.

Sorry about the delay in confirmation.
