### ISSUE TITLE
Corral internal error when --bit-precise --unroll 8 is invoked

### ISSUE THREAD

**Issue by Guoanshisb** [smackers/smack#94]
Hi guys,

I got a Corral error message,
`Error, internal bug: Failed to find the failing assert`

when verifying the `bitvector/s3_clnt_1_false-unreach-call.BV.c.cil.c`.

Disabling `/bopt:proverOpt:OPTIMIZE_FOR_BV=true /bopt:z3opt:smt.relevancy=0` arguments to Corral will not repeat this bug.
Unrolling depth is less than 8 will not repeat this bug.
Adding `/trackAllVars /staticInlining` will crash Corral

**Comment by michael-emmi** [comment]
I cannot reproduce this bug with the following flags
````
Corral /trackAllVars /staticInlining /recursionBound:9 /bopt:proverOpt:OPTIMIZE_FOR_BV=true /bopt:z3opt:smt.relevancy=0
````
Can you please clarify how to reproduce this bug?

**Comment by Guoanshisb** [comment]
Not reproducible on develop branch. Maybe I was using an ancient version of corral then. Can you close it?
