### ISSUE TITLE
Mark smackverify.py command line options as comment in generated bpl files

### ISSUE THREAD

**Issue by MontyCarter** [smackers/smack#95]
To give some context to bpl files, it will be nice to know what options were used to generate them.  

I propose we create a comment header for each output bpl file that lists the arguments used to call smackverify.  This header should also include the SMACK version number (maybe even a git commit hash, since we often work off the develop branch).

To give this some context, we are generating bpl files for all SVCOMP benchmarks, and it will be nice to know what options were used to generate these, rather than storing that information in a separate file from the bpl's.  

It should also be useful when sending bpl files to the Boogie/Corral teams when we have strange bugs and such.

**Comment by michael-emmi** [comment]
Great idea Monty. I can look into this very soon.
