### ISSUE TITLE
--debug to smack.py causes error in smack executable

### ISSUE THREAD

**Issue by MontyCarter** [smackers/smack#98]
If smack.py is called with the `--debug` flag, when the smack executable is called to generate a bpl file, smack.py tries to pass a `-debug` flag.  The smack executable does not recognize this flag.

Running `smack -help` lists the valid arguments for `smack`, but this list does not include `-debug`.

**Comment by michael-emmi** [comment]
Can you be more specific about your configuration? Did you build SMACK in Release or Debug mode?

On my installation `smack -help` does not list a `-debug` flag, yet the `-debug` flag is nevertheless admitted, and helpfully outputs debugging information while running `smack -debug …`.

**Comment by MontyCarter** [comment]
Is Debug vs Release mode configured by adding the `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=Release` flag when calling cmake?

To double check things, I did a fresh checkout of the develop branch, and rebuilt smack using both `-DCMAKE_BUILD_TYPE=Debug` and `-DCMAKE_BUILD_TYPE=Release`.  Both of these had the same problem, where `-debug` is not recognized.

Here are the steps I took to build.

* Clone fresh copy of smackers/smack, checkout develop branch.
* Modify build.sh to not install dependencies, and to not use sudo for the `sudo make install` call that installs SMACK itself (line 370 of build.sh).
* Set `-DCMAKE_BUILD_TYPE=` to either `Debug` or `Release` in build.sh, on the cmake call for smack (line 368).
* Installed smack by calling `./build.sh --prefix /home/montgomc/projects/smack-project-debugtest/smack-install/` from the `/home/montgomc/projects/smack-project-debugtest/smack/bin/` folder.
* Imported `smack.enviornment`, double checked that I was using the correct instance of smack.
* Ran `smack -debug a.bc` on a .bc file I had lying around.
* Got unrecognized option error.

`mono -V` and `clang -v` give `3.8.0` and `3.5.2`, respectively.

**Comment by MontyCarter** [comment]
So Shaobo says this debug flag is being accepted on his machine...  He has llvm version 3.5.0.  At this point, I am guessing that llvm 3.5.2 has stopped recognizing this flag.

I've verified this problem on two machines, both of which are Ubuntu 14 machines, and I think both had llvm installed using packages (one of them I'm certain used apt-get to install llvm, and the other, I'm pretty sure...)

**Comment by zvonimir** [comment]
Yeah, I cannot reproduce this on my machine either. I think I see what probably happened here. When llvm-3.5 Ubuntu package is installed from their package repo (http://llvm.org/apt/), it probably at this point installs 3.5.2 by default. When I installed it from the same place several months ago, it was probably installing 3.5.0 by default. Hence this discrepancy, which kind of sucks.

Now, I am really not sure if we should be fixing this at this point, or leave it for later, when we will actually be bumping LLVM version. Thoughts?

**Comment by MontyCarter** [comment]
For this debug flag, it's not a big deal at all.

In general, though, here are my two cents:

I wonder if we should figure out a way to specify the version number more precisely when installing the package (perhaps this isn't possible...), as I am concerned that we'll run into similar issues with something more critical.

**Comment by zvonimir** [comment]
Yes, I looked precisely into this just now. And after I read what is provided in the link to their packages above, it seems that specifying a version precisely (i.e., including its last digit) is not possible. In other words, llvm-3.5 package in fact installs 3.5.2, and to me it seems that there is no explicit package for 3.5.0 any more. I would appreciate if someone else could confirm that.

**Comment by MontyCarter** [comment]
I checked and couldn't find a way to specify the third digit on the apt-get
repo, however, I did notice that there is a static download for "Clang for
Ubuntu14.04 Linux
<http://llvm.org/releases/3.5.1/clang+llvm-3.5.1-x86_64-linux-gnu.tar.xz>"
for 3.5.0 and 3.5.1 on http://llvm.org/releases/download.html.

I'm not sure if this would work (i.e., has all the necessary components),
but they seem to be keeping old versions available for quite some time.

**Comment by zvonimir** [comment]
Well, you can give it a try. My hunch is that those are just binaries, without headers and such. So my hunch is also to stick with proper packages. My hope is that things typically won't break between minor LLVM versions, and so we won't have to worry about this. Or we will just have to update SMACK a little bit now and then to by in sync with minor LLVM updates. Note that these minor releases are predominantly (if not even exclusively) bug fixes.

**Comment by shaobo-he** [comment]
We seem to have this issue fixed as no one can reproduce it anymore.
