### ISSUE TITLE
Modularize smack.py

### ISSUE THREAD

**Issue by MontyCarter** [smackers/smack#99]
# Overview

I am proposing that we modularize `smack.py` into proper python modules.  As more and more features get added to `smack.py`, it is going to become large and unmanageable as a single file.  Creating a proper python module for smack will help remedy this.

Also, I feel that `smack.py` would greatly benefit from defining some good abstraction layers, such as input and output abstraction interfaces.  The move to `smack.py` was definitely an improvement, but to move things into submodules will require a cleaner abstraction, such as not relying on globals, for example.

This is rather long, so I've broken it in to sections.  The Background section isn't required to understand the proposal, but it gives some justification/rationale for the proposal.  I also have some subsections that give some additional suggestions/commentary that aren't centrally important to the main idea of modularizing `smack.py`.  These should be seen as what I, personally, had in mind, rather than requirements of the overall goal of modularizing `smack.py`.

Finally, I want to emphasize that this suggestion is NOT going back in the direction of having multiple scripts that get executed from the command line (as with `smackverify.py`, `smackgen.py`, and `llvm2bpl.py`).  Instead, the logic of `smack.py` would be entirely offloaded to a python module,  whose submodules don't get used by themselves.
# Background

To integrate support for svcomp, we decided to build the necessary options directly into the main toolchain executable (`smack.py`).  For example, adding the `--svcomp` flag includes a different header file, `svcomp-smack.h`, rather than `smack.h`.  This adds definitions and declarations for functions that tools competing in svcomp are required give special meaning/handling to.  Another example is the error trace format required by svcomp, whose generation will be enabled with `--error-witness`.

As more and more features like this get added, I'm concerned that `smack.py` is going grow in to a long, unwieldy file.

The extra code for the `--svcomp` flag is rather short, but the code for generating the error witness trace file is around 150 lines.

Currently, in the svcomp2016 branch, I have the svcomp error trace generation code in a pseudo-module called `toSVCOMPformat.py`, which is currently located in the `bin/` folder.  `smack.py` imports this, but because things aren't organized as formal python modules, `toSVCOMPformat.py` must be in the same folder as `smack.py`.

The result of this is that `toSVCOMPformat.py` must be installed to the machine/local bin folder.  As more features are added, this will either lead to a massive, messy `smack.py` file, or a `bin/` install folder with lots of cluttering python pseudo-modules that never get executed directly and so don't belong in the `bin/` folder.
# Motivation

This proposal aims to keep the size of the main entry point (currently `smack.py`) short and manageable.  To do this, it will be necessary to break out some of the code from `smack.py`, and put it into python library modules.  Because these library modules won't get called directly from the command line, they belong in the `share/` folder, rather than the `bin/` folder.  To achieve this, it will be necessary to create proper python modules that the main entry point will import and call in to.

In addition to organizing the `bin/` folder, and moving supporting library modules into the `share/` folder, this change would also make the entire smack toolchain accessible from other python scripts, as they would be able to import our main smack python module.
### Motivating Example

I've been digging around in this other project called BenchExec.  Its entry point, `benchexec` is located in their `bin/` folder, and is a very short file that imports their python module, and calls `main()`.

The main script that gets executed, `benchexec`, can be seen at https://github.com/dbeyer/benchexec/blob/master/bin/benchexec.  It uses a relative path to locate the benchexec python module.

The main python module can be seen at https://github.com/dbeyer/benchexec/blob/master/benchexec/__init__.py.  It imports all of the submodules that it needs, and contains a `main()` function, which is executed by the `benchexec` script in `bin/`.

This project seems to be quite modular, and I think it does a good job of drawing lines for different abstraction layers.  It's a different type of project than a verification tool (it is a benchmarking framework), so it wouldn't translate exactly, but I think at the very least it demonstrates what advantages can be gained by converting things to python modules.
# Proposal

At the high level, I propose that we have a very simple `smack.py` file in the installation `bin/` folder (as we currently do), however, there would be no logic in this file.  Instead, it would use relative paths to find the `../share/pylib/smack/` folder, which would contain all of the old `smack.py` logic.  (Btw, I just made up these folder names.  They will need to be adjusted to match python module  creation/linking requirements, and be consistent and suitable for our own naming conventions)

This way, we can add additional supporting submodules to the `share/pylib/smack/` module, without cluttering `bin/`.
### Module organization

I don't have an exact organization in mind for how to abstract smack.py into submodules.  A util submodule could contain things like `try_command()`.  

One idea that I keep coming back to is to have a class that represents an error trace.  We currently have at least 3 formats for error trace output -- the standard command line stdout output format, a proprietary json format for the Eclipse IDE plugin, and an 'error witness' format for svcomp.  Further, there are at least 2 formats from other tools (boogie and corral) that we consume, and translate into these three output formats.  
It might make sense to have a submodule for boogie and a submodule for corral.  These two would submodules would generate a smack error trace object.  This smack error trace object could then have member functions to convert it into any of the three formats.
# Conclusion

I've got to run, but I wanted to get this posted so people could start thinking about it.  I'll post additional comments on this issue with some ideas if it seems like people are interested in this proposal.

**Comment by michael-emmi** [comment]
While I’m not sure I agree with many of your motivations, I do think that it would be good to adopt a more standard filesystem structure.

**Comment by michael-emmi** [comment]
While I’m not sure I agree with much of the aforementioned motivations, I do think it would be a good idea to adopt a more standard filesystem structure as we continue to expand, like that mentioned here:

http://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

Note that the top-level (Python) executable should be called `smack` and not `smack.py` — which would require renaming the existing `smack` executable to something else, e.g., `llvm2bpl` sounds good.

A good first step would thus be creating the hollow `bin/smack` Python executable which invokes `smack/main.py`, and renaming the existing `smack` executable to `llvm2bpl`. Once that is in place we can think of good modularizations for `smack/main.py` as we expand.

**Comment by shaobo-he** [comment]
This issue has been resolved. Thank you @MontyCarter
